import { Icon, IconName } from "@atoms/Icon";
import type { Meta, StoryObj } from "@storybook/react-vite";

import { Badge } from "./Badge";

const meta: Meta<typeof Badge> = {
  title: "Atoms/Badge",
  component: Badge,
  tags: ["autodocs"],
  argTypes: {
    children: { control: "text" },
    size: {
      control: { type: "select" },
      options: ["small", "medium"],
    },
    variant: {
      control: { type: "select" },
      options: ["default", "primary"],
    },
    disabled: { control: "boolean" },
    iconLeft: { control: "boolean" },
    iconRight: { control: "boolean" },
  },
};

export default meta;
type Story = StoryObj<typeof Badge>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T717" },
  },
  args: {
    children: "Badge",
    variant: "default",
    size: "medium",
  },
};

export const Primary: Story = {
  name: "Primary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T718" },
  },
  args: {
    children: "Badge",
    variant: "primary",
    size: "medium",
  },
};

export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T719" },
  },
  args: {
    children: "Badge",
    variant: "default",
    size: "small",
  },
};

export const SmallPrimary: Story = {
  name: "Small Primary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T720" },
  },
  args: {
    children: "Badge",
    variant: "primary",
    size: "small",
  },
};

export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T721" },
  },
  args: {
    children: "Badge",
    variant: "default",
    size: "medium",
    disabled: true,
  },
};

export const DisabledPrimary: Story = {
  name: "Disabled Primary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T722" },
  },
  args: {
    children: "Badge",
    variant: "primary",
    size: "medium",
    disabled: true,
  },
};

export const WithLeftIcon: Story = {
  name: "With Left Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T723" },
  },
  args: {
    children: "Search",
    variant: "default",
    size: "medium",
    iconLeft: <Icon name={IconName.SEARCH} />,
  },
};

export const WithRightIcon: Story = {
  name: "With Right Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T724" },
  },
  args: {
    children: "Next",
    variant: "primary",
    size: "medium",
    iconRight: <Icon name={IconName.CLOSE} />,
  },
};

export const WithBothIcons: Story = {
  name: "With Both Icons",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T725" },
  },
  args: {
    children: "Navigate",
    variant: "default",
    size: "medium",
    iconLeft: <Icon name={IconName.SEARCH} />,
    iconRight: <Icon name={IconName.CLOSE} />,
  },
};

export const AllVariants: Story = {
  name: "All Variants",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T726" },
  },
  render: () => (
    <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
      <Badge variant="default" size="medium">
        Badge
      </Badge>
      <Badge variant="primary" size="medium">
        Badge
      </Badge>
      <Badge variant="default" size="small">
        Badge
      </Badge>
      <Badge variant="primary" size="small">
        Badge
      </Badge>
      <Badge variant="default" size="medium" disabled>
        Badge
      </Badge>
      <Badge variant="primary" size="medium" disabled>
        Badge
      </Badge>
      <Badge variant="default" size="medium" iconLeft={<Icon name={IconName.SEARCH} />}>
        With Icon
      </Badge>
      <Badge variant="primary" size="medium" iconRight={<Icon name={IconName.CLOSE} />}>
        With Icon
      </Badge>
    </div>
  ),
};
