import { expect, within } from "storybook/test";

import { COLORS } from "./../../../utils/colors";
import { BarGraph } from "./BarGraph";

import type { BarDataSeries } from "./BarGraph";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof BarGraph> = {
  title: "Charts/BarGraph",
  component: BarGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof BarGraph>;

const generateBasicData = (): BarDataSeries[] => {
  const x = [200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      color: COLORS.ORANGE,
      x,
      y: [220, 180, 200, 135, 185, 160, 280, 225, 280],
    },
  ];
};

const generateGroupedBarData = (): BarDataSeries[] => {
  const x = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      color: COLORS.ORANGE,
      x,
      y: [140, 140, 195, 205, 230, 65, 300, 290, 175, 280],
    },
    {
      name: "Data B",
      color: COLORS.RED,
      x,
      y: [150, 75, 300, 210, 130, 75, 140, 35, 290, 70],
    },
    {
      name: "Data C",
      color: COLORS.GREEN,
      x,
      y: [55, 185, 225, 75, 105, 120, 215, 155, 90, 265],
    },
  ];
};

const generateStackedBarData = (): BarDataSeries[] => {
  const x = [200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      color: COLORS.ORANGE,
      x,
      y: [90, 105, 105, 45, 95, 70, 190, 135, 190],
    },
    {
      name: "Data B",
      color: COLORS.RED,
      x,
      y: [90, 75, 90, 90, 95, 90, 90, 90, 90],
    },
  ];
};

export const Basic: Story = {
  name: "Basic",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T966" },
  },
  args: {
    dataSeries: generateBasicData(),
    title: "Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const GroupedBars: Story = {
  name: "Grouped Bars",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T967" },
  },
  args: {
    dataSeries: generateGroupedBarData(),
    variant: "group",
    title: "Cluster Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Cluster Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const StackedBars: Story = {
  name: "Stacked Bars",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T968" },
  },
  args: {
    dataSeries: generateStackedBarData(),
    variant: "stack",
    title: "Stacked Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Two traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(2);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
    });
  },
};

export const CustomStyling: Story = {
  name: "Custom Styling",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T969" },
  },
  args: {
    dataSeries: generateGroupedBarData(),
    title: "Custom Bar Graph",
    xTitle: "X-Axis Label",
    yTitle: "Y-Axis Label",
    width: 1000,
    height: 600,
    barWidth: 16,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Custom Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Axis titles are displayed", async () => {
      expect(canvas.getByText("X-Axis Label")).toBeInTheDocument();
      expect(canvas.getByText("Y-Axis Label")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};
