import { expect, waitFor, within } from "storybook/test";

import { BarGraph } from "./BarGraph";

import type { BarDataSeries } from "./BarGraph";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof BarGraph> = {
  title: "Charts/Bar Graph",
  component: BarGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof BarGraph>;

const generateBasicData = (): BarDataSeries[] => {
  const x = [200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      x,
      y: [220, 180, 200, 135, 185, 160, 280, 225, 280],
    },
  ];
};

const generateGroupedBarData = (): BarDataSeries[] => {
  const x = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      x,
      y: [140, 140, 195, 205, 230, 65, 300, 290, 175, 280],
    },
    {
      name: "Data B",
      x,
      y: [150, 75, 300, 210, 130, 75, 140, 35, 290, 70],
    },
    {
      name: "Data C",
      x,
      y: [55, 185, 225, 75, 105, 120, 215, 155, 90, 265],
    },
  ];
};

const generatePipelineRunsByStatus = (): BarDataSeries[] => {
  // x positions are integer indices; xTickText supplies the day labels
  const x = [0, 1, 2, 3, 4, 5, 6];

  return [
    {
      name: "Success",
      x,
      y: [42, 51, 38, 60, 55, 12, 8],
      color: "#29A634",
    },
    {
      name: "Failed",
      x,
      y: [3, 5, 2, 7, 4, 1, 0],
      color: "#CD4246",
    },
  ];
};

const generateStackedBarData = (): BarDataSeries[] => {
  const x = [200, 300, 400, 500, 600, 700, 800, 900, 1000];

  return [
    {
      name: "Data A",
      x,
      y: [90, 105, 105, 45, 95, 70, 190, 135, 190],
    },
    {
      name: "Data B",
      x,
      y: [90, 75, 90, 90, 95, 90, 90, 90, 90],
    },
  ];
};

export const Basic: Story = {
  name: "Basic",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T966" },
  },
  args: {
    dataSeries: generateBasicData(),
    title: "Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const GroupedBars: Story = {
  name: "Grouped Bars",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T967" },
  },
  args: {
    dataSeries: generateGroupedBarData(),
    variant: "group",
    title: "Cluster Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Cluster Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const NoTitle: Story = {
  name: "No Title",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5462" },
  },
  args: {
    dataSeries: generateBasicData(),
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("No title block is rendered", async () => {
      expect(canvasElement.querySelector(".gtitle")).not.toBeInTheDocument();
      expect(canvas.queryByText("Bar Graph")).not.toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const StackedBars: Story = {
  name: "Stacked Bars",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T968" },
  },
  args: {
    dataSeries: generateStackedBarData(),
    variant: "stack",
    title: "Stacked Bar Graph",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Two traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(2);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
    });
  },
};

export const CategoricalXLabels: Story = {
  name: "Categorical X Labels",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5459" },
    docs: {
      description: {
        story:
          "Use `xTickText` to display categorical x-axis labels (e.g. days of the week). The numeric `x` values still drive bar positioning, but the rendered tick labels match `xTickText` in order.",
      },
    },
  },
  args: {
    dataSeries: generatePipelineRunsByStatus(),
    xTickText: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    variant: "group",
    title: "Pipeline Runs by Status",
    xTitle: "Day",
    yTitle: "Runs",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Pipeline Runs by Status")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("X-axis ticks show categorical labels, not integers", async () => {
      const tickLabels = [
        ...canvasElement.querySelectorAll(".xtick text"),
      ].map((node) => node.textContent);
      expect(tickLabels).toEqual([
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat",
        "Sun",
      ]);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Success")).toBeInTheDocument();
      expect(canvas.getByText("Failed")).toBeInTheDocument();
    });
  },
};

export const CustomStyling: Story = {
  name: "Custom Styling",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T969" },
  },
  args: {
    dataSeries: generateGroupedBarData(),
    title: "Custom Bar Graph",
    xTitle: "X-Axis Label",
    yTitle: "Y-Axis Label",
    width: 1000,
    height: 600,
    barWidth: 16,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Custom Bar Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Axis titles are displayed", async () => {
      expect(canvas.getByText("X-Axis Label")).toBeInTheDocument();
      expect(canvas.getByText("Y-Axis Label")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const ContainerFilled: Story = {
  name: "Container Filled (responsive)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5469" },
    layout: "fullscreen",
    docs: {
      description: {
        story:
          "Omit `width`/`height` and the chart fills its container, tracking size via a `ResizeObserver`. Wrapped here in an `h-80 w-full` box.",
      },
    },
  },
  args: {
    dataSeries: generateGroupedBarData(),
    title: "Fills its container",
    variant: "group",
  },
  decorators: [
    (Story) => (
      <div data-testid="fill-wrapper" className="h-80 w-full">
        <Story />
      </div>
    ),
  ],
  play: async ({ canvasElement, step }) => {
    await step("Chart canvas fills the container width", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot).toBeInTheDocument();
        expect(plot.clientWidth).toBeGreaterThanOrEqual(wrapper.clientWidth - 2);
      });
    });

    await step("Chart resizes in place when the container resizes", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      // Shrink the container; the ResizeObserver should drive a Plotly relayout
      // (not a full re-plot) so the canvas tracks the new width.
      wrapper.style.width = "440px";
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot.clientWidth).toBeGreaterThanOrEqual(420);
        expect(plot.clientWidth).toBeLessThanOrEqual(460);
      });
    });
  },
};

const barRegressionData: BarDataSeries[] = [
  { name: "Run 1", x: [0, 1, 2, 3, 4, 5], y: [10, 18, 14, 22, 19, 25] },
  { name: "Run 2", x: [0, 1, 2, 3, 4, 5], y: [8, 12, 17, 15, 21, 23] },
  { name: "Run 3", x: [0, 1, 2, 3, 4, 5], y: [13, 15, 12, 19, 17, 22] },
];

export const SmallSizeLegendRegression: Story = {
  name: "Small Size — Legend vs Ticks",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5470" },
    docs: {
      description: {
        story:
          "At a small size with a bottom legend and `xTickText`, the legend sits below the x-axis tick labels rather than overlapping them.",
      },
    },
  },
  args: {
    dataSeries: barRegressionData,
    xTickText: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    xTitle: "Month",
    yTitle: "Value",
    width: 360,
    height: 220,
    variant: "group",
    barWidth: 0.25,
  },
  play: async ({ canvasElement, step }) => {
    await step("Legend sits below the x-axis tick labels (no overlap)", async () => {
      await waitFor(() => {
        const ticks = [
          ...canvasElement.querySelectorAll<SVGTextElement>(".xtick text"),
        ];
        const legendItems = [
          ...canvasElement.querySelectorAll<SVGTextElement>(".legend .legendtext"),
        ];
        expect(ticks.length).toBeGreaterThan(0);
        expect(legendItems.length).toBeGreaterThan(0);
        const tickBottom = Math.max(
          ...ticks.map((node) => node.getBoundingClientRect().bottom),
        );
        const legendTop = Math.min(
          ...legendItems.map((node) => node.getBoundingClientRect().top),
        );
        expect(legendTop).toBeGreaterThanOrEqual(tickBottom - 2);
      });
    });
  },
};
