import { FlaskConical } from "lucide-react";
import { expect, within } from "storybook/test";


import { EmptyState } from "./EmptyState";

import type { Meta, StoryObj } from "@storybook/react-vite";

import { PATTERNS_COMPONENT_PREFIX } from "@/components/storybook-categories";
import { Button } from "@/components/ui/button";

const meta: Meta<typeof EmptyState> = {
  title: `${PATTERNS_COMPONENT_PREFIX}/Empty State`,
  component: EmptyState,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <div className="w-96 rounded-lg border bg-card">
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4912" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("No records yet")).toBeInTheDocument();
    expect(
      canvas.getByText(
        "Import a dataset or connect a data source to get started."
      )
    ).toBeInTheDocument();
  },
};

export const NoData: Story = {
  args: {
    variant: "no-data",
    action: <Button size="sm">Import data</Button>,
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4913" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("No records yet")).toBeInTheDocument();
    expect(
      canvas.getByRole("button", { name: "Import data" })
    ).toBeInTheDocument();
  },
};

export const NoResults: Story = {
  args: {
    variant: "no-results",
    action: (
      <Button variant="ghost" size="sm">
        Clear filters
      </Button>
    ),
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4914" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("No results found")).toBeInTheDocument();
    expect(
      canvas.getByRole("button", { name: "Clear filters" })
    ).toBeInTheDocument();
  },
};

export const NoAccess: Story = {
  args: { variant: "no-access" },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4915" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("Access restricted")).toBeInTheDocument();
    expect(
      canvas.getByText(
        "You don't have permission to view this resource. Contact your admin."
      )
    ).toBeInTheDocument();
  },
};

export const EmptyFolder: Story = {
  args: {
    variant: "empty-folder",
    action: (
      <Button size="sm" variant="outline">
        Upload files
      </Button>
    ),
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4916" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("This folder is empty")).toBeInTheDocument();
    expect(
      canvas.getByRole("button", { name: "Upload files" })
    ).toBeInTheDocument();
  },
};

export const ServerError: Story = {
  args: {
    variant: "server-error",
    action: (
      <Button size="sm" variant="outline">
        Retry
      </Button>
    ),
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4917" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("Something went wrong")).toBeInTheDocument();
    expect(canvas.getByRole("button", { name: "Retry" })).toBeInTheDocument();
  },
};

export const CustomContent: Story = {
  args: {
    icon: FlaskConical,
    title: "No experiments run yet",
    description: "Configure your protocol and run your first experiment.",
    action: <Button size="sm">Create experiment</Button>,
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4918" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("No experiments run yet")).toBeInTheDocument();
    expect(
      canvas.getByText(
        "Configure your protocol and run your first experiment."
      )
    ).toBeInTheDocument();
    expect(
      canvas.getByRole("button", { name: "Create experiment" })
    ).toBeInTheDocument();
  },
};

export const OverrideTitle: Story = {
  name: "Variant with overridden title",
  args: {
    variant: "no-data",
    title: "No pipelines configured",
    description: "Create a pipeline to start processing your data.",
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4919" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("No pipelines configured")).toBeInTheDocument();
    expect(
      canvas.getByText("Create a pipeline to start processing your data.")
    ).toBeInTheDocument();
    expect(canvas.queryByText("No records yet")).not.toBeInTheDocument();
  },
};

export const EmptyTitleAndDescription: Story = {
  name: "Empty strings hide title and description",
  args: {
    title: "",
    description: "",
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T4920" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.queryByText("No records yet")).not.toBeInTheDocument();
    const slot = canvasElement.querySelector('[data-slot="empty-state"]');
    expect(slot).not.toBeNull();
    expect(slot?.querySelector("p")).toBeNull();
  },
};
