import React from "react";
import { expect, within } from "storybook/test";

import AppHeader from "./AppHeader";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof AppHeader> = {
  title: "Patterns/AppHeader",
  component: AppHeader,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof AppHeader>;

const defaultAppHeaderPlay: Story["play"] = async ({ canvasElement, step }) => {
  const canvas = within(canvasElement);

  await step("Hostname displays", async () => {
    expect(canvas.getByText("localhost:3000")).toBeInTheDocument();
  });

  await step("Home and settings actions render", async () => {
    expect(canvas.getByRole("button", { name: "Home" })).toBeInTheDocument();
    expect(canvas.getByRole("button", { name: "Settings" })).toBeInTheDocument();
  });

  await step("User profile name is shown", async () => {
    expect(canvas.getByText("Chris Calo")).toBeInTheDocument();
  });
};

// Default example
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T871" },
  },
  args: {
    hostname: "localhost:3000",
    userProfile: {
      name: "Chris Calo",
    },
  },
  play: defaultAppHeaderPlay,
};

// With avatar
export const WithAvatar: Story = {
  name: "With Avatar",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T872" },
  },
  args: {
    hostname: "localhost:3000",
    userProfile: {
      name: "Chris Calo",
      avatar: "https://i.pravatar.cc/300",
    },
  },
  play: defaultAppHeaderPlay,
};

// Interactive example with action logging
const InteractiveDemo = () => {
  const [clickedAction, setClickedAction] = React.useState<string | null>(null);

  const handleHomeClick = () => {
    setClickedAction("Home icon clicked");
    setTimeout(() => setClickedAction(null), 2000);
  };

  const handleSettingsClick = () => {
    setClickedAction("Settings icon clicked");
    setTimeout(() => setClickedAction(null), 2000);
  };

  const handleProfileClick = () => {
    setClickedAction("User profile clicked");
    setTimeout(() => setClickedAction(null), 2000);
  };

  return (
    <div style={{ width: "100vw" }}>
      <AppHeader
        hostname="app.example.com"
        userProfile={{
          name: "Chris Calo",
          avatar: "https://i.pravatar.cc/300",
        }}
        onHomeClick={handleHomeClick}
        onSettingsClick={handleSettingsClick}
        onUserProfileClick={handleProfileClick}
      />

      {clickedAction && (
        <div
          style={{
            padding: "12px 16px",
            marginTop: "16px",
            backgroundColor: "#f0f9ff",
            border: "1px solid #deebff",
            borderRadius: "4px",
            fontFamily: "Inter, sans-serif",
            fontSize: "14px",
          }}
        >
          {clickedAction}
        </div>
      )}

      <div
        style={{
          padding: "16px",
          fontFamily: "Inter, sans-serif",
          fontSize: "14px",
          marginTop: "32px",
          color: "#6a737d",
        }}
      >
        <p>Click on any of the buttons above to see the interactions.</p>
      </div>
    </div>
  );
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T873" },
  },
  render: () => <InteractiveDemo />,
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Hostname displays", async () => {
      expect(canvas.getByText("app.example.com")).toBeInTheDocument();
    });

    await step("Home and settings actions render", async () => {
      expect(canvas.getByRole("button", { name: "Home" })).toBeInTheDocument();
      expect(canvas.getByRole("button", { name: "Settings" })).toBeInTheDocument();
    });

    await step("User profile name is shown", async () => {
      expect(canvas.getByText("Chris Calo")).toBeInTheDocument();
    });

    await step("Interaction hint is visible", async () => {
      expect(
        canvas.getByText("Click on any of the buttons above to see the interactions."),
      ).toBeInTheDocument();
    });
  },
};
