import { LifeBuoy, LogOut, Settings, User } from "lucide-react";
import { expect, userEvent, waitFor, within } from "storybook/test";

import { UserMenu } from "./UserMenu";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof UserMenu> = {
  title: "Composed/UserMenu",
  component: UserMenu,
  tags: ["autodocs"],
  parameters: {
    docs: {
      description: {
        component:
          "User account affordance — an avatar (initials or image) that opens a dropdown menu. " +
          "A composition over the `Avatar` + `DropdownMenu` primitives. Focus trap, keyboard " +
          "navigation, and Esc-to-close come from the underlying Radix `DropdownMenu`.",
      },
    },
  },
  args: {
    name: "Emily Liu",
    subtitle: "emily.liu@acme.com",
    groups: [
      {
        items: [
          { id: "profile", label: "Profile", icon: User },
          { id: "settings", label: "Settings", icon: Settings },
          { id: "help", label: "Help & support", icon: LifeBuoy },
        ],
      },
      {
        items: [
          { id: "logout", label: "Log out", icon: LogOut, variant: "destructive" },
        ],
      },
    ],
  },
};
export default meta;

type Story = StoryObj<typeof meta>;

/** Default: icon-only avatar trigger. */
export const Default: Story = {
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5493" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Avatar shows derived initials", async () => {
      expect(canvas.getByText("EL")).toBeInTheDocument();
    });
  },
};

/** Menu opened via click; verifies items, keyboard, and Esc-to-close. */
export const MenuOpen: Story = {
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5494" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);
    const menu = within(document.body);
    const trigger = canvas.getByRole("button", { name: /account menu/i });

    await step("Opens on click and shows the header + items", async () => {
      await userEvent.click(trigger);
      expect(await menu.findByRole("menu")).toBeInTheDocument();
      expect(menu.getByText("emily.liu@acme.com")).toBeInTheDocument();
      expect(menu.getByRole("menuitem", { name: "Settings" })).toBeInTheDocument();
      expect(menu.getByRole("menuitem", { name: "Log out" })).toBeInTheDocument();
    });

    await step("Esc closes the menu and restores focus", async () => {
      await userEvent.keyboard("{Escape}");
      await waitFor(() => expect(menu.queryByRole("menu")).not.toBeInTheDocument());
      expect(trigger).toHaveFocus();
    });

    await step("Keyboard opens and navigates the menu", async () => {
      trigger.focus();
      await userEvent.keyboard("{Enter}");
      expect(await menu.findByRole("menu")).toBeInTheDocument();
      await userEvent.keyboard("{ArrowDown}");
      // Radix roving focus moves real DOM focus onto a menu item.
      await waitFor(() =>
        expect(document.activeElement).toHaveAttribute("role", "menuitem")
      );
      await userEvent.keyboard("{Escape}");
    });
  },
};

/** Detailed variant — avatar plus name/subtitle row, for a sidebar footer. */
export const Detailed: Story = {
  args: { variant: "detailed", subtitle: "ADMIN", side: "right", align: "end" },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5495" },
  },
  decorators: [
    (Story) => (
      <div className="w-[220px] p-2 border border-sidebar-border rounded-md bg-sidebar">
        <Story />
      </div>
    ),
  ],
};

/** Initials are derived from the name when no image is supplied. */
export const SingleName: Story = {
  args: { name: "Tetra", subtitle: undefined, avatarSrc: undefined },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5496" },
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    expect(canvas.getByText("TE")).toBeInTheDocument();
  },
};
