/**
 * Which Jira workflow statuses are far enough along to audit.
 *
 * A ticket that is still Open or In Progress has no settled test coverage yet:
 * its stories may not be written, its Zephyr IDs not yet generated by the sync
 * workflow, and any "coverage gap" it reports is simply work in flight. Auditing
 * from Code review onwards keeps the report to tickets whose coverage is
 * supposed to be final.
 *
 * ## Why names and not status categories
 *
 * Jira sorts every status into exactly three categories (To Do / In Progress /
 * Done). In the SW workflow they fall out like this:
 *
 *   To Do        Open
 *   In Progress  In Progress, Code review, Verification
 *   Done         Closed
 *
 * The cutoff we want — "Code review or later" — falls *inside* the In Progress
 * category, so no category predicate can express it: `category >= In Progress`
 * lets plain In Progress through, and `category = Done` drops Code review and
 * Verification. Names are the only thing with the resolution to draw this line.
 *
 * The cost of names is that a status rename silently changes the audited set.
 * `validateStatusNames` below buys that protection back explicitly: the audit
 * checks its configured names against the project's real statuses up front and
 * fails loudly rather than quietly auditing fewer tickets.
 */

/** Statuses at or after code review — the default audited set. */
export const DEFAULT_AUDITED_STATUSES = ["Code review", "Verification", "Closed"] as const;

function normalize(status: string): string {
  return status.trim().toLowerCase();
}

export function isAuditedStatus(status: string, audited: readonly string[] = DEFAULT_AUDITED_STATUSES): boolean {
  const target = normalize(status);
  return audited.some((name) => normalize(name) === target);
}

/** One status as Jira defines it for a project, used to validate the configured names. */
export interface ProjectStatus {
  name: string;
  category?: string;
}

export class UnknownStatusError extends Error {
  constructor(
    readonly unknown: string[],
    readonly available: ProjectStatus[],
    projectKey: string,
  ) {
    const listed = available
      .map((status) => {
        const category = status.category ? ` (${status.category})` : "";
        return `    ${status.name}${category}`;
      })
      .join("\n");
    const named = unknown.map((name) => JSON.stringify(name)).join(", ");
    super(
      `Status ${named} does not exist in project ${projectKey} — ` +
        "it was probably renamed, which would otherwise silently shrink the audited set.\n\n" +
        `  Valid statuses:\n${listed}\n\n` +
        "  Pass --statuses to override the audited set, or --all-statuses to audit every status.",
    );
    this.name = "UnknownStatusError";
  }
}

/**
 * Fails when a configured status name is not one the project actually defines.
 *
 * This is the safety net that makes name-based filtering safe: without it, a
 * renamed "Code review" would just stop matching and the audit would quietly
 * skip every ticket in that status. Comparison is case-insensitive, matching
 * `isAuditedStatus`, so only a real rename trips it.
 */
export function validateStatusNames(
  configured: readonly string[],
  available: readonly ProjectStatus[],
  projectKey: string,
): void {
  // An empty list means the project statuses could not be read (e.g. the token
  // lacks the permission); the audit should not fail closed on a missing check.
  if (available.length === 0) return;
  const known = new Set(available.map((status) => normalize(status.name)));
  const unknown = configured.filter((name) => !known.has(normalize(name)));
  if (unknown.length > 0) throw new UnknownStatusError(unknown, [...available], projectKey);
}
