import * as React from "react";

import { plateOptionsFromCsvTriage } from "./csvPlateTriage";
import { PlateMapActionsMenu } from "./PlateMapActionsMenu";
import { PlateMapPlateSelector } from "./PlateMapPlateSelector";
import { PlatePaintGrid } from "./PlatePaintGrid";
import { resolveDimensions, allPositions } from "./wellGrid";
import { WellManifestTable } from "./WellManifestTable";
import { WellMetadataForm } from "./WellMetadataForm";

import type { PlateMapActionsMenuProps } from "./PlateMapActionsMenu";
import type { WellShape } from "./PlatePaintGrid";
import type {
  PlateFormat,
  PlateMapCsvTriage,
  PlateMapGroupOption,
  PlateMapPlateOption,
  WellColumn,
  WellField,
  WellId,
  WellRecord,
} from "./types";

import { Badge } from "@/components/ui/badge";
import { Card, CardAction, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";

const PLATE_WELL_KEY_SEPARATOR = "::";
const DEFAULT_PLATE_BARCODE_FIELD = "plateBarcode";
const DEFAULT_PLATE_BARCODE_HEADER = "Plate Barcode";

export function getPlateMapScopedWellId(plateBarcode: string, wellId: WellId): WellId {
  return `${plateBarcode}${PLATE_WELL_KEY_SEPARATOR}${wellId}`;
}

function wellIdFromPlateWellKey(plateId: string, key: WellId): WellId | undefined {
  const prefix = `${plateId}${PLATE_WELL_KEY_SEPARATOR}`;
  return key.startsWith(prefix) ? key.slice(prefix.length) : undefined;
}

export interface PlateMapEditorProps<T extends WellRecord = WellRecord> extends Omit<
  PlateMapActionsMenuProps,
  "hasEntries" | "className"
> {
  format: PlateFormat;
  rows?: number;
  columns?: number;
  values: Map<WellId, T>;
  onChange: (next: Map<WellId, T>) => void;
  selection: Set<WellId>;
  onSelectionChange: (next: Set<WellId>) => void;

  fields: WellField<T>[];
  tableColumns: WellColumn<T>[];

  /** Resolves the SVG fill color for a well. */
  colorForWell: (well: T | undefined, wellId: WellId) => string;
  /** Builds an empty record when a well is freshly created. */
  emptyEntry: (wellId: WellId) => T;
  /**
   * Merges the staged form record onto an existing well record on Apply.
   * Defaults to a shallow merge (form keys overwrite existing keys when set).
   */
  mergeOnApply?: (existing: T | undefined, staged: Partial<T>, wellId: WellId) => T;
  /** Filter for the manifest's "hide empty" mode. */
  isPopulated?: (row: T) => boolean;
  /** Select field cycled when double-clicking a single well, e.g. role painting. */
  cycleFieldOnWellDoubleClick?: keyof T & string;

  /** Optional header title (e.g. plate set name). */
  title?: string;
  /** Optional badges shown in the header next to the title. */
  badges?: React.ReactNode;
  /** Optional banner (e.g. import/error alert) shown above the layout. */
  banner?: React.ReactNode;
  /** Legend block rendered under the form column. */
  legend?: React.ReactNode;
  /** Form helper slot rendered between fields and the action row. */
  formExtras?: React.ReactNode;
  /** Footer actions (e.g. Save, Back). */
  footer?: React.ReactNode;
  /** Title for the plate grid panel. */
  plateTitle?: React.ReactNode;
  /** Optional controls shown next to the built-in actions menu. */
  plateToolbar?: React.ReactNode;
  /** User-provided plates available for this editor. Barcodes are never generated by the editor. */
  plates?: PlateMapPlateOption[];
  activePlateId?: string;
  onPlateChange?: (plateId: string) => void;
  /** Opens the host app's manual barcode entry flow for creating a plate. */
  onAddPlate?: () => void;
  addPlateLabel?: string;
  plateSelectorLabel?: string;
  /** Row field used to stamp the active user-provided barcode onto edited wells. Defaults to `plateBarcode`. */
  plateBarcodeField?: keyof T & string;
  /** Header for the automatic manifest barcode column. */
  plateBarcodeColumnHeader?: string;
  /** Hide the automatic manifest barcode column when plate-scoped editing is active. */
  hidePlateBarcodeColumn?: boolean;
  /** Optional grouped well shortcuts rendered under the grid. */
  groups?: PlateMapGroupOption[];
  activeGroupId?: string;
  onGroupClick?: (group: PlateMapGroupOption) => void;
  /** Custom hover summary for the strip above the grid. */
  renderHoverSummary?: (well: T | undefined, wellId: WellId) => React.ReactNode;
  /** Fixed well size. When unset, the grid grows with the available width. */
  cellSize?: number;
  /** Fill color for empty wells. Pass `null` to delegate empty wells to `colorForWell`. */
  emptyWellFillColor?: string | null;
  /** Well shape forwarded to `PlatePaintGrid`. Defaults to `"rect"`. */
  wellShape?: WellShape;
  autoScaleGrid?: boolean;
  minCellSize?: number;
  maxCellSize?: number;

  className?: string;
}

function defaultMerge<T extends WellRecord>(existing: T | undefined, staged: Partial<T>): T {
  return { ...(existing ?? ({} as T)), ...staged };
}

function mergePlateOptions(
  importedPlates: PlateMapPlateOption[],
  providedPlates: PlateMapPlateOption[] | undefined,
): PlateMapPlateOption[] {
  const merged = new Map<string, PlateMapPlateOption>();
  importedPlates.forEach((plate) => merged.set(plate.id, plate));
  (providedPlates ?? []).forEach((plate) => merged.set(plate.id, plate));
  return [...merged.values()];
}

function resolveActivePlate(
  plates: PlateMapPlateOption[],
  selectedPlateId: string | undefined,
): PlateMapPlateOption | undefined {
  const matchingPlate = plates.find((plate) => plate.id === selectedPlateId);
  if (matchingPlate) return matchingPlate;
  return selectedPlateId ? undefined : plates[0];
}

function buildScopedValues<T extends WellRecord>(values: Map<WellId, T>, plateKey: string | undefined) {
  if (!plateKey) return values;

  const next = new Map<WellId, T>();
  values.forEach((row, key) => {
    const wellId = wellIdFromPlateWellKey(plateKey, key);
    if (wellId) next.set(wellId, row);
  });
  return next;
}

function resolveImportedPlateSelection({
  importedPlates,
  selectedPlateId,
  isControlled,
  providedPlateCount,
}: {
  importedPlates: PlateMapPlateOption[];
  selectedPlateId?: string;
  isControlled: boolean;
  providedPlateCount: number;
}): string | null | undefined {
  const firstImportedPlateId = importedPlates[0]?.id;
  if (!firstImportedPlateId) return !isControlled && providedPlateCount === 0 ? null : undefined;
  return importedPlates.some((plate) => plate.id === selectedPlateId) ? undefined : firstImportedPlateId;
}

function shouldShowPlateSelector(plateCount: number, onAddPlate: PlateMapEditorProps["onAddPlate"]): boolean {
  return plateCount > 0 || !!onAddPlate;
}

function canUpdatePlateSelection(isControlled: boolean, onPlateChange: PlateMapEditorProps["onPlateChange"]): boolean {
  return !isControlled || !!onPlateChange;
}

function PlateMapEditorTitleBar({ title, badges }: { title?: string; badges?: React.ReactNode }) {
  if (!title && !badges) return null;

  return (
    <div className="flex flex-wrap items-center justify-between gap-2">
      {title ? <h2 className="text-lg font-semibold">{title}</h2> : <span />}
      {badges ? <div className="flex flex-wrap gap-2">{badges}</div> : null}
    </div>
  );
}

function PlateMapEditorLegend({ legend }: { legend?: React.ReactNode }) {
  if (!legend) return null;

  return (
    <>
      <Separator />
      {legend}
    </>
  );
}

export function PlateMapEditor<T extends WellRecord = WellRecord>({
  format,
  rows,
  columns,
  values,
  onChange,
  selection,
  onSelectionChange,
  fields,
  tableColumns,
  colorForWell,
  emptyEntry,
  mergeOnApply,
  isPopulated,
  cycleFieldOnWellDoubleClick,
  title,
  badges,
  banner,
  legend,
  formExtras,
  footer,
  plateTitle = "Plate",
  plateToolbar,
  plates,
  activePlateId,
  onPlateChange,
  onAddPlate,
  addPlateLabel,
  plateSelectorLabel,
  plateBarcodeField,
  plateBarcodeColumnHeader = DEFAULT_PLATE_BARCODE_HEADER,
  hidePlateBarcodeColumn = false,
  groups,
  activeGroupId,
  onGroupClick,
  renderHoverSummary,
  cellSize,
  emptyWellFillColor,
  wellShape,
  autoScaleGrid,
  minCellSize,
  maxCellSize,
  className,
  templates,
  templateId,
  onTemplateChange,
  onClearTemplate,
  onImportCsv,
  onExportCsv,
  onImportTemplate,
  onExportTemplate,
  csvAccept,
  templateAccept,
  label,
  align,
  side,
  importTemplateLabel,
  exportTemplateLabel,
  importCsvLabel,
  exportCsvLabel,
  clearLabel,
}: PlateMapEditorProps<T>) {
  const dims = resolveDimensions(format, rows, columns);
  const [staged, setStaged] = React.useState<Partial<T>>({});
  const [hoverPos, setHoverPos] = React.useState<WellId | null>(null);
  const [flashWell, setFlashWell] = React.useState<{ wellId: WellId; key: number }>();
  const [csvPlates, setCsvPlates] = React.useState<PlateMapPlateOption[]>([]);
  const [internalActivePlateId, setInternalActivePlateId] = React.useState<string>();

  const merge = mergeOnApply ?? defaultMerge<T>;
  const availablePlates = React.useMemo(() => mergePlateOptions(csvPlates, plates), [csvPlates, plates]);
  const isPlateSelectionControlled = activePlateId !== undefined;
  const selectedPlateId = activePlateId ?? internalActivePlateId;
  const activePlate = React.useMemo(
    () => resolveActivePlate(availablePlates, selectedPlateId),
    [availablePlates, selectedPlateId],
  );
  const activePlateBarcode = activePlate?.barcode;
  const activePlateKey = activePlateBarcode;
  const isPlateScoped = !!activePlateKey;
  const barcodeField = (plateBarcodeField ?? DEFAULT_PLATE_BARCODE_FIELD) as keyof T & string;
  const previousActivePlateKey = React.useRef<string | undefined>(activePlateKey);

  const scopedValues = React.useMemo(() => buildScopedValues(values, activePlateKey), [activePlateKey, values]);

  const toStoredWellKey = React.useCallback(
    (wellId: WellId): WellId => {
      if (!isPlateScoped || !activePlateKey) return wellId;
      return getPlateMapScopedWellId(activePlateKey, wellId);
    },
    [activePlateKey, isPlateScoped],
  );

  const handlePlateChange = React.useCallback(
    (plateId: string) => {
      if (!isPlateSelectionControlled) setInternalActivePlateId(plateId);
      onPlateChange?.(plateId);
    },
    [isPlateSelectionControlled, onPlateChange],
  );

  const handleImportCsv = React.useCallback(
    async (file: File, triage?: PlateMapCsvTriage) => {
      if (triage) {
        const nextCsvPlates = plateOptionsFromCsvTriage(triage);
        setCsvPlates(nextCsvPlates);
        const nextSelection = resolveImportedPlateSelection({
          importedPlates: nextCsvPlates,
          selectedPlateId,
          isControlled: isPlateSelectionControlled,
          providedPlateCount: plates?.length ?? 0,
        });

        if (nextSelection !== undefined) {
          if (!isPlateSelectionControlled) setInternalActivePlateId(nextSelection ?? undefined);
          if (nextSelection) onPlateChange?.(nextSelection);
        }
      }

      await onImportCsv?.(file, triage);
    },
    [isPlateSelectionControlled, onImportCsv, onPlateChange, plates, selectedPlateId],
  );

  const stampActivePlateBarcode = React.useCallback(
    (row: T): T => {
      if (!isPlateScoped || !activePlateBarcode) return row;
      return { ...(row as Record<string, unknown>), [barcodeField]: activePlateBarcode } as T;
    },
    [activePlateBarcode, barcodeField, isPlateScoped],
  );

  const commitScopedValues = React.useCallback(
    (nextScopedValues: Map<WellId, T>) => {
      if (!isPlateScoped || !activePlateKey) {
        onChange(nextScopedValues);
        return;
      }

      const next = new Map(values);
      [...next.keys()].forEach((key) => {
        if (wellIdFromPlateWellKey(activePlateKey, key)) {
          next.delete(key);
        }
      });
      nextScopedValues.forEach((row, wellId) => {
        next.set(toStoredWellKey(wellId), stampActivePlateBarcode(row));
      });
      onChange(next);
    },
    [activePlateKey, isPlateScoped, onChange, stampActivePlateBarcode, toStoredWellKey, values],
  );

  React.useEffect(() => {
    if (previousActivePlateKey.current === activePlateKey) return;
    previousActivePlateKey.current = activePlateKey;
    setStaged({});
    setHoverPos(null);
    setFlashWell(undefined);
    if (selection.size > 0) onSelectionChange(new Set());
  }, [activePlateKey, onSelectionChange, selection.size]);

  const doubleClickCycleField = React.useMemo(() => {
    if (!cycleFieldOnWellDoubleClick) return;
    const field = fields.find((f) => f.key === cycleFieldOnWellDoubleClick);
    if (field?.kind !== "select" || !field.options?.length) return;
    return field;
  }, [cycleFieldOnWellDoubleClick, fields]);

  const applyStagedToSelection = () => {
    if (selection.size === 0) return;
    const next = new Map(scopedValues);
    selection.forEach((wellId) => {
      const existing = next.get(wellId);
      const merged = stampActivePlateBarcode(merge(existing, staged, wellId));
      next.set(wellId, merged);
    });
    commitScopedValues(next);
  };

  const clearWells = () => {
    if (selection.size === 0) return;
    const next = new Map(scopedValues);
    selection.forEach((wellId) => next.delete(wellId));
    commitScopedValues(next);
  };

  const cycleWellField = React.useCallback(
    (wellId: WellId) => {
      if (!doubleClickCycleField?.options?.length) return;

      const next = new Map(scopedValues);
      const existing = next.get(wellId);
      const currentValue = existing?.[doubleClickCycleField.key];
      const currentIndex = doubleClickCycleField.options.findIndex((opt) => opt.value === currentValue);
      const nextOption = doubleClickCycleField.options[(currentIndex + 1) % doubleClickCycleField.options.length];
      if (!nextOption) return;

      const base = existing ?? emptyEntry(wellId);
      next.set(wellId, stampActivePlateBarcode({ ...base, [doubleClickCycleField.key]: nextOption.value } as T));
      commitScopedValues(next);
      setFlashWell((current) => ({ wellId, key: (current?.key ?? 0) + 1 }));
    },
    [commitScopedValues, doubleClickCycleField, emptyEntry, scopedValues, stampActivePlateBarcode],
  );

  const selectAll = () => {
    onSelectionChange(new Set(allPositions(dims)));
  };
  const deselectAll = () => onSelectionChange(new Set());

  const hoverEntry = hoverPos ? scopedValues.get(hoverPos) : undefined;

  const hoverFields = hoverEntry
    ? (fields
        .map((f) => {
          const v = hoverEntry[f.key];
          if (v === undefined || v === null || v === "") return null;
          if (f.kind === "select") {
            const opt = (f.options ?? []).find((o) => o.value === v);
            return opt?.label ?? String(v);
          }
          if (f.kind === "multiselect") {
            const arr = Array.isArray(v) ? (v as string[]) : [];
            if (arr.length === 0) return null;
            return arr
              .map((item) => (f.options ?? []).find((o) => o.value === item)?.label ?? item)
              .join(", ");
          }
          if (f.kind === "boolean") {
            return v ? f.label : null;
          }
          return String(v);
        })
        .filter(Boolean) as string[])
    : [];

  const hoverSummary = hoverPos
    ? (renderHoverSummary?.(hoverEntry, hoverPos) ?? [hoverPos, ...hoverFields].join(" • "))
    : " ";
  const manifestColumns = React.useMemo(() => {
    if (!isPlateScoped || !activePlateBarcode || hidePlateBarcodeColumn) return tableColumns;
    const alreadyHasBarcodeColumn = tableColumns.some(
      (column) => column.field === barcodeField || column.id === barcodeField,
    );
    if (alreadyHasBarcodeColumn) return tableColumns;

    const barcodeColumn: WellColumn<T> = {
      id: barcodeField,
      header: plateBarcodeColumnHeader,
      minWidth: 150,
      render: ({ row }) => {
        const barcode = row[barcodeField] ?? activePlateBarcode;
        return <Badge variant="outline">{String(barcode)}</Badge>;
      },
    };
    return [barcodeColumn, ...tableColumns];
  }, [activePlateBarcode, barcodeField, hidePlateBarcodeColumn, isPlateScoped, plateBarcodeColumnHeader, tableColumns]);
  const showPlateSelector = shouldShowPlateSelector(availablePlates.length, onAddPlate);
  const canChangePlate = canUpdatePlateSelection(isPlateSelectionControlled, onPlateChange);

  return (
    <div data-slot="plate-map-editor" className={cn("flex flex-col gap-4", className)}>
      <PlateMapEditorTitleBar title={title} badges={badges} />

      {banner}

      <div className="flex flex-wrap gap-3 xl:flex-nowrap">
        {/* Form column */}
        <Card className="flex w-full max-w-[360px] min-w-[300px] basis-[360px] flex-col" size="sm">
          <CardContent className="flex h-full flex-1 flex-col gap-3">
            <WellMetadataForm
              fields={fields}
              value={staged}
              onChange={setStaged}
              selectionSize={selection.size}
              onApply={applyStagedToSelection}
              onClear={clearWells}
              extras={formExtras}
            />
            <PlateMapEditorLegend legend={legend} />
          </CardContent>
        </Card>

        {/* Plate column */}
        <Card className="flex min-w-[360px] flex-1 flex-col" size="sm">
          <CardHeader className="border-b">
            <div className="flex min-w-0 flex-wrap items-center gap-2">
              <PlateMapActionsMenu
                templates={templates}
                templateId={templateId}
                onTemplateChange={onTemplateChange}
                onClearTemplate={onClearTemplate}
                hasEntries={values.size > 0}
                onImportCsv={onImportCsv ? handleImportCsv : undefined}
                onExportCsv={onExportCsv}
                onImportTemplate={onImportTemplate}
                onExportTemplate={onExportTemplate}
                csvAccept={csvAccept}
                templateAccept={templateAccept}
                label={label}
                align={align}
                side={side}
                importTemplateLabel={importTemplateLabel}
                exportTemplateLabel={exportTemplateLabel}
                importCsvLabel={importCsvLabel}
                exportCsvLabel={exportCsvLabel}
                clearLabel={clearLabel}
              />
              <CardTitle className="min-w-0">{plateTitle}</CardTitle>
              {showPlateSelector ? (
                <PlateMapPlateSelector
                  plates={availablePlates}
                  activePlateId={activePlate?.id}
                  onPlateChange={canChangePlate ? handlePlateChange : undefined}
                  onAddPlate={onAddPlate}
                  addPlateLabel={addPlateLabel}
                  label={plateSelectorLabel}
                />
              ) : null}
            </div>
            <CardAction className="flex flex-wrap items-center gap-2">
              {plateToolbar}
              <div className="flex items-center gap-2 text-xs">
                <button
                  type="button"
                  className="font-medium text-primary underline-offset-2 hover:text-primary/80 hover:underline"
                  onClick={selectAll}
                >
                  Select all
                </button>
                <span className="text-muted-foreground/60">·</span>
                <button
                  type="button"
                  className="font-medium text-primary underline-offset-2 hover:text-primary/80 hover:underline"
                  onClick={deselectAll}
                >
                  Deselect all
                </button>
              </div>
            </CardAction>
          </CardHeader>
          <CardContent className="flex flex-col gap-1.5">
            <div className="h-5 text-xs text-muted-foreground">{hoverSummary}</div>
            <PlatePaintGrid
              format={format}
              rows={rows}
              columns={columns}
              values={scopedValues}
              selection={selection}
              onSelectionChange={onSelectionChange}
              colorForWell={colorForWell}
              emptyWellFillColor={emptyWellFillColor}
              wellShape={wellShape}
              onWellHover={setHoverPos}
              onWellDoubleClick={doubleClickCycleField ? cycleWellField : undefined}
              selectionFillMode={doubleClickCycleField ? "well" : "selection"}
              flashWellId={flashWell?.wellId}
              flashWellKey={flashWell?.key}
              cellSize={cellSize}
              autoScale={autoScaleGrid}
              minCellSize={minCellSize}
              maxCellSize={maxCellSize}
            />
            {groups && groups.length > 0 ? (
              <>
                <Separator className="mt-2" />
                <div className="flex max-h-28 flex-wrap gap-3 overflow-y-auto pt-1">
                  {groups.map((group) => {
                    const isActive = group.id === activeGroupId;
                    const count = group.count ?? group.wellIds?.length;
                    return (
                      <button
                        key={group.id}
                        type="button"
                        disabled={group.disabled}
                        onClick={() => onGroupClick?.(group)}
                        className={cn(
                          "flex w-16 flex-col items-center gap-1 rounded-md px-1 py-1 text-center text-xs transition-colors",
                          "text-muted-foreground hover:bg-muted/60",
                          isActive && "bg-muted text-foreground ring-1 ring-primary/40",
                          group.disabled && "pointer-events-none opacity-50",
                        )}
                        title={group.label}
                      >
                        <span
                          className="size-7 rounded-full border"
                          style={{
                            backgroundColor: group.color,
                            borderColor: group.borderColor,
                          }}
                          aria-hidden
                        />
                        <span className="w-full truncate text-foreground">{group.label}</span>
                        {count === undefined ? null : (
                          <span className="text-[0.7rem] leading-none text-muted-foreground">{count} wells</span>
                        )}
                      </button>
                    );
                  })}
                </div>
              </>
            ) : null}
          </CardContent>
        </Card>
      </div>

      <Card size="sm">
        <CardHeader className="border-b">
          <CardTitle>Sample manifest</CardTitle>
        </CardHeader>
        <CardContent>
          <WellManifestTable
            values={scopedValues}
            onChange={commitScopedValues}
            columns={manifestColumns}
            fields={fields}
            selection={selection}
            onSelectionChange={onSelectionChange}
            emptyEntry={emptyEntry}
            isPopulated={isPopulated}
          />
        </CardContent>
      </Card>

      {footer ? <div className="flex justify-end gap-2 pt-2">{footer}</div> : null}
    </div>
  );
}

export { Badge as PlateBadge };
