import type { PlateFormat } from "@/components/charts/PlateMap";
import type * as React from "react";

export type { PlateFormat };

export type WellId = string;

/**
 * Generic per-well record. Callers supply concrete shape via the `T` generic
 * on `PlateMapEditor`. Permissive base accepts both interfaces and indexable
 * record types.
 */
export type WellRecord = NonNullable<unknown>;

/**
 * Field kinds rendered by `WellMetadataForm` and (when `editableInTable`) by
 * `WellManifestTable`.
 */
export type WellFieldKind =
  | "text"
  | "number"
  | "integer"
  | "boolean"
  | "date"
  | "datetime"
  | "time"
  | "select"
  | "multiselect"
  | "custom";

export interface WellSelectOption {
  value: string;
  label: string;
  /** Optional swatch color shown next to the label. */
  swatch?: string;
}

export interface WellField<T extends WellRecord = WellRecord> {
  /** Key in the well record this field reads/writes. */
  key: keyof T & string;
  label: string;
  /** Optional leading icon shown in form labels and matching table headers. */
  icon?: React.ReactNode;
  kind: WellFieldKind;
  placeholder?: string;
  /** Required for `kind: "select"` and `kind: "multiselect"`. */
  options?: WellSelectOption[];
  /** Visual style for `kind: "boolean"`. Defaults to `"checkbox"`. */
  boolStyle?: "checkbox" | "switch";
  /**
   * When true, matching `WellManifestTable` cells render an inline editor of
   * this field's `kind` (mirroring the form). Defaults to false — cells stay
   * read-only unless the developer opts in or supplies `WellColumn.render`.
   */
  editableInTable?: boolean;
  /**
   * Custom renderer for the form input. Receives current value and a setter
   * that patches the field on the staged form record.
   */
  render?: (ctx: { value: unknown; onChange: (next: unknown) => void; selectionSize: number }) => React.ReactNode;
}

export interface WellColumn<T extends WellRecord = WellRecord> {
  /** Stable id; falls back to `field` if omitted. */
  id?: string;
  header: string;
  /** Optional leading icon in the table header. */
  icon?: React.ReactNode;
  /** Read direct property when `field` is set. */
  field?: keyof T & string;
  /** Min width in px (applied via inline style). */
  minWidth?: number;
  /**
   * Cell renderer. If omitted, the cell renders a display value. `select`
   * fields render as badge-style custom cells using the matching option label.
   */
  render?: (ctx: { row: T; wellId: WellId; update: (patch: Partial<T>) => void }) => React.ReactNode;
}

export interface TemplateOption {
  id: string;
  label: string;
  /** Optional group header in the dropdown (e.g. "Built-in", "User"). */
  group?: string;
  /** Optional supporting text for richer chooser menus. */
  description?: string;
  disabled?: boolean;
}

export interface PlateMapPlateOption {
  /** Stable plate id. For imported CSVs this should be the user-provided barcode. */
  id: string;
  /** User-provided plate barcode. Barcodes are never generated by the editor. */
  barcode: string;
  /** Optional display label when it differs from the barcode. */
  label?: string;
  /** Optional count shown beside the plate pill, usually imported row/well count. */
  count?: number;
  disabled?: boolean;
}

export interface PlateMapCsvRow {
  /** 1-based CSV line number, including the header line. */
  line: number;
  values: Record<string, string>;
}

export interface PlateMapCsvPlate {
  /** User-provided plate barcode used as the selectable plate id. */
  id: string;
  barcode: string;
  rows: PlateMapCsvRow[];
  rowCount: number;
}

export interface PlateMapCsvTriage {
  headers: string[];
  /** Resolved header name for the plate barcode column, when present. */
  plateBarcodeColumn?: string;
  rows: PlateMapCsvRow[];
  plates: PlateMapCsvPlate[];
  /** Rows missing a barcode. The editor does not create fallback barcodes. */
  missingBarcodeRows: PlateMapCsvRow[];
}

export interface PlateMapCsvTriageOptions {
  /** Exact column name to use before trying aliases. */
  plateBarcodeColumn?: string;
  /** Additional accepted names for the plate barcode column. */
  plateBarcodeColumnAliases?: readonly string[];
}

export interface ImportExportHandlers {
  onImportCsv?: (file: File, triage?: PlateMapCsvTriage) => void | Promise<void>;
  onExportCsv?: () => void;
  onImportTemplate?: (file: File) => void | Promise<void>;
  onExportTemplate?: () => void;
}

export interface PlateDimensions {
  rows: number;
  columns: number;
}

export interface PlateMapGroupOption {
  id: string;
  label: string;
  /** Well ids in the group; callers can use this to select the group. */
  wellIds?: WellId[];
  /** Optional explicit count; defaults to `wellIds.length` when present. */
  count?: number;
  color?: string;
  borderColor?: string;
  disabled?: boolean;
}

/**
 * Every user-facing string rendered by `WellManifestTable` (and the filter
 * popover it owns). All optional — an omitted key falls back to the English
 * default shown in its comment.
 */
export interface WellManifestTableLabels {
  /** "Show all wells" — toggles off the hide-empty filter. */
  showAllWells?: string;
  /** "Hide empty wells" */
  hideEmptyWells?: string;
  /** "Group by" — accessible name of the group-by select. */
  groupBy?: string;
  /** "Group by…" — placeholder of the group-by select. */
  groupByPlaceholder?: string;
  /** "No grouping" */
  noGrouping?: string;
  /** "Selected" — screen-reader name of the selection column. */
  selectedColumn?: string;
  /** "Well" — header of the well-id column. */
  wellColumn?: string;
  /** "No rows. Paint wells on the plate." */
  emptyRows?: React.ReactNode;
  /** "Rows per page" */
  rowsPerPage?: string;
  /** "Prev" */
  previousPage?: string;
  /** "Next" */
  nextPage?: string;
  /** "(blank)" — group key for rows whose grouped field is empty. */
  blankGroup?: string;
  /** "Filter" — trigger for the filter popover. */
  filter?: string;
  /** "Value…" — placeholder for a filter condition's value input. */
  filterValuePlaceholder?: string;
  /** "Clear all" — clears every active filter. */
  clearFilters?: string;
  /** Defaults to `` `${total} rows · ${selected} selected` ``. */
  rowSummary?: (total: number, selected: number) => string;
  /** Defaults to `` `(${count} rows)` ``, singular `row` at 1. */
  groupRowCount?: (count: number) => string;
  /** Defaults to `` `${from}–${to} of ${total}` ``, or `"0 of 0"` when empty. */
  pageRange?: (from: number, to: number, total: number) => string;
}

/**
 * Every user-facing string the `PlateMapEditor` shell renders, on top of the
 * manifest's own. All optional; omitted keys fall back to English defaults.
 *
 * Strings that are structural rather than incidental — `plateTitle`,
 * `manifestTitle`, and the import/export menu's labels — stay as their own
 * top-level props, because they are `ReactNode` slots rather than plain text.
 */
export interface PlateMapEditorLabels extends WellManifestTableLabels {
  /** "Apply" */
  apply?: string;
  /** "Clear wells" */
  clearWells?: string;
  /** "Select wells to edit" — form heading with an empty selection. */
  selectionEmpty?: string;
  /** Defaults to `` `Apply to ${n} wells` ``, singular `well` at 1. */
  selectionCount?: (selectionSize: number) => string;
  /** "Select all" */
  selectAll?: string;
  /** "Deselect all" */
  deselectAll?: string;
}
