import * as React from "react";

import { plateOptionsFromCsvTriage } from "./csvPlateTriage";
import { PLATE_MAP_EMPTY_WELL_FILL } from "./PlatePaintGrid";

import type { PlateMapCsvTriage, PlateMapPlateOption, WellField, WellId, WellRecord } from "./types";

const PLATE_WELL_KEY_SEPARATOR = "::";
const DEFAULT_PLATE_BARCODE_FIELD = "plateBarcode";

/** Scopes a well id to a plate barcode, matching the editor's storage key format. */
export function getPlateMapScopedWellId(plateBarcode: string, wellId: WellId): WellId {
  return `${plateBarcode}${PLATE_WELL_KEY_SEPARATOR}${wellId}`;
}

function wellIdFromPlateWellKey(plateId: string, key: WellId): WellId | undefined {
  const prefix = `${plateId}${PLATE_WELL_KEY_SEPARATOR}`;
  return key.startsWith(prefix) ? key.slice(prefix.length) : undefined;
}

/** Default `colorForWell` — populated wells read as filled, empty wells as surface. */
export function defaultColorForWell(well: unknown): string {
  return well === undefined ? PLATE_MAP_EMPTY_WELL_FILL : "var(--color-chart-1)";
}

/** Default `emptyEntry` — a blank record, sufficient when wells carry no required keys. */
export function defaultEmptyEntry<T extends WellRecord>(): T {
  return {} as T;
}

function defaultMerge<T extends WellRecord>(existing: T | undefined, staged: Partial<T>): T {
  return { ...(existing ?? ({} as T)), ...staged };
}

function mergePlateOptions(
  importedPlates: PlateMapPlateOption[],
  providedPlates: PlateMapPlateOption[] | undefined,
): PlateMapPlateOption[] {
  const merged = new Map<string, PlateMapPlateOption>();
  importedPlates.forEach((plate) => merged.set(plate.id, plate));
  (providedPlates ?? []).forEach((plate) => merged.set(plate.id, plate));
  return [...merged.values()];
}

function resolveActivePlate(
  plates: PlateMapPlateOption[],
  selectedPlateId: string | undefined,
): PlateMapPlateOption | undefined {
  const matchingPlate = plates.find((plate) => plate.id === selectedPlateId);
  if (matchingPlate) return matchingPlate;
  return selectedPlateId ? undefined : plates[0];
}

function buildScopedValues<T extends WellRecord>(values: Map<WellId, T>, plateKey: string | undefined) {
  if (!plateKey) return values;

  const next = new Map<WellId, T>();
  values.forEach((row, key) => {
    const wellId = wellIdFromPlateWellKey(plateKey, key);
    if (wellId) next.set(wellId, row);
  });
  return next;
}

function resolveImportedPlateSelection({
  importedPlates,
  selectedPlateId,
  isControlled,
  providedPlateCount,
}: {
  importedPlates: PlateMapPlateOption[];
  selectedPlateId?: string;
  isControlled: boolean;
  providedPlateCount: number;
}): string | null | undefined {
  const firstImportedPlateId = importedPlates[0]?.id;
  if (!firstImportedPlateId) return !isControlled && providedPlateCount === 0 ? null : undefined;
  return importedPlates.some((plate) => plate.id === selectedPlateId) ? undefined : firstImportedPlateId;
}

/**
 * Which plates Apply/Clear write to.
 *
 * - `"active-plate"` (default) — only the plate currently shown.
 * - `"all-plates"` — the same well positions on every plate in `plates`, each
 *   row stamped with its own plate's barcode. Falls back to `"active-plate"`
 *   when the editor isn't plate-scoped.
 */
export type PlateMapApplyScope = "active-plate" | "all-plates";

export interface UsePlateMapEditorStateOptions<T extends WellRecord = WellRecord> {
  values: Map<WellId, T>;
  onChange: (next: Map<WellId, T>) => void;
  selection: Set<WellId>;
  onSelectionChange: (next: Set<WellId>) => void;

  /** Builds an empty record when a well is freshly created. Defaults to `{}`. */
  emptyEntry?: (wellId: WellId) => T;
  /**
   * Merges the staged form record onto an existing well record on Apply.
   * Defaults to a shallow merge (form keys overwrite existing keys when set).
   */
  mergeOnApply?: (existing: T | undefined, staged: Partial<T>, wellId: WellId) => T;

  /**
   * Controlled staged form record. When provided, the hook stops owning staged
   * state — pair with `onStagedChange` to prefill the form, read what's staged,
   * or drive Apply from outside (bulk paste, "copy from another well", …).
   */
  staged?: Partial<T>;
  onStagedChange?: (next: Partial<T>) => void;

  /** Field schema, required only for `cycleFieldOnWellDoubleClick`. */
  fields?: WellField<T>[];
  /** Select field cycled when double-clicking a single well, e.g. role painting. */
  cycleFieldOnWellDoubleClick?: keyof T & string;

  /** User-provided plates. Barcodes are never generated by the editor. */
  plates?: PlateMapPlateOption[];
  activePlateId?: string;
  onPlateChange?: (plateId: string) => void;
  /** Row field used to stamp the active barcode onto edited wells. Defaults to `plateBarcode`. */
  plateBarcodeField?: keyof T & string;
  /**
   * Default scope for Apply/Clear. Defaults to `"active-plate"`.
   * Both functions accept a per-call override, so a host can offer
   * "Apply" and "Apply to all plates" side by side without changing this.
   */
  applyScope?: PlateMapApplyScope;
  onImportCsv?: (file: File, triage?: PlateMapCsvTriage) => void | Promise<void>;
}

export interface PlateMapEditorState<T extends WellRecord = WellRecord> {
  /** Staged form record applied across the selection on `applyStagedToSelection`. */
  staged: Partial<T>;
  setStaged: (next: Partial<T>) => void;
  /** Values narrowed to the active plate. Identical to `values` when unscoped. */
  scopedValues: Map<WellId, T>;
  /** Writes plate-scoped values back through `onChange`, re-scoping keys. */
  commitScopedValues: (next: Map<WellId, T>) => void;
  /**
   * Applies the staged record across the selection. Pass a scope to override
   * `applyScope` for this call.
   *
   * Safe to wire straight to `onClick` — a non-scope argument (such as the
   * click event React passes) is ignored and the default scope is used.
   */
  applyStagedToSelection: (scope?: PlateMapApplyScope) => void;
  /** Clears the selected wells. Same scope-override rules as Apply. */
  clearWells: (scope?: PlateMapApplyScope) => void;

  availablePlates: PlateMapPlateOption[];
  activePlate: PlateMapPlateOption | undefined;
  isPlateScoped: boolean;
  isPlateSelectionControlled: boolean;
  canChangePlate: boolean;
  handlePlateChange: (plateId: string) => void;
  handleImportCsv: (file: File, triage?: PlateMapCsvTriage) => Promise<void>;

  /** Set when `cycleFieldOnWellDoubleClick` resolves to a usable select field. */
  cycleWellField: ((wellId: WellId) => void) | undefined;
  flashWell: { wellId: WellId; key: number } | undefined;
  hoveredWellId: WellId | null;
  setHoveredWellId: (wellId: WellId | null) => void;
}

/**
 * The staged-edit controller behind `PlateMapEditor` — staged form record,
 * Apply/Clear across the selection, plate scoping and barcode stamping, CSV
 * plate triage, and double-click field cycling.
 *
 * Use it when you need a layout `PlateMapEditor` can't express and are
 * composing `PlateMapForm` / `PlateMapGrid` / `PlateMapManifest` yourself, so
 * you don't have to re-implement the apply semantics. `PlateMapEditor` is a
 * thin layout over this hook.
 */
export function usePlateMapEditorState<T extends WellRecord = WellRecord>({
  values,
  onChange,
  selection,
  onSelectionChange,
  emptyEntry = defaultEmptyEntry,
  mergeOnApply,
  staged: controlledStaged,
  onStagedChange,
  fields,
  cycleFieldOnWellDoubleClick,
  plates,
  activePlateId,
  onPlateChange,
  plateBarcodeField,
  applyScope = "active-plate",
  onImportCsv,
}: UsePlateMapEditorStateOptions<T>): PlateMapEditorState<T> {
  const [internalStaged, setInternalStaged] = React.useState<Partial<T>>({});
  const [hoveredWellId, setHoveredWellId] = React.useState<WellId | null>(null);
  const [flashWell, setFlashWell] = React.useState<{ wellId: WellId; key: number }>();
  const [csvPlates, setCsvPlates] = React.useState<PlateMapPlateOption[]>([]);
  const [internalActivePlateId, setInternalActivePlateId] = React.useState<string>();

  const isStagedControlled = controlledStaged !== undefined;
  const staged = controlledStaged ?? internalStaged;
  const setStaged = React.useCallback(
    (next: Partial<T>) => {
      if (!isStagedControlled) setInternalStaged(next);
      onStagedChange?.(next);
    },
    [isStagedControlled, onStagedChange],
  );

  const merge = mergeOnApply ?? defaultMerge<T>;
  const availablePlates = React.useMemo(() => mergePlateOptions(csvPlates, plates), [csvPlates, plates]);
  const isPlateSelectionControlled = activePlateId !== undefined;
  const selectedPlateId = activePlateId ?? internalActivePlateId;
  const activePlate = React.useMemo(
    () => resolveActivePlate(availablePlates, selectedPlateId),
    [availablePlates, selectedPlateId],
  );
  const activePlateBarcode = activePlate?.barcode;
  const activePlateKey = activePlateBarcode;
  const isPlateScoped = !!activePlateKey;
  const barcodeField = (plateBarcodeField ?? DEFAULT_PLATE_BARCODE_FIELD) as keyof T & string;
  const previousActivePlateKey = React.useRef<string | undefined>(activePlateKey);

  const scopedValues = React.useMemo(() => buildScopedValues(values, activePlateKey), [activePlateKey, values]);

  const toStoredWellKey = React.useCallback(
    (wellId: WellId): WellId => {
      if (!isPlateScoped || !activePlateKey) return wellId;
      return getPlateMapScopedWellId(activePlateKey, wellId);
    },
    [activePlateKey, isPlateScoped],
  );

  const handlePlateChange = React.useCallback(
    (plateId: string) => {
      if (!isPlateSelectionControlled) setInternalActivePlateId(plateId);
      onPlateChange?.(plateId);
    },
    [isPlateSelectionControlled, onPlateChange],
  );

  const handleImportCsv = React.useCallback(
    async (file: File, triage?: PlateMapCsvTriage) => {
      if (triage) {
        const nextCsvPlates = plateOptionsFromCsvTriage(triage);
        setCsvPlates(nextCsvPlates);
        const nextSelection = resolveImportedPlateSelection({
          importedPlates: nextCsvPlates,
          selectedPlateId,
          isControlled: isPlateSelectionControlled,
          providedPlateCount: plates?.length ?? 0,
        });

        if (nextSelection !== undefined) {
          if (!isPlateSelectionControlled) setInternalActivePlateId(nextSelection ?? undefined);
          if (nextSelection) onPlateChange?.(nextSelection);
        }
      }

      await onImportCsv?.(file, triage);
    },
    [isPlateSelectionControlled, onImportCsv, onPlateChange, plates, selectedPlateId],
  );

  const stampActivePlateBarcode = React.useCallback(
    (row: T): T => {
      if (!isPlateScoped || !activePlateBarcode) return row;
      return { ...(row as Record<string, unknown>), [barcodeField]: activePlateBarcode } as T;
    },
    [activePlateBarcode, barcodeField, isPlateScoped],
  );

  const commitScopedValues = React.useCallback(
    (nextScopedValues: Map<WellId, T>) => {
      if (!isPlateScoped || !activePlateKey) {
        onChange(nextScopedValues);
        return;
      }

      const next = new Map(values);
      [...next.keys()].forEach((key) => {
        if (wellIdFromPlateWellKey(activePlateKey, key)) {
          next.delete(key);
        }
      });
      nextScopedValues.forEach((row, wellId) => {
        next.set(toStoredWellKey(wellId), stampActivePlateBarcode(row));
      });
      onChange(next);
    },
    [activePlateKey, isPlateScoped, onChange, stampActivePlateBarcode, toStoredWellKey, values],
  );

  React.useEffect(() => {
    if (previousActivePlateKey.current === activePlateKey) return;
    previousActivePlateKey.current = activePlateKey;
    setStaged({});
    setHoveredWellId(null);
    setFlashWell(undefined);
    if (selection.size > 0) onSelectionChange(new Set());
  }, [activePlateKey, onSelectionChange, selection.size, setStaged]);

  const doubleClickCycleField = React.useMemo(() => {
    if (!cycleFieldOnWellDoubleClick) return;
    const field = (fields ?? []).find((f) => f.key === cycleFieldOnWellDoubleClick);
    if (field?.kind !== "select" || !field.options?.length) return;
    return field;
  }, [cycleFieldOnWellDoubleClick, fields]);

  // `onApply`/`onClear` are wired straight to `onClick` by `WellMetadataForm`,
  // so these receive a MouseEvent as their first argument. Only accept the two
  // literal scopes; anything else means "no override".
  const resolveScope = React.useCallback(
    (override?: unknown): PlateMapApplyScope =>
      override === "all-plates" || override === "active-plate" ? override : applyScope,
    [applyScope],
  );

  const appliesToEveryPlate = React.useCallback(
    (scope: PlateMapApplyScope) => scope === "all-plates" && isPlateScoped && availablePlates.length > 0,
    [availablePlates.length, isPlateScoped],
  );

  const applyStagedToSelection = React.useCallback(
    (scope?: PlateMapApplyScope) => {
      if (selection.size === 0) return;

      if (appliesToEveryPlate(resolveScope(scope))) {
        const next = new Map(values);
        availablePlates.forEach((plate) => {
          selection.forEach((wellId) => {
            const key = getPlateMapScopedWellId(plate.barcode, wellId);
            const base = next.get(key) ?? emptyEntry(wellId);
            const merged = merge(base, staged, wellId) as Record<string, unknown>;
            next.set(key, { ...merged, [barcodeField]: plate.barcode } as T);
          });
        });
        onChange(next);
        return;
      }

      const next = new Map(scopedValues);
      selection.forEach((wellId) => {
        const existing = next.get(wellId);
        const base = existing ?? emptyEntry(wellId);
        const merged = stampActivePlateBarcode(merge(base, staged, wellId));
        next.set(wellId, merged);
      });
      commitScopedValues(next);
    },
    [
      appliesToEveryPlate,
      availablePlates,
      barcodeField,
      commitScopedValues,
      emptyEntry,
      merge,
      onChange,
      resolveScope,
      scopedValues,
      selection,
      staged,
      stampActivePlateBarcode,
      values,
    ],
  );

  const clearWells = React.useCallback(
    (scope?: PlateMapApplyScope) => {
      if (selection.size === 0) return;

      if (appliesToEveryPlate(resolveScope(scope))) {
        const next = new Map(values);
        availablePlates.forEach((plate) => {
          selection.forEach((wellId) => next.delete(getPlateMapScopedWellId(plate.barcode, wellId)));
        });
        onChange(next);
        return;
      }

      const next = new Map(scopedValues);
      selection.forEach((wellId) => next.delete(wellId));
      commitScopedValues(next);
    },
    [
      appliesToEveryPlate,
      availablePlates,
      commitScopedValues,
      onChange,
      resolveScope,
      scopedValues,
      selection,
      values,
    ],
  );

  const cycleWellField = React.useCallback(
    (wellId: WellId) => {
      if (!doubleClickCycleField?.options?.length) return;

      const next = new Map(scopedValues);
      const existing = next.get(wellId);
      const currentValue = existing?.[doubleClickCycleField.key];
      const currentIndex = doubleClickCycleField.options.findIndex((opt) => opt.value === currentValue);
      const nextOption = doubleClickCycleField.options[(currentIndex + 1) % doubleClickCycleField.options.length];
      if (!nextOption) return;

      const base = existing ?? emptyEntry(wellId);
      next.set(wellId, stampActivePlateBarcode({ ...base, [doubleClickCycleField.key]: nextOption.value } as T));
      commitScopedValues(next);
      setFlashWell((current) => ({ wellId, key: (current?.key ?? 0) + 1 }));
    },
    [commitScopedValues, doubleClickCycleField, emptyEntry, scopedValues, stampActivePlateBarcode],
  );

  return {
    staged,
    setStaged,
    scopedValues,
    commitScopedValues,
    applyStagedToSelection,
    clearWells,
    availablePlates,
    activePlate,
    isPlateScoped,
    isPlateSelectionControlled,
    canChangePlate: !isPlateSelectionControlled || !!onPlateChange,
    handlePlateChange,
    handleImportCsv,
    cycleWellField: doubleClickCycleField ? cycleWellField : undefined,
    flashWell,
    hoveredWellId,
    setHoveredWellId,
  };
}
