# Force public npm registry for dependency resolution
# This ensures the package only depends on publicly-available packages
# and provides reproducible builds for external contributors
npmRegistryServer: "https://registry.npmjs.org"

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Package extensions to fix Storybook Yarn PnP compatibility issues
# These allow @storybook/addon-essentials and @storybook/addon-interactions
# to access their peer dependencies correctly
packageExtensions:
  "@storybook/addon-essentials@*":
    dependencies:
      "@storybook/addon-actions": "*"
      "@storybook/addon-backgrounds": "*"
      "@storybook/addon-controls": "*"
      "@storybook/addon-docs": "*"
      "@storybook/addon-measure": "*"
      "@storybook/addon-outline": "*"
      "@storybook/addon-toolbars": "*"
      "@storybook/addon-viewport": "*"
  "@storybook/addon-interactions@*":
    dependencies:
      "@storybook/global": "*"
      "@storybook/instrumenter": "*"
      "polished": "*"
      "storybook": "*"
