# Force public npm registry for dependency resolution
# This ensures the package only depends on publicly-available packages
# and provides reproducible builds for external contributors
npmRegistryServer: "https://registry.npmjs.org"

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.12.0.cjs
