import { expect, within } from "storybook/test";

import CodeScriptEditorButton from "./CodeScriptEditorButton";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof CodeScriptEditorButton> = {
  title: "Patterns/CodeScriptEditorButton",
  component: CodeScriptEditorButton,
  tags: ["autodocs"],
  argTypes: {
    language: {
      control: { type: "select" },
      options: ["python", "javascript", "typescript", "sql", "json", "yaml"],
    },
    disabled: {
      control: { type: "boolean" },
    },
    isEditMode: {
      control: { type: "boolean" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof CodeScriptEditorButton>;

// Basic examples
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T894" },
  },
  args: {
    initialCode: `def hello_world():
    print("Hello, World!")
    return "Hello, World!"

hello_world()`,
    language: "python",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders for default Python snippet", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats reflect initial code", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

export const Empty: Story = {
  name: "Empty",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T895" },
  },
  args: {
    initialCode: "",
    language: "python",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders with empty initial code", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Empty code shows zero lines and characters", async () => {
      expect(canvas.getByText("0 lines / 0 chars")).toBeInTheDocument();
    });
  },
};

export const JavaScript: Story = {
  name: "Java Script",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T896" },
  },
  args: {
    initialCode: `function helloWorld() {
  console.log("Hello, World!");
  return "Hello, World!";
}

helloWorld();`,
    language: "javascript",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders for JavaScript language", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Stats row shows line and character counts", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

export const SQL: Story = {
  name: "S Q L",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T897" },
  },
  args: {
    initialCode: `SELECT 
  id,
  name,
  email,
  created_at
FROM users 
WHERE active = true
ORDER BY created_at DESC
LIMIT 10;`,
    language: "sql",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders for SQL snippet", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

export const JSON: Story = {
  name: "J S O N",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T898" },
  },
  args: {
    initialCode: `{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "age": 30,
  "active": true,
  "preferences": {
    "theme": "dark",
    "notifications": true
  }
}`,
    language: "json",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders for JSON snippet", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

// State examples
export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T899" },
  },
  args: {
    initialCode: `def example():
    return "This editor is disabled"`,
    language: "python",
    disabled: true,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button is disabled", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeDisabled();
    });

    await step("Stats remain visible when disabled", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

// Custom text and titles
export const CustomLabels: Story = {
  name: "Custom Labels",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T900" },
  },
  args: {
    initialCode: `# Custom configuration script
config = {
    "api_endpoint": "https://api.example.com",
    "timeout": 30,
    "retries": 3
}`,
    language: "python",
    buttonText: "Configure Script",
    modalTitle: "Script Configuration",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Custom button label Configure Script is shown", async () => {
      expect(canvas.getByRole("button", { name: /configure script/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

// With callback
export const WithCallback: Story = {
  name: "With Callback",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T901" },
  },
  args: {
    initialCode: `print("Initial code")`,
    language: "python",
    onCodeSave: (code: string) => {
      console.log("Code saved:", code);
      alert(`Code saved! Length: ${code.length} characters`);
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders with onCodeSave callback wired", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Initial code length is reflected in stats", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

// Long code example
export const LongCode: Story = {
  name: "Long Code",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T902" },
  },
  args: {
    initialCode: `import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

def load_and_preprocess_data(file_path):
    """
    Load and preprocess the dataset
    """
    # Load the data
    data = pd.read_csv(file_path)
    
    # Handle missing values
    data = data.dropna()
    
    # Feature engineering
    data['feature_1_squared'] = data['feature_1'] ** 2
    data['feature_interaction'] = data['feature_1'] * data['feature_2']
    
    return data

def train_model(X, y):
    """
    Train a Random Forest model
    """
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # Initialize and train the model
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42
    )
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    
    print(f"Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(report)
    
    return model

# Main execution
if __name__ == "__main__":
    # Load and preprocess data
    data = load_and_preprocess_data("dataset.csv")
    
    # Prepare features and target
    X = data.drop('target', axis=1)
    y = data['target']
    
    # Train the model
    model = train_model(X, y)
    
    print("Model training completed!")`,
    language: "python",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders for long Python script", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Stats show large line and character counts", async () => {
      const stats = canvas.getByText(/\d+ lines \/ \d+ chars/);
      expect(stats).toBeInTheDocument();
      expect(stats.textContent).toMatch(/\d{2,} lines/);
    });
  },
};

// Different button variants
export const SmallButton: Story = {
  name: "Small Button",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T903" },
  },
  args: {
    initialCode: `console.log("Small button example");`,
    language: "javascript",
    buttonProps: {
      size: "small",
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders with small size", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

export const PrimaryButton: Story = {
  name: "Primary Button",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T904" },
  },
  args: {
    initialCode: `console.log("Primary button example");`,
    language: "javascript",
    buttonProps: {
      variant: "primary",
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders with primary variant", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};

export const SecondaryButton: Story = {
  name: "Secondary Button",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T905" },
  },
  args: {
    initialCode: `console.log("Secondary button example");`,
    language: "javascript",
    buttonProps: {
      variant: "secondary",
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Edit Code button renders with secondary variant", async () => {
      expect(canvas.getByRole("button", { name: /edit code/i })).toBeInTheDocument();
    });

    await step("Line and character stats are displayed", async () => {
      expect(canvas.getByText(/\d+ lines \/ \d+ chars/)).toBeInTheDocument();
    });
  },
};
