import { expect, within } from "storybook/test";

import { COLORS } from "./../../../utils/colors";
import { Boxplot } from "./Boxplot";

import type { BoxDataSeries } from "./Boxplot";
import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Boxplot> = {
  title: "Charts/Boxplot",
  component: Boxplot,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Boxplot>;

const generateBasicBoxData = (): BoxDataSeries[] => {
  return [
    {
      name: "Data A",
      color: COLORS.ORANGE,
      y: [155, 135, 175, 185, 120, 125, 140, 160, 180, 145, 170, 165, 150],
    },
  ];
};

const generateMultipleBoxData = (): BoxDataSeries[] => {
  return [
    {
      name: "Group 1",
      color: COLORS.ORANGE,
      y: [155, 135, 175, 185, 120, 125, 140, 160, 180, 145, 170, 165, 150],
      x: ["Group 1"],
    },
    {
      name: "Group 2",
      color: COLORS.RED,
      y: [90, 85, 95, 105, 75, 80, 88, 92, 98, 82, 96, 87, 91],
      x: ["Group 2"],
    },
    {
      name: "Group 3",
      color: COLORS.GREEN,
      y: [185, 165, 205, 215, 150, 155, 170, 190, 210, 175, 200, 195, 180],
      x: ["Group 3"],
    },
    {
      name: "Group 4",
      color: COLORS.BLUE,
      y: [220, 200, 240, 250, 185, 190, 205, 225, 245, 210, 235, 230, 215],
      x: ["Group 4"],
    },
    {
      name: "Group 5",
      color: COLORS.PURPLE,
      y: [135, 115, 155, 165, 100, 105, 120, 140, 160, 125, 150, 145, 130],
      x: ["Group 5"],
    },
  ];
};

const generateCategoricalBoxData = (): BoxDataSeries[] => {
  return [
    {
      name: "Category A",
      color: COLORS.ORANGE,
      y: [155, 135, 175, 185, 120, 125, 140, 160, 180, 145, 170, 165, 150, 155, 135, 175, 185, 120, 125, 140],
      x: [
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
        "200",
      ],
    },
    {
      name: "Category B",
      color: COLORS.RED,
      y: [90, 85, 95, 105, 75, 80, 88, 92, 98, 82, 96, 87, 91, 85, 95, 105, 75, 80, 88, 92],
      x: [
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
        "350",
      ],
    },
    {
      name: "Category C",
      color: COLORS.GREEN,
      y: [68, 45, 85, 95, 30, 35, 48, 68, 88, 53, 78, 73, 58, 65, 75, 85, 40, 45, 58, 72],
      x: [
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
        "500",
      ],
    },
    {
      name: "Category D",
      color: COLORS.BLUE,
      y: [220, 200, 240, 250, 185, 190, 205, 225, 245, 210, 235, 230, 215, 225, 195, 235, 245, 180, 185, 200],
      x: [
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
        "800",
      ],
    },
    {
      name: "Category E",
      color: COLORS.PURPLE,
      y: [135, 115, 155, 165, 100, 105, 120, 140, 160, 125, 150, 145, 130, 125, 135, 145, 90, 95, 110, 130],
      x: [
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
        "1000",
      ],
    },
  ];
};

export const Basic: Story = {
  name: "Basic",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T970" },
  },
  args: {
    dataSeries: generateBasicBoxData(),
    title: "Boxplot",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Boxplot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One box trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(1);
    });

    await step("Legend shows series name", async () => {
      expect(canvas.getAllByText("Data A").length).toBeGreaterThanOrEqual(1);
    });
  },
};

export const MultipleBoxes: Story = {
  name: "Multiple Boxes",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T971" },
  },
  args: {
    dataSeries: generateMultipleBoxData(),
    title: "Multiple Boxplots",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Multiple Boxplots")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Five box traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(5);
    });

    await step("Legend shows all group names", async () => {
      expect(canvas.getAllByText("Group 1").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Group 2").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Group 3").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Group 4").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Group 5").length).toBeGreaterThanOrEqual(1);
    });
  },
};

export const CategoricalData: Story = {
  name: "Categorical Data",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T972" },
  },
  args: {
    dataSeries: generateCategoricalBoxData(),
    title: "Boxplot",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Boxplot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Axis titles are displayed", async () => {
      expect(canvas.getByText("Columns")).toBeInTheDocument();
      expect(canvas.getByText("Rows")).toBeInTheDocument();
    });

    await step("Five box traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(5);
    });

    await step("Legend shows all category names", async () => {
      expect(canvas.getAllByText("Category A").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category B").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category C").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category D").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category E").length).toBeGreaterThanOrEqual(1);
    });
  },
};

export const WithOutliers: Story = {
  name: "With Outliers",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T973" },
  },
  args: {
    dataSeries: generateCategoricalBoxData(),
    title: "Boxplot with Outliers",
    xTitle: "Columns",
    yTitle: "Rows",
    showPoints: true,
    width: 1000,
    height: 600,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Boxplot with Outliers")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Axis titles are displayed", async () => {
      expect(canvas.getByText("Columns")).toBeInTheDocument();
      expect(canvas.getByText("Rows")).toBeInTheDocument();
    });

    await step("Five box traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(5);
    });

    await step("Points are rendered with box traces", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(5);
    });

    await step("Legend shows all category names", async () => {
      expect(canvas.getAllByText("Category A").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category B").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category C").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category D").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category E").length).toBeGreaterThanOrEqual(1);
    });
  },
};

export const CustomStyling: Story = {
  name: "Custom Styling",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T974" },
  },
  args: {
    dataSeries: generateCategoricalBoxData(),
    title: "Custom Boxplot",
    xTitle: "X-Axis Label",
    yTitle: "Y-Axis Label",
    width: 1000,
    height: 600,
    showPoints: true,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Custom Boxplot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Axis titles are displayed", async () => {
      expect(canvas.getByText("X-Axis Label")).toBeInTheDocument();
      expect(canvas.getByText("Y-Axis Label")).toBeInTheDocument();
    });

    await step("Five box traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".boxlayer .trace");
      expect(traces.length).toBe(5);
    });

    await step("Legend shows all category names", async () => {
      expect(canvas.getAllByText("Category A").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category B").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category C").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category D").length).toBeGreaterThanOrEqual(1);
      expect(canvas.getAllByText("Category E").length).toBeGreaterThanOrEqual(1);
    });
  },
};
