import Navbar from "./Navbar";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Navbar> = {
  title: "Molecules/Navbar",
  component: Navbar,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Navbar>;

// Default Navbar example
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T926" },
  },
  args: {
    organization: {
      name: "TetraScience",
      subtext: "tetrascience",
    },
  },
};
