import { expect, within } from "storybook/test";

import { COLORS } from "../../../utils/colors";

import { PieChart } from "./index";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Charts/PieChart",
  component: PieChart,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
} satisfies Meta<typeof PieChart>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1012" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector(".legend-container");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Temperature")).toBeInTheDocument();
    });
  },
};

export const WithCustomColors: Story = {
  name: "With Custom Colors",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1013" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
      colors: [COLORS.ORANGE, COLORS.RED, COLORS.GREEN, COLORS.BLUE, COLORS.PURPLE],
    },
    title: "Bioreactor Parameter Distribution",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor Parameter Distribution")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector(".legend-container");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Dissolved Oxygen")).toBeInTheDocument();
    });
  },
};

export const DonutChart: Story = {
  name: "Donut Chart",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1014" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution (Donut)",
    width: 480,
    height: 480,
    textInfo: "label+percent",
    hole: 0.5,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(
        canvas.getByText("Bioreactor Parameter Distribution (Donut)"),
      ).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector(".legend-container");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("Viability")).toBeInTheDocument();
      expect(legend.getByText("Cell Density")).toBeInTheDocument();
    });
  },
};

export const WithLabelAndValues: Story = {
  name: "With Label And Values",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1015" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution",
    width: 480,
    height: 480,
    textInfo: "label+value",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor Parameter Distribution")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector(".legend-container");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Temperature")).toBeInTheDocument();
    });
  },
};

export const WithRotation: Story = {
  name: "With Rotation",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1016" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution (Rotated)",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 45,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(
        canvas.getByText("Bioreactor Parameter Distribution (Rotated)"),
      ).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector(".legend-container");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("Dissolved Oxygen")).toBeInTheDocument();
      expect(legend.getByText("Cell Density")).toBeInTheDocument();
    });
  },
};
