import { expect, within } from "storybook/test";


import { PieChart } from "./index";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta = {
  title: "Charts/Pie Chart",
  component: PieChart,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
} satisfies Meta<typeof PieChart>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1012" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Temperature")).toBeInTheDocument();
    });

    await step("Legend color swatches have non-zero rendered size", async () => {
      const swatches = canvasElement.querySelectorAll<HTMLElement>(
        "[data-slot='pie-legend-swatch']",
      );
      expect(swatches.length).toBe(5);
      swatches.forEach((swatch) => {
        const rect = swatch.getBoundingClientRect();
        expect(rect.width).toBeGreaterThan(0);
        expect(rect.height).toBeGreaterThan(0);
      });
    });
  },
};

export const WithCustomColors: Story = {
  name: "With Custom Colors",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1013" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
      colors: ["#FFA62E", "#FF5C64", "#A5C34E", "#2D9CDB", "#7A51AB"],
    },
    title: "Bioreactor Parameter Distribution",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor Parameter Distribution")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Dissolved Oxygen")).toBeInTheDocument();
    });
  },
};

export const DonutChart: Story = {
  name: "Donut Chart",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1014" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution (Donut)",
    width: 480,
    height: 480,
    textInfo: "label+percent",
    hole: 0.5,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(
        canvas.getByText("Bioreactor Parameter Distribution (Donut)"),
      ).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("Viability")).toBeInTheDocument();
      expect(legend.getByText("Cell Density")).toBeInTheDocument();
    });
  },
};

export const WithLabelAndValues: Story = {
  name: "With Label And Values",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1015" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution",
    width: 480,
    height: 480,
    textInfo: "label+value",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Bioreactor Parameter Distribution")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
      expect(legend.getByText("Temperature")).toBeInTheDocument();
    });
  },
};

export const WithRotation: Story = {
  name: "With Rotation",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1016" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Bioreactor Parameter Distribution (Rotated)",
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 45,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(
        canvas.getByText("Bioreactor Parameter Distribution (Rotated)"),
      ).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("Dissolved Oxygen")).toBeInTheDocument();
      expect(legend.getByText("Cell Density")).toBeInTheDocument();
    });
  },
};

export const CompactDashboardTile: Story = {
  name: "Compact (Dashboard Tile)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    title: "Parameters",
    // `width` matches the tile; `height` is the plot height — the HTML title and
    // legend stack above/below it, so plot(200) + title + legend ≈ the 260 tile.
    width: 600,
    height: 200,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
    density: "compact",
  },
  render: (args) => (
    <div
      style={{
        width: 600,
        height: 260,
        border: "1px solid var(--border, #e2e8f0)",
        borderRadius: 8,
        overflow: "hidden",
      }}
    >
      <PieChart {...args} />
    </div>
  ),
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Compact title renders at the reduced size", async () => {
      const heading = canvas.getByText("Parameters");
      expect(heading).toBeInTheDocument();
      expect(heading.style.fontSize).toBe("14px");
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });

    await step("Legend shows parameter labels", async () => {
      const legendRoot = canvasElement.querySelector("[data-slot='pie-legend']");
      expect(legendRoot).toBeTruthy();
      const legend = within(legendRoot as HTMLElement);
      expect(legend.getByText("pH")).toBeInTheDocument();
    });
  },
};

export const NoTitle: Story = {
  name: "No Title",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5464" },
  },
  args: {
    dataSeries: {
      labels: ["pH", "Temperature", "Dissolved Oxygen", "Cell Density", "Viability"],
      values: [12, 23, 35, 18, 12],
      name: "Bioreactor Parameters",
    },
    width: 480,
    height: 480,
    textInfo: "percent",
    hole: 0,
    rotation: 0,
  },
  play: async ({ canvasElement, step }) => {
    await step("No title block is rendered", async () => {
      expect(canvasElement.querySelector(".title-container")).not.toBeInTheDocument();
      expect(canvasElement.querySelector(".title")).not.toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Pie layer and slices render", async () => {
      expect(canvasElement.querySelector(".pielayer")).toBeInTheDocument();
      const slices = canvasElement.querySelectorAll(".pielayer .slice");
      expect(slices.length).toBe(5);
    });
  },
};
