import { expect, within } from "storybook/test";

import LaunchContent from "./LaunchContent";

import type { Meta, StoryObj } from "@storybook/react-vite";


const meta: Meta<typeof LaunchContent> = {
  title: "Patterns/LaunchContent",
  component: LaunchContent,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <>
        <Story />
      </>
    ),
  ],
};

export default meta;

type Story = StoryObj<typeof LaunchContent>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T916" },
  },
  args: {
    initialCode: `protocolSchema: v3
name: v3
description: No description
config: {}
steps: []`,
    versions: ["v0.0.7", "v0.0.6", "v0.0.5"],
    currentVersion: "v0.0.7",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Deploy button is displayed", async () => {
      await expect(canvas.getByRole("button", { name: /deploy/i })).toBeInTheDocument();
    });

    await step("Version selector is displayed", async () => {
      await expect(canvas.getByRole("combobox")).toBeInTheDocument();
    });
  },
};

export const WithCallbacks: Story = {
  name: "With Callbacks",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T917" },
  },
  args: {
    ...Default.args,
    onDeploy: () => console.log("Deploy clicked!"),
    onVersionChange: (version) => console.log(`Version changed to ${version}`),
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Deploy button is displayed", async () => {
      await expect(canvas.getByRole("button", { name: /deploy/i })).toBeInTheDocument();
    });

    await step("Version selector is displayed", async () => {
      await expect(canvas.getByRole("combobox")).toBeInTheDocument();
    });
  },
};

export const WithDeploymentFeedback: Story = {
  name: "With Deployment Feedback",
  args: {
    ...Default.args,
    onDeploy: () => {
      console.log("Deploy complete!");
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Deploy button is displayed", async () => {
      await expect(canvas.getByRole("button", { name: /deploy/i })).toBeInTheDocument();
    });
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T918" },
    docs: {
      description: {
        story: 'Click the "Deploy" button to see toast notifications showing deployment status and success.',
      },
    },
  },
};

export const EmptyEditor: Story = {
  name: "Empty Editor",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T919" },
  },
  args: {
    initialCode: "",
    versions: ["v0.0.7", "v0.0.6", "v0.0.5"],
    currentVersion: "v0.0.7",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Deploy button is displayed", async () => {
      await expect(canvas.getByRole("button", { name: /deploy/i })).toBeInTheDocument();
    });

    await step("Version selector is displayed", async () => {
      await expect(canvas.getByRole("combobox")).toBeInTheDocument();
    });
  },
};
