import type { Meta, StoryObj } from "@storybook/react-vite";
import { Label } from "./Label";

const meta: Meta<typeof Label> = {
  title: "Atoms/Label",
  component: Label,
  tags: ["autodocs"],
  argTypes: {
    children: { control: "text" },
    infoText: { control: "text" },
  },
};

export default meta;
type Story = StoryObj<typeof Label>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T808" },
  },
  args: {
    children: "Label",
  },
};

export const WithInfoIcon: Story = {
  name: "With Info Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T809" },
  },
  args: {
    children: "Label",
    infoText: "This is additional information about the label",
  },
};

export const Complete: Story = {
  name: "Complete",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T810" },
  },
  args: {
    children: "Label",
    infoText: "This is additional information about the label",
  },
};
