import { useState } from "react";
import { expect, within } from "storybook/test";

import PythonEditorModal from "./PythonEditorModal";

import type { Meta, StoryObj } from "@storybook/react-vite";

import { Button } from "@/components/ui/button";

const meta: Meta<typeof PythonEditorModal> = {
  title: "Patterns/PythonEditorModal",
  component: PythonEditorModal,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;

type Story = StoryObj<typeof PythonEditorModal>;

export const Interactive = () => {
  const [open, setOpen] = useState(false);
  const [lastSaved, setLastSaved] = useState("");
  const initialCode = "def add(a, b):\n  return a + b\n\nresult = add(5, 3)\nprint(result)";

  return (
    <>
      <Button onClick={() => setOpen(true)}>Open Python Editor Modal</Button>

      <PythonEditorModal
        open={open}
        onOpenChange={setOpen}
        title="Edit Python Code"
        initialValue={lastSaved || initialCode}
        onSave={(value) => {
          setLastSaved(value);
          setOpen(false);
        }}
      />

      {lastSaved && (
        <div className="mt-4">
          <strong>Last Saved Code:</strong>
          <pre className="bg-muted p-3 rounded-lg overflow-auto max-h-[200px] font-mono text-sm mt-2">{lastSaved}</pre>
        </div>
      )}
    </>
  );
};
Interactive.storyName = "Interactive";
Interactive.parameters = {
  // Auto-generated by sync-storybook-zephyr - do not add manually
  zephyr: { testCaseId: "SW-T932" },
};
Interactive.play = async ({ canvasElement, step }) => {
  const canvas = within(canvasElement);

  await step("Open trigger button renders", async () => {
    expect(canvas.getByRole("button", { name: "Open Python Editor Modal" })).toBeInTheDocument();
  });
};

export const DefaultStory: Story = {
  name: "Default",
  parameters: {
    layout: "centered",
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T933" },
    docs: { story: { inline: false, iframeHeight: 400 } },
  },
  args: {
    open: true,
    onOpenChange: () => {},
    title: "Python Editor",
    initialValue: "def hello_world():\n  print('Hello, World!')\n\nhello_world()",
    onSave: (value) => console.log("Saving code:", value),
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement.ownerDocument.body);

    await step("Modal renders with title", async () => {
      expect(canvas.getByText("Python Editor")).toBeInTheDocument();
    });

    await step("Footer actions render", async () => {
      expect(canvas.getByRole("button", { name: "Cancel" })).toBeInTheDocument();
      expect(canvas.getByRole("button", { name: "Save Code" })).toBeInTheDocument();
    });
  },
};
