import { expect, within } from "storybook/test";

import ProtocolConfiguration from "./ProtocolConfiguration";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof ProtocolConfiguration> = {
  title: "Patterns/ProtocolConfiguration",
  component: ProtocolConfiguration,
  parameters: {
    layout: "padded",
  },
  tags: ["autodocs"],
  argTypes: {
    className: {
      control: { type: "text" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof ProtocolConfiguration>;

const protocolConfigurationPlay: Story["play"] = async ({ canvasElement, step }) => {
  const canvas = within(canvasElement);

  await step("Heading renders", async () => {
    expect(canvas.getByRole("heading", { name: "Protocol Configuration" })).toBeInTheDocument();
  });

  await step("Configuration card and empty state display", async () => {
    expect(canvas.getByText("Configuration")).toBeInTheDocument();
    expect(
      canvas.getByText("No values, Use the 'edit' button to add values"),
    ).toBeInTheDocument();
  });

  await step("Edit mode switch and label are visible", async () => {
    expect(canvas.getByText("Edit Mode")).toBeInTheDocument();
  });
};

// Basic examples
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T927" },
  },
  args: {},
  play: protocolConfigurationPlay,
};

export const WithCustomClassName: Story = {
  name: "With Custom Class Name",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T928" },
  },
  args: {
    className: "custom-protocol-config",
  },
  play: protocolConfigurationPlay,
};

// Interactive example showing both states
export const Interactive: Story = {
  name: "Interactive",
  args: {},
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T929" },
    docs: {
      description: {
        story: "Toggle the Edit Mode switch to see the different states of the component.",
      },
    },
  },
  play: protocolConfigurationPlay,
};

// Container example to show how it looks in a layout
export const InContainer: Story = {
  name: "In Container",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T930" },
  },
  args: {},
  decorators: [
    (Story) => (
      <div style={{ maxWidth: "800px", margin: "0 auto", padding: "20px" }}>
        <Story />
      </div>
    ),
  ],
  play: protocolConfigurationPlay,
};
