import { expect, waitFor, within } from "storybook/test";


import { ScatterGraph } from "./ScatterGraph";

import type { ScatterDataSeries } from "./ScatterGraph";
import type { Meta, StoryObj } from "@storybook/react-vite";

const generateScatterDemoData = (): ScatterDataSeries[] => {
  return [
    {
      name: "Data A",
      x: [400, 430, 450, 470, 490, 510, 530, 550, 570, 590, 610, 630, 650],
      y: [85, 72, 75, 92, 87, 125, 143, 145, 150, 165, 170, 160, 145],
    },
    {
      name: "Data B",
      x: [390, 410, 430, 450, 470, 490, 510, 530, 550, 570, 590, 610],
      y: [50, 75, 80, 85, 100, 105, 115, 135, 140, 150, 155, 145],
    },
    {
      name: "Data C",
      x: [410, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640],
      y: [60, 85, 90, 100, 110, 120, 125, 150, 160, 165, 175, 170],
    },
  ];
};

const meta: Meta<typeof ScatterGraph> = {
  title: "Charts/Scatter Graph",
  component: ScatterGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ScatterGraph>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1017" },
  },
  args: {
    dataSeries: generateScatterDemoData(),
    width: 900,
    height: 600,
    title: "Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const CustomRanges: Story = {
  name: "Custom Ranges",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1018" },
  },
  args: {
    ...Default.args,
    xRange: [300, 700],
    yRange: [0, 200],
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const ContainerFilled: Story = {
  name: "Container Filled (responsive)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
    layout: "fullscreen",
    docs: {
      description: {
        story:
          "Omit `width`/`height` and the chart fills its container, tracking size via a `ResizeObserver`. Wrapped here in an `h-80 w-full` box.",
      },
    },
  },
  args: {
    dataSeries: generateScatterDemoData(),
    title: "Fills its container",
  },
  decorators: [
    (Story) => (
      <div data-testid="fill-wrapper" className="h-80 w-full">
        <Story />
      </div>
    ),
  ],
  play: async ({ canvasElement, step }) => {
    await step("Chart canvas fills the container width", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot).toBeInTheDocument();
        expect(plot.clientWidth).toBeGreaterThanOrEqual(wrapper.clientWidth - 2);
      });
    });

    await step("Chart resizes in place when the container resizes", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      // Shrink the container; the ResizeObserver should drive a Plotly relayout
      // (not a full re-plot) so the canvas tracks the new width.
      wrapper.style.width = "440px";
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot.clientWidth).toBeGreaterThanOrEqual(420);
        expect(plot.clientWidth).toBeLessThanOrEqual(460);
      });
    });
  },
};
