import { expect, waitFor, within } from "storybook/test";

/** A Plotly plot div exposes `emit` to dispatch synthetic hover events. */
type EmittingPlot = HTMLElement & {
  emit: (event: string, data?: unknown) => void;
};

import { AreaGraph } from "./AreaGraph";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof AreaGraph> = {
  title: "Charts/Area Graph",
  component: AreaGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["normal", "stacked"],
    },
    width: {
      control: { type: "number" },
    },
    height: {
      control: { type: "number" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

const sampleDataSeries = [
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [120, 130, 100, 110, 140, 160, 150, 140, 110],
    name: "Series 1",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [30, 40, 50, 60, 70, 50, 40, 30, 20],
    name: "Series 2",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [20, 30, 25, 35, 40, 30, 25, 20, 15],
    name: "Series 3",
  },
];

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T963" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });

    await step("Tooltip shows the hovered point's own value", async () => {
      const plot = canvasElement.querySelector(".js-plotly-plot") as EmittingPlot;
      // Normal-mode traces carry no customdata, so the tooltip reports the
      // point's own y value directly.
      plot.emit("plotly_hover", {
        points: [{ x: 600, y: 140, data: { name: "Series 1" } }],
        event: new MouseEvent("mousemove", { clientX: 300, clientY: 200 }),
      });
      await waitFor(() => {
        const tip = document.querySelector('[data-slot="tooltip-content"]');
        expect(tip).toBeInTheDocument();
        expect(tip).toHaveTextContent("Rows: 140");
      });
      plot.emit("plotly_unhover");
    });
  },
};

export const Stacked: Story = {
  name: "Stacked",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T964" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Stacked Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "stacked",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });

    await step("Tooltip shows the series value, not the stacked sum", async () => {
      const plot = canvasElement.querySelector(".js-plotly-plot") as EmittingPlot;
      // Series 2 at x=600: own value 70, stacked y = 140 + 70 = 210
      plot.emit("plotly_hover", {
        points: [{ x: 600, y: 210, customdata: 70, data: { name: "Series 2" } }],
        event: new MouseEvent("mousemove", { clientX: 300, clientY: 200 }),
      });
      await waitFor(() => {
        const tip = document.querySelector('[data-slot="tooltip-content"]');
        expect(tip).toBeInTheDocument();
        expect(tip).toHaveTextContent("Rows: 70");
        expect(tip).not.toHaveTextContent("Rows: 210");
      });
      plot.emit("plotly_unhover");
    });
  },
};

const weekdayDataSeries = [
  {
    // x positions are integer indices; xTickText supplies the day labels
    x: [0, 1, 2, 3, 4, 5, 6],
    y: [120, 130, 100, 110, 140, 80, 60],
    name: "Throughput",
  },
];

export const CategoricalXLabels: Story = {
  name: "Categorical X Labels",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5458" },
    docs: {
      description: {
        story:
          "Use `xTickText` to display categorical x-axis labels (e.g. days of the week). The numeric `x` values still drive area positioning, but the rendered tick labels match `xTickText` in order.",
      },
    },
  },
  args: {
    dataSeries: weekdayDataSeries,
    xTickText: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    title: "Throughput by Weekday",
    xTitle: "Day",
    yTitle: "Files",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Throughput by Weekday")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("X-axis ticks show categorical labels, not integers", async () => {
      const tickLabels = [
        ...canvasElement.querySelectorAll(".xtick text"),
      ].map((node) => node.textContent);
      expect(tickLabels).toEqual([
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat",
        "Sun",
      ]);
    });
  },
};

export const CustomRange: Story = {
  name: "Custom Range",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T965" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph with Custom Range",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
    xRange: [300, 900],
    yRange: [0, 200],
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph with Custom Range")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });
  },
};

export const ContainerFilled: Story = {
  name: "Container Filled (responsive)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5467" },
    layout: "fullscreen",
    docs: {
      description: {
        story:
          "Omit `width`/`height` and the chart fills its container, tracking size via a `ResizeObserver`. Here it's wrapped in an `h-80 w-full` box.",
      },
    },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Fills its container",
    xTitle: "Columns",
    yTitle: "Rows",
    variant: "normal",
  },
  decorators: [
    (Story) => (
      <div data-testid="fill-wrapper" className="h-80 w-full">
        <Story />
      </div>
    ),
  ],
  play: async ({ canvasElement, step }) => {
    await step("Chart canvas fills the container width", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      // The plot is created after the first ResizeObserver measurement, so wait
      // for it before asserting it sized to the container (not a fixed 1000px).
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot).toBeInTheDocument();
        expect(plot.clientWidth).toBeGreaterThanOrEqual(wrapper.clientWidth - 2);
      });
    });

    await step("Chart resizes in place when the container resizes", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      // Shrink the container; the ResizeObserver should drive a Plotly relayout
      // (not a full re-plot) so the canvas tracks the new width.
      wrapper.style.width = "440px";
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot.clientWidth).toBeGreaterThanOrEqual(420);
        expect(plot.clientWidth).toBeLessThanOrEqual(460);
      });
    });
  },
};

const regressionDataSeries = [
  { name: "Run 1", x: [0, 1, 2, 3, 4, 5], y: [10, 18, 14, 22, 19, 25] },
  { name: "Run 2", x: [0, 1, 2, 3, 4, 5], y: [8, 12, 17, 15, 21, 23] },
  { name: "Run 3", x: [0, 1, 2, 3, 4, 5], y: [13, 15, 12, 19, 17, 22] },
];

export const SmallSizeLegendRegression: Story = {
  name: "Small Size — Legend vs Ticks",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5468" },
    docs: {
      description: {
        story:
          "At a small size (310×200) with a bottom legend and `xTickText`, the legend sits below the x-axis tick labels and title rather than overlapping them.",
      },
    },
  },
  args: {
    dataSeries: regressionDataSeries,
    xTickText: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    xTitle: "Month",
    yTitle: "Value",
    width: 310,
    height: 200,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    await step("Chart container renders", async () => {
      await waitFor(() =>
        expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument(),
      );
    });

    await step("Legend sits below the x-axis tick labels (no overlap)", async () => {
      await waitFor(() => {
        const ticks = [
          ...canvasElement.querySelectorAll<SVGTextElement>(".xtick text"),
        ];
        const legendItems = [
          ...canvasElement.querySelectorAll<SVGTextElement>(".legend .legendtext"),
        ];
        expect(ticks.length).toBeGreaterThan(0);
        expect(legendItems.length).toBeGreaterThan(0);

        const tickBottom = Math.max(
          ...ticks.map((node) => node.getBoundingClientRect().bottom),
        );
        const legendTop = Math.min(
          ...legendItems.map((node) => node.getBoundingClientRect().top),
        );
        // Legend must start at or below where the tick labels end (small
        // sub-pixel tolerance for rounding).
        expect(legendTop).toBeGreaterThanOrEqual(tickBottom - 2);
      });
    });
  },
};

export const NoTitle: Story = {
  name: "No Title",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5461" },
  },
  args: {
    dataSeries: sampleDataSeries,
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("No title block is rendered", async () => {
      expect(canvasElement.querySelector(".gtitle")).not.toBeInTheDocument();
      expect(canvas.queryByText("Area Graph")).not.toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });
  },
};
