import { expect, waitFor, within } from "storybook/test";

import { AreaGraph } from "./AreaGraph";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof AreaGraph> = {
  title: "Charts/Area Graph",
  component: AreaGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["normal", "stacked"],
    },
    width: {
      control: { type: "number" },
    },
    height: {
      control: { type: "number" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

const sampleDataSeries = [
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [120, 130, 100, 110, 140, 160, 150, 140, 110],
    name: "Series 1",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [30, 40, 50, 60, 70, 50, 40, 30, 20],
    name: "Series 2",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [20, 30, 25, 35, 40, 30, 25, 20, 15],
    name: "Series 3",
  },
];

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T963" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });
  },
};

export const Stacked: Story = {
  name: "Stacked",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T964" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Stacked Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "stacked",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });

    await step("Tooltip shows the series value, not the stacked sum", async () => {
      type EmittingPlot = HTMLElement & {
        emit: (event: string, data?: unknown) => void;
      };
      const plot = canvasElement.querySelector(".js-plotly-plot") as EmittingPlot;
      // Series 2 at x=600: own value 70, stacked y = 140 + 70 = 210
      plot.emit("plotly_hover", {
        points: [{ x: 600, y: 210, customdata: 70, data: { name: "Series 2" } }],
        event: new MouseEvent("mousemove", { clientX: 300, clientY: 200 }),
      });
      await waitFor(() => {
        const tip = document.querySelector('[data-slot="tooltip-content"]');
        expect(tip).toBeInTheDocument();
        expect(tip).toHaveTextContent("Rows: 70");
        expect(tip).not.toHaveTextContent("Rows: 210");
      });
      plot.emit("plotly_unhover");
    });
  },
};

const weekdayDataSeries = [
  {
    // x positions are integer indices; xTickText supplies the day labels
    x: [0, 1, 2, 3, 4, 5, 6],
    y: [120, 130, 100, 110, 140, 80, 60],
    name: "Throughput",
  },
];

export const CategoricalXLabels: Story = {
  name: "Categorical X Labels",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
    docs: {
      description: {
        story:
          "Use `xTickText` to display categorical x-axis labels (e.g. days of the week). The numeric `x` values still drive area positioning, but the rendered tick labels match `xTickText` in order.",
      },
    },
  },
  args: {
    dataSeries: weekdayDataSeries,
    xTickText: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    title: "Throughput by Weekday",
    xTitle: "Day",
    yTitle: "Files",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Throughput by Weekday")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("X-axis ticks show categorical labels, not integers", async () => {
      const tickLabels = [
        ...canvasElement.querySelectorAll(".xtick text"),
      ].map((node) => node.textContent);
      expect(tickLabels).toEqual([
        "Mon",
        "Tue",
        "Wed",
        "Thu",
        "Fri",
        "Sat",
        "Sun",
      ]);
    });
  },
};

export const CustomRange: Story = {
  name: "Custom Range",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T965" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph with Custom Range",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
    xRange: [300, 900],
    yRange: [0, 200],
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph with Custom Range")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });
  },
};
