import { expect, waitFor, within } from "storybook/test";

import { AreaGraph } from "./AreaGraph";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof AreaGraph> = {
  title: "Charts/Area Graph",
  component: AreaGraph,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["normal", "stacked"],
    },
    width: {
      control: { type: "number" },
    },
    height: {
      control: { type: "number" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof meta>;

const sampleDataSeries = [
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [120, 130, 100, 110, 140, 160, 150, 140, 110],
    name: "Series 1",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [30, 40, 50, 60, 70, 50, 40, 30, 20],
    name: "Series 2",
  },
  {
    x: [200, 300, 400, 500, 600, 700, 800, 900, 1000],
    y: [20, 30, 25, 35, 40, 30, 25, 20, 15],
    name: "Series 3",
  },
];

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T963" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });
  },
};

export const Stacked: Story = {
  name: "Stacked",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T964" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Stacked Area Graph",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "stacked",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Area Graph")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });

    await step("Tooltip shows the series value, not the stacked sum", async () => {
      type EmittingPlot = HTMLElement & {
        emit: (event: string, data?: unknown) => void;
      };
      const plot = canvasElement.querySelector(".js-plotly-plot") as EmittingPlot;
      // Series 2 at x=600: own value 70, stacked y = 140 + 70 = 210
      plot.emit("plotly_hover", {
        points: [{ x: 600, y: 210, customdata: 70, data: { name: "Series 2" } }],
        event: new MouseEvent("mousemove", { clientX: 300, clientY: 200 }),
      });
      await waitFor(() => {
        const tip = document.querySelector('[data-slot="tooltip-content"]');
        expect(tip).toBeInTheDocument();
        expect(tip).toHaveTextContent("Rows: 70");
        expect(tip).not.toHaveTextContent("Rows: 210");
      });
      plot.emit("plotly_unhover");
    });
  },
};

export const CompactDashboardTile: Story = {
  name: "Compact (Dashboard Tile)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Yield",
    xTitle: "Run",
    yTitle: "g/L",
    width: 600,
    height: 260,
    variant: "normal",
    density: "compact",
  },
  render: (args) => (
    <div
      style={{
        width: 600,
        height: 260,
        border: "1px solid var(--border, #e2e8f0)",
        borderRadius: 8,
        overflow: "hidden",
      }}
    >
      <AreaGraph {...args} />
    </div>
  ),
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Compact title is displayed", async () => {
      expect(canvas.getByText("Yield")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Plot area fills more than 65% of the 600×260 tile", async () => {
      const drag = canvasElement.querySelector(".nsewdrag");
      expect(drag).toBeTruthy();
      const w = parseFloat(drag?.getAttribute("width") ?? "0");
      const h = parseFloat(drag?.getAttribute("height") ?? "0");
      expect((w * h) / (600 * 260)).toBeGreaterThan(0.65);
    });
  },
};

export const CustomRange: Story = {
  name: "Custom Range",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T965" },
  },
  args: {
    dataSeries: sampleDataSeries,
    title: "Area Graph with Custom Range",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "normal",
    xRange: [300, 900],
    yRange: [0, 200],
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Area Graph with Custom Range")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Series 1")).toBeInTheDocument();
      expect(canvas.getByText("Series 2")).toBeInTheDocument();
      expect(canvas.getByText("Series 3")).toBeInTheDocument();
    });
  },
};
