import React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import ProtocolConfiguration from "./ProtocolConfiguration";

const meta: Meta<typeof ProtocolConfiguration> = {
  title: "Molecules/ProtocolConfiguration",
  component: ProtocolConfiguration,
  parameters: {
    layout: "padded",
  },
  tags: ["autodocs"],
  argTypes: {
    className: {
      control: { type: "text" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof ProtocolConfiguration>;

// Basic examples
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T927" },
  },
  args: {},
};

export const WithCustomClassName: Story = {
  name: "With Custom Class Name",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T928" },
  },
  args: {
    className: "custom-protocol-config",
  },
};

// Interactive example showing both states
export const Interactive: Story = {
  name: "Interactive",
  args: {},
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T929" },
    docs: {
      description: {
        story: "Toggle the Edit Mode switch to see the different states of the component.",
      },
    },
  },
};

// Container example to show how it looks in a layout
export const InContainer: Story = {
  name: "In Container",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T930" },
  },
  args: {},
  decorators: [
    (Story) => (
      <div style={{ maxWidth: "800px", margin: "0 auto", padding: "20px" }}>
        <Story />
      </div>
    ),
  ],
};
