import React, { useState } from "react";

import MenuItem from "./MenuItem";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof MenuItem> = {
  title: "Atoms/MenuItem",
  component: MenuItem,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof MenuItem>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T813" },
  },
  args: {
    label: "Menu Item",
    showCheckbox: false,
    active: false,
  },
};

export const WithCheckbox: Story = {
  name: "With Checkbox",
  args: {
    label: "Menu Item with Checkbox",
    showCheckbox: true,
    checked: false,
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T814" },
    docs: {
      description: {
        story: "When showCheckbox is true, the label is displayed as part of the Checkbox component.",
      },
    },
  },
};

export const WithCheckboxChecked: Story = {
  name: "With Checkbox Checked",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T815" },
  },
  args: {
    label: "Checked Menu Item",
    showCheckbox: true,
    checked: true,
  },
};

export const Active: Story = {
  name: "Active",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T816" },
  },
  args: {
    label: "Active Menu Item",
    active: true,
  },
};

export const ActiveWithCheckbox: Story = {
  name: "Active With Checkbox",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T817" },
  },
  args: {
    label: "Active Checked Menu Item",
    showCheckbox: true,
    checked: true,
    active: true,
  },
};

export const ComparisonWithAndWithoutCheckbox: Story = {
  name: "Comparison With And Without Checkbox",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T818" },
  },
  render: () => {
    return (
      <div style={{ width: "300px", border: "1px solid #eee", borderRadius: "8px", overflow: "hidden" }}>
        <MenuItem label="Regular MenuItem (without checkbox)" />
        <MenuItem label="MenuItem with Checkbox" showCheckbox={true} checked={false} />
      </div>
    );
  },
};

const InteractiveDemo = () => {
  const [activeItem, setActiveItem] = useState<string | null>(null);
  const [checked, setChecked] = useState<Record<string, boolean>>({
    item1: false,
    item2: true,
    item3: false,
  });

  const handleClick = (itemId: string) => {
    setActiveItem(itemId);
  };

  const handleCheckChange = (itemId: string, isChecked: boolean) => {
    setChecked((prev) => ({
      ...prev,
      [itemId]: isChecked,
    }));
  };

  return (
    <div style={{ width: "300px", border: "1px solid #eee", borderRadius: "8px", overflow: "hidden" }}>
      <MenuItem
        label="Menu Item 1"
        active={activeItem === "item1"}
        onClick={() => handleClick("item1")}
        showCheckbox={true}
        checked={checked.item1}
        onCheckChange={(isChecked) => handleCheckChange("item1", isChecked)}
      />
      <MenuItem
        label="Menu Item 2"
        active={activeItem === "item2"}
        onClick={() => handleClick("item2")}
        showCheckbox={true}
        checked={checked.item2}
        onCheckChange={(isChecked) => handleCheckChange("item2", isChecked)}
      />
      <MenuItem
        label="Menu Item 3"
        active={activeItem === "item3"}
        onClick={() => handleClick("item3")}
        showCheckbox={true}
        checked={checked.item3}
        onCheckChange={(isChecked) => handleCheckChange("item3", isChecked)}
      />
    </div>
  );
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T819" },
  },
  render: () => <InteractiveDemo />,
};
