import { Meta, StoryObj } from "@storybook/react-vite";
import { Icon, IconName } from "@atoms/Icon";
import { Input } from "@atoms/Input";

const meta: Meta<typeof Input> = {
  title: "Atoms/Input",
  component: Input,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    size: {
      control: { type: "select" },
      options: ["xsmall", "small"],
    },
    error: {
      control: { type: "boolean" },
    },
    disabled: {
      control: { type: "boolean" },
    },
  },
};

export default meta;
type Story = StoryObj<typeof Input>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T799" },
  },
  args: {
    placeholder: "Placeholder",
  },
};

export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T800" },
  },
  args: {
    placeholder: "Placeholder",
    size: "small",
  },
};

export const XSmall: Story = {
  name: "X Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T801" },
  },
  args: {
    placeholder: "Placeholder",
    size: "xsmall",
  },
};

export const WithLeftIcon: Story = {
  name: "With Left Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T802" },
  },
  args: {
    placeholder: "Placeholder",
    iconLeft: <Icon name={IconName.SEARCH} />,
  },
};

export const WithRightIcon: Story = {
  name: "With Right Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T803" },
  },
  args: {
    placeholder: "Placeholder",
    iconRight: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

export const WithBothIcons: Story = {
  name: "With Both Icons",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T804" },
  },
  args: {
    placeholder: "Placeholder",
    iconLeft: <Icon name={IconName.SEARCH} />,
    iconRight: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

export const Error: Story = {
  name: "Error",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T805" },
  },
  args: {
    placeholder: "Placeholder",
    error: true,
  },
};

export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T806" },
  },
  args: {
    placeholder: "Placeholder",
    disabled: true,
  },
};

export const AllVariations: Story = {
  name: "All Variations",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T807" },
  },
  render: () => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "16px",
        maxWidth: "300px",
      }}
    >
      <Input placeholder="Default" />
      <Input placeholder="Small" size="small" />
      <Input placeholder="XSmall" size="xsmall" />
      <Input placeholder="With left icon" iconLeft={<Icon name={IconName.SEARCH} />} />
      <Input placeholder="With right icon" iconRight={<Icon name={IconName.CHEVRON_DOWN} />} />
      <Input
        placeholder="With both icons"
        iconLeft={<Icon name={IconName.SEARCH} />}
        iconRight={<Icon name={IconName.CHEVRON_DOWN} />}
      />
      <Input placeholder="Error state" error />
      <Input placeholder="Disabled state" disabled />
    </div>
  ),
};
