import { Meta, StoryObj } from "@storybook/react-vite";
import CardSidebar from "./CardSidebar";

const meta: Meta<typeof CardSidebar> = {
  title: "Molecules/CardSidebar",
  component: CardSidebar,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    status: {
      control: "select",
      options: ["default", "active", "hover", "disabled"],
    },
    onButtonClick: { action: "button clicked" },
    onLinkClick: { action: "link clicked" },
  },
};

export default meta;
type Story = StoryObj<typeof CardSidebar>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T880" },
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button",
    linkText: "Link",
    status: "default",
  },
};

export const WithoutButton: Story = {
  name: "Without Button",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T881" },
  },
  args: {
    title: "Title",
    description: "Description",
    linkText: "Link",
    status: "default",
  },
};

export const WithoutLink: Story = {
  name: "Without Link",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T882" },
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button",
    status: "default",
  },
};

export const Active: Story = {
  name: "Active",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T883" },
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button",
    linkText: "Link",
    status: "active",
  },
};

export const Hover: Story = {
  name: "Hover",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T884" },
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button",
    linkText: "Link",
    status: "hover",
  },
};

export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T885" },
  },
  args: {
    title: "Title",
    description: "Description",
    buttonText: "Button",
    linkText: "Link",
    status: "disabled",
  },
};

export const WithoutDescription: Story = {
  name: "Without Description",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T886" },
  },
  args: {
    title: "Title",
    buttonText: "Button",
    linkText: "Link",
  },
};

export const LinkOnly: Story = {
  name: "Link Only",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T887" },
  },
  args: {
    title: "Title",
    description: "Description with link only, no button",
    linkText: "Link",
  },
};

export const ButtonOnly: Story = {
  name: "Button Only",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T888" },
  },
  args: {
    title: "Title",
    description: "Description with button only, no link",
    buttonText: "Button",
  },
};

export const TitleOnly: Story = {
  name: "Title Only",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T889" },
  },
  args: {
    title: "Title Only",
    description: "No actions available on this card",
  },
};

export const CustomText: Story = {
  name: "Custom Text",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T890" },
  },
  args: {
    title: "Custom Title",
    description: "This is a custom description that explains what this card does.",
    buttonText: "Action",
    linkText: "Learn more",
  },
};

export const AllVariants: Story = {
  name: "All Variants",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T891" },
  },
  render: () => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "24px",
        width: "400px",
      }}
    >
      <CardSidebar title="Title" description="Description" buttonText="Button" linkText="Link" status="default" />
      <CardSidebar title="Title" description="Description" buttonText="Button" linkText="Link" status="active" />
      <CardSidebar title="Title" description="Description" buttonText="Button" linkText="Link" status="hover" />
      <CardSidebar title="Title" description="Description" buttonText="Button" linkText="Link" status="disabled" />
    </div>
  ),
};

export const ActionVariations: Story = {
  name: "Action Variations",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T892" },
  },
  render: () => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "24px",
        width: "400px",
      }}
    >
      <CardSidebar
        title="With Both"
        description="This card has both button and link"
        buttonText="Button"
        linkText="Link"
      />
      <CardSidebar title="Button Only" description="This card has only a button" buttonText="Button" />
      <CardSidebar title="Link Only" description="This card has only a link" linkText="Link" />
      <CardSidebar title="No Actions" description="This card has no button or link" />
    </div>
  ),
};

export const WithoutButtonAndLink: Story = {
  name: "Without Button And Link",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T893" },
  },
  args: {
    title: "Title",
    description: "Description with no button and no link",
    status: "default",
  },
};
