import { useState } from "react";
import { expect, within } from "storybook/test";

import AssistantModal from "./AssistantModal";

import { Button } from "@/components/ui/button";


export default {
  title: "Patterns/AssistantModal",
  component: AssistantModal,
};

export const Default = () => {
  const [open, setOpen] = useState(false);
  const [lastCode, setLastCode] = useState("");
  const [lastInput, setLastInput] = useState("");

  return (
    <div>
      <Button onClick={() => setOpen(true)}>Open Assistant Modal</Button>
      <AssistantModal
        open={open}
        onOpenChange={setOpen}
        title="Tetrascience Assistant"
        prompt="Here you may ask questions about task scripts, protocols, and pipelines."
        initialCode={lastCode || "Description\n"}
        userQuery={`Please generate an example protocol v3 yaml for Tecan D300e and PerkinElmer EnVision to Dotmatics`}
        onCopy={(code) => {
          setLastCode(code);
          alert("Copied code: " + code);
        }}
        onLaunch={(code) => {
          alert("Launch with code: " + code);
        }}
        onSend={(input) => {
          setLastInput(input);
          alert("Sent input: " + input);
        }}
      />
      {lastCode && (
        <div style={{ marginTop: 16 }}>
          <strong>Last Code:</strong>
          <pre style={{ background: "#f5f5f5", padding: 8, borderRadius: 4 }}>{lastCode}</pre>
        </div>
      )}
      {lastInput && (
        <div style={{ marginTop: 8 }}>
          <strong>Last Input:</strong> {lastInput}
        </div>
      )}
    </div>
  );
};
Default.storyName = "Default";
Default.parameters = {
  layout: "centered",
  // Auto-generated by sync-storybook-zephyr - do not add manually
  zephyr: { testCaseId: "SW-T874" },
};
Default.play = async ({ canvasElement, step }) => {
  const canvas = within(canvasElement);

  await step("Open trigger button renders", async () => {
    expect(canvas.getByRole("button", { name: "Open Assistant Modal" })).toBeInTheDocument();
  });
};
