
import { ThemeProvider } from "../../../theme";

import Card from "./Card";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Card> = {
  title: "Atoms/Card",
  component: Card,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    size: {
      control: "select",
      options: ["small", "medium", "large"],
    },
    variant: {
      control: "select",
      options: ["default", "outlined", "elevated"],
    },
    fullWidth: {
      control: "boolean",
    },
  },
};

export default meta;
type Story = StoryObj<typeof Card>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T751" },
  },
  args: {
    children: "Card content",
    title: "Card Title",
    size: "medium",
    variant: "default",
  },
};

export const Outlined: Story = {
  name: "Outlined",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T752" },
  },
  args: {
    children: "Card content with outlined variant",
    title: "Outlined Card",
    size: "medium",
    variant: "outlined",
  },
};

export const Elevated: Story = {
  name: "Elevated",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T753" },
  },
  args: {
    children: "Card content with elevated variant",
    title: "Elevated Card",
    size: "medium",
    variant: "elevated",
  },
};

export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T754" },
  },
  args: {
    children: "Small card content",
    title: "Small Card",
    size: "small",
    variant: "default",
  },
};

export const Large: Story = {
  name: "Large",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T755" },
  },
  args: {
    children: "Large card content",
    title: "Large Card",
    size: "large",
    variant: "default",
  },
};

export const NoTitle: Story = {
  name: "No Title",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T756" },
  },
  args: {
    children: "Card with no title",
    size: "medium",
    variant: "default",
  },
};

export const FullWidth: Story = {
  name: "Full Width",
  args: {
    children: "This card will take full width of its container",
    title: "Full Width Card",
    size: "medium",
    variant: "default",
    fullWidth: true,
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T757" },
    layout: "padded",
  },
};

export const AllVariants: Story = {
  name: "All Variants",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T758" },
  },
  render: () => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "24px",
        width: "400px",
      }}
    >
      <Card title="Default Card" variant="default">
        Default variant content
      </Card>
      <Card title="Outlined Card" variant="outlined">
        Outlined variant content
      </Card>
      <Card title="Elevated Card" variant="elevated">
        Elevated variant content
      </Card>
    </div>
  ),
};

export const AllSizes: Story = {
  name: "All Sizes",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T759" },
  },
  render: () => (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "24px",
        width: "400px",
      }}
    >
      <Card title="Small Card" size="small">
        Small size content
      </Card>
      <Card title="Medium Card" size="medium">
        Medium size content
      </Card>
      <Card title="Large Card" size="large">
        Large size content
      </Card>
    </div>
  ),
};

// Theme examples
export const WithCustomBorder: Story = {
  name: "With Custom Border",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T760" },
  },
  args: {
    children: "Card with custom border color",
    title: "Custom Border Card",
    variant: "outlined",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            cardBorder: "#DC2626",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithCustomBackground: Story = {
  name: "With Custom Background",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T761" },
  },
  args: {
    children: "Card with custom background",
    title: "Custom Background Card",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            cardBackground: "#FEF3C7",
            cardBorder: "#F59E0B",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithSharpCorners: Story = {
  name: "With Sharp Corners",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T762" },
  },
  args: {
    children: "Card with sharp corners",
    title: "Sharp Corners Card",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          radius: {
            large: "4px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithFullTheme: Story = {
  name: "With Full Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T763" },
  },
  args: {
    children: "Fully themed card with purple background and rounded corners",
    title: "Themed Card",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            cardBackground: "#F3E8FF",
            cardBorder: "#9333EA",
          },
          radius: {
            large: "24px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};
