import Textarea from "./Textarea";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Textarea> = {
  title: "Atoms/Textarea",
  component: Textarea,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Textarea>;

// Default textarea
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T852" },
  },
  args: {
    placeholder: "Enter text here...",
  },
};

// XSmall size
export const XSmall: Story = {
  name: "X Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T853" },
  },
  args: {
    placeholder: "Enter text here...",
    size: "xsmall",
  },
};

// Small size
export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T854" },
  },
  args: {
    placeholder: "Enter text here...",
    size: "small",
  },
};

// Disabled state
export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T855" },
  },
  args: {
    placeholder: "This textarea is disabled",
    disabled: true,
  },
};

// Error state
export const Error: Story = {
  name: "Error",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T856" },
  },
  args: {
    placeholder: "Enter text here...",
    error: true,
  },
};

// With value
export const WithValue: Story = {
  name: "With Value",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T857" },
  },
  args: {
    defaultValue:
      "This is a textarea with some initial value that shows how the text would look when filled in by the user.",
    rows: 5,
  },
};

// Full width
export const FullWidth: Story = {
  name: "Full Width",
  args: {
    placeholder: "Full width textarea",
    fullWidth: true,
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T858" },
    layout: "padded",
  },
};
