import { Icon, IconName } from "@atoms/Icon";
import { expect, fn, userEvent, within } from "storybook/test";

import { ThemeProvider } from "../../../theme";

import { Button } from "./Button";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Button> = {
  title: "Atoms/Button",
  component: Button,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["primary", "secondary", "tertiary"],
    },
    size: {
      control: { type: "select" },
      options: ["small", "medium"],
    },
  },
};

export default meta;
type Story = StoryObj<typeof Button>;

/**
 * Helper function to convert hex color to RGB format for comparison
 * Browser computed styles return RGB format, not hex
 */
function hexToRgb(hex: string): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return hex;
  const r = parseInt(result[1], 16);
  const g = parseInt(result[2], 16);
  const b = parseInt(result[3], 16);
  return `rgb(${r}, ${g}, ${b})`;
}

// Basic examples
export const Primary: Story = {
  name: "Primary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T727" },
  },
  args: {
    children: "Primary Button",
    variant: "primary",
  },
};

export const Secondary: Story = {
  name: "Secondary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T728" },
  },
  args: {
    children: "Secondary Button",
    variant: "secondary",
  },
};

export const Tertiary: Story = {
  name: "Tertiary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T729" },
  },
  args: {
    children: "Tertiary Button",
    variant: "tertiary",
  },
};

// Size examples
export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T730" },
  },
  args: {
    children: "Small Button",
    size: "small",
  },
};

export const Medium: Story = {
  name: "Medium",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T731" },
  },
  args: {
    children: "Medium Button",
    size: "medium",
  },
};

// State examples
export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T732" },
  },
  args: {
    children: "Disabled Button",
    disabled: true,
  },
};

export const Loading: Story = {
  name: "Loading",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T733" },
  },
  args: {
    children: "Loading Button",
    loading: true,
  },
};

// With icons
export const WithLeftIcon: Story = {
  name: "With Left Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T734" },
  },
  args: {
    children: "Search",
    leftIcon: <Icon name={IconName.SEARCH} />,
  },
};

export const WithRightIcon: Story = {
  name: "With Right Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T735" },
  },
  args: {
    children: "Next",
    rightIcon: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

export const WithBothIcons: Story = {
  name: "With Both Icons",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T736" },
  },
  args: {
    children: "Search and Continue",
    leftIcon: <Icon name={IconName.SEARCH} />,
    rightIcon: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

// Icon only button
export const IconOnly: Story = {
  name: "Icon Only",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T737" },
  },
  args: {
    leftIcon: <Icon name={IconName.SEARCH} />,
    "aria-label": "Search",
  },
};

export const FullWidth: Story = {
  name: "Full Width",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T738" },
  },
  args: {
    children: "Full Width Button",
    fullWidth: true,
  },
};

// Theme examples
export const WithRedTheme: Story = {
  name: "With Red Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T739" },
  },
  args: {
    children: "Red Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#DC2626",
            primaryHover: "#B91C1C",
            primaryActive: "#991B1B",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithPurpleTheme: Story = {
  name: "With Purple Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T740" },
  },
  args: {
    children: "Purple Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#9333EA",
            primaryHover: "#7E22CE",
            primaryActive: "#6B21A8",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithCustomRadius: Story = {
  name: "With Custom Radius",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T741" },
  },
  args: {
    children: "Sharp Corners Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          radius: {
            medium: "4px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithFullCustomTheme: Story = {
  name: "With Full Custom Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T742" },
  },
  args: {
    children: "Fully Custom Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#F59E0B",
            primaryHover: "#D97706",
            primaryActive: "#B45309",
          },
          radius: {
            medium: "20px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

// ============================================================================
// Interactive Test Stories
// These stories have play functions for automated testing
// They are hidden from the Storybook UI with tags: ["!dev"]
// ============================================================================

export const ClickInteraction: Story = {
  name: "Click Interaction",
  tags: ["!dev"],
  parameters: {
    zephyr: { testCaseId: "SW-T743" },
  },
  args: {
    children: "Click Me",
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /click me/i });

    await expect(button).toBeInTheDocument();
    await userEvent.click(button);
    await expect(args.onClick).toHaveBeenCalledTimes(1);
  },
};

export const DisabledButtonInteraction: Story = {
  name: "Disabled Button Interaction",
  tags: ["!dev"],
  parameters: {
    zephyr: { testCaseId: "SW-T744" },
  },
  args: {
    children: "Disabled Button",
    disabled: true,
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /disabled button/i });

    await expect(button).toBeDisabled();
    await userEvent.click(button).catch(() => {
      // Expected to fail on disabled button
    });
    await expect(args.onClick).not.toHaveBeenCalled();
  },
};

export const HoverInteraction: Story = {
  name: "Hover Interaction",
  tags: ["!dev"],
  parameters: {
    zephyr: { testCaseId: "SW-T745" },
  },
  args: {
    children: "Hover Over Me",
    variant: "primary",
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /hover over me/i });

    await expect(button).toBeInTheDocument();
    await userEvent.hover(button);
    await expect(button).toBeVisible();
    await userEvent.unhover(button);
  },
};

export const KeyboardInteraction: Story = {
  name: "Keyboard Interaction",
  tags: ["!dev"],
  parameters: {
    zephyr: { testCaseId: "SW-T746" },
  },
  args: {
    children: "Press Enter",
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /press enter/i });

    await userEvent.tab();
    await expect(button).toHaveFocus();
    await userEvent.keyboard("{Enter}");
    await expect(args.onClick).toHaveBeenCalledTimes(1);
  },
};

export const RedThemeVerification: Story = {
  name: "Red Theme Color Verification",
  tags: ["!dev"],
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1048" },
  },
  args: {
    children: "Red Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#DC2626",
            primaryHover: "#B91C1C",
            primaryActive: "#991B1B",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /red theme button/i });

    await expect(button).toBeInTheDocument();
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;
    const expectedColor = hexToRgb("#DC2626");
    await expect(backgroundColor).toBe(expectedColor);
  },
};

export const PurpleThemeVerification: Story = {
  name: "Purple Theme Color Verification",
  tags: ["!dev"],
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1049" },
  },
  args: {
    children: "Purple Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#9333EA",
            primaryHover: "#7E22CE",
            primaryActive: "#6B21A8",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /purple theme button/i });

    await expect(button).toBeInTheDocument();
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;
    const expectedColor = hexToRgb("#9333EA");
    await expect(backgroundColor).toBe(expectedColor);
  },
};

export const OrangeThemeVerification: Story = {
  name: "Orange Theme Color Verification",
  tags: ["!dev"],
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1050" },
  },
  args: {
    children: "Orange Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#F59E0B",
            primaryHover: "#D97706",
            primaryActive: "#B45309",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /orange theme button/i });

    await expect(button).toBeInTheDocument();
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;
    const expectedColor = hexToRgb("#F59E0B");
    await expect(backgroundColor).toBe(expectedColor);
  },
};
