import type { Meta, StoryObj } from "@storybook/react-vite";
import { expect, fn, userEvent, within } from "storybook/test";

import { Button } from "./Button";
import { ThemeProvider } from "../../../theme";

/**
 * Interactive test stories for the Button component.
 * These are excluded from the Storybook UI but run as part of the test suite.
 */
const meta: Meta<typeof Button> = {
  title: "Tests/Atoms/Button",
  component: Button,
  tags: ["!dev"],
  parameters: {
    layout: "centered",
  },
};

export default meta;
type Story = StoryObj<typeof Button>;

export const ClickInteraction: Story = {
  name: "Click Interaction",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T743" },
  },
  args: {
    children: "Click Me",
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);

    // Find the button by its text
    const button = canvas.getByRole("button", { name: /click me/i });

    // Verify button is rendered
    await expect(button).toBeInTheDocument();

    // Click the button
    await userEvent.click(button);

    // Verify the onClick handler was called
    await expect(args.onClick).toHaveBeenCalledTimes(1);
  },
};

export const DisabledButtonInteraction: Story = {
  name: "Disabled Button Interaction",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T744" },
  },
  args: {
    children: "Disabled Button",
    disabled: true,
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);

    const button = canvas.getByRole("button", { name: /disabled button/i });

    // Verify button is disabled
    await expect(button).toBeDisabled();

    // Attempt to click - should not trigger onClick
    // Note: userEvent.click respects disabled state and won't fire events
    await userEvent.click(button).catch(() => {
      // Expected to fail on disabled button
    });

    // Verify onClick was NOT called
    await expect(args.onClick).not.toHaveBeenCalled();
  },
};

export const HoverInteraction: Story = {
  name: "Hover Interaction",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T745" },
  },
  args: {
    children: "Hover Over Me",
    variant: "primary",
  },
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);

    const button = canvas.getByRole("button", { name: /hover over me/i });

    // Verify initial state
    await expect(button).toBeInTheDocument();

    // Hover over the button
    await userEvent.hover(button);

    // Button should still be visible after hover
    await expect(button).toBeVisible();

    // Unhover
    await userEvent.unhover(button);
  },
};

export const KeyboardInteraction: Story = {
  name: "Keyboard Interaction",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T746" },
  },
  args: {
    children: "Press Enter",
    onClick: fn(),
  },
  play: async ({ canvasElement, args }) => {
    const canvas = within(canvasElement);

    const button = canvas.getByRole("button", { name: /press enter/i });

    // Focus the button using tab
    await userEvent.tab();

    // Verify button has focus
    await expect(button).toHaveFocus();

    // Press Enter to activate the button
    await userEvent.keyboard("{Enter}");

    // Verify onClick was called
    await expect(args.onClick).toHaveBeenCalledTimes(1);
  },
};

/**
 * Helper function to convert hex color to RGB format for comparison
 * Browser computed styles return RGB format, not hex
 */
function hexToRgb(hex: string): string {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return hex;
  const r = parseInt(result[1], 16);
  const g = parseInt(result[2], 16);
  const b = parseInt(result[3], 16);
  return `rgb(${r}, ${g}, ${b})`;
}

// Theme verification tests - these ensure the ThemeProvider correctly scopes CSS variables
export const RedThemeVerification: Story = {
  name: "[SW-T1048] Red Theme Color Verification",
  args: {
    children: "Red Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#DC2626",
            primaryHover: "#B91C1C",
            primaryActive: "#991B1B",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /red theme button/i });

    // Verify button is rendered
    await expect(button).toBeInTheDocument();

    // Get computed background color
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;

    // Verify the button has the correct red theme color (#DC2626 = rgb(220, 38, 38))
    const expectedColor = hexToRgb("#DC2626");
    await expect(backgroundColor).toBe(expectedColor);
  },
};

export const PurpleThemeVerification: Story = {
  name: "[SW-T1049] Purple Theme Color Verification",
  args: {
    children: "Purple Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#9333EA",
            primaryHover: "#7E22CE",
            primaryActive: "#6B21A8",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /purple theme button/i });

    // Verify button is rendered
    await expect(button).toBeInTheDocument();

    // Get computed background color
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;

    // Verify the button has the correct purple theme color (#9333EA = rgb(147, 51, 234))
    const expectedColor = hexToRgb("#9333EA");
    await expect(backgroundColor).toBe(expectedColor);
  },
};

export const OrangeThemeVerification: Story = {
  name: "[SW-T1050] Orange Theme Color Verification",
  args: {
    children: "Orange Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#F59E0B",
            primaryHover: "#D97706",
            primaryActive: "#B45309",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole("button", { name: /orange theme button/i });

    // Verify button is rendered
    await expect(button).toBeInTheDocument();

    // Get computed background color
    const computedStyle = window.getComputedStyle(button);
    const backgroundColor = computedStyle.backgroundColor;

    // Verify the button has the correct orange theme color (#F59E0B = rgb(245, 158, 11))
    const expectedColor = hexToRgb("#F59E0B");
    await expect(backgroundColor).toBe(expectedColor);
  },
};
