import { Icon, IconName } from "@atoms/Icon";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { ThemeProvider } from "../../../theme";

import { Button } from "./Button";

const meta: Meta<typeof Button> = {
  title: "Atoms/Button",
  component: Button,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["primary", "secondary", "tertiary"],
    },
    size: {
      control: { type: "select" },
      options: ["small", "medium"],
    },
  },
};

export default meta;
type Story = StoryObj<typeof Button>;

// Basic examples
export const Primary: Story = {
  name: "Primary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T727" },
  },
  args: {
    children: "Primary Button",
    variant: "primary",
  },
};

export const Secondary: Story = {
  name: "Secondary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T728" },
  },
  args: {
    children: "Secondary Button",
    variant: "secondary",
  },
};

export const Tertiary: Story = {
  name: "Tertiary",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T729" },
  },
  args: {
    children: "Tertiary Button",
    variant: "tertiary",
  },
};

// Size examples
export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T730" },
  },
  args: {
    children: "Small Button",
    size: "small",
  },
};

export const Medium: Story = {
  name: "Medium",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T731" },
  },
  args: {
    children: "Medium Button",
    size: "medium",
  },
};

// State examples
export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T732" },
  },
  args: {
    children: "Disabled Button",
    disabled: true,
  },
};

export const Loading: Story = {
  name: "Loading",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T733" },
  },
  args: {
    children: "Loading Button",
    loading: true,
  },
};

// With icons
export const WithLeftIcon: Story = {
  name: "With Left Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T734" },
  },
  args: {
    children: "Search",
    leftIcon: <Icon name={IconName.SEARCH} />,
  },
};

export const WithRightIcon: Story = {
  name: "With Right Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T735" },
  },
  args: {
    children: "Next",
    rightIcon: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

export const WithBothIcons: Story = {
  name: "With Both Icons",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T736" },
  },
  args: {
    children: "Search and Continue",
    leftIcon: <Icon name={IconName.SEARCH} />,
    rightIcon: <Icon name={IconName.CHEVRON_DOWN} />,
  },
};

// Icon only button
export const IconOnly: Story = {
  name: "Icon Only",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T737" },
  },
  args: {
    leftIcon: <Icon name={IconName.SEARCH} />,
    "aria-label": "Search",
  },
};

export const FullWidth: Story = {
  name: "Full Width",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T738" },
  },
  args: {
    children: "Full Width Button",
    fullWidth: true,
  },
};

// Theme examples
export const WithRedTheme: Story = {
  name: "With Red Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T739" },
  },
  args: {
    children: "Red Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#DC2626",
            primaryHover: "#B91C1C",
            primaryActive: "#991B1B",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithPurpleTheme: Story = {
  name: "With Purple Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T740" },
  },
  args: {
    children: "Purple Theme Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#9333EA",
            primaryHover: "#7E22CE",
            primaryActive: "#6B21A8",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithCustomRadius: Story = {
  name: "With Custom Radius",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T741" },
  },
  args: {
    children: "Sharp Corners Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          radius: {
            medium: "4px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithFullCustomTheme: Story = {
  name: "With Full Custom Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T742" },
  },
  args: {
    children: "Fully Custom Button",
    variant: "primary",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            primary: "#F59E0B",
            primaryHover: "#D97706",
            primaryActive: "#B45309",
          },
          radius: {
            medium: "20px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};
