import { expect, within } from "storybook/test";

import Navbar from "./Navbar";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Navbar> = {
  title: "Patterns/Navbar",
  component: Navbar,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Navbar>;

// Default Navbar example
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T926" },
  },
  args: {
    organization: {
      name: "TetraScience",
      subtext: "tetrascience",
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Organization region renders", async () => {
      expect(canvas.getByText("ORGANIZATION")).toBeInTheDocument();
      expect(canvas.getByText("TetraScience")).toBeInTheDocument();
      expect(canvas.getByText("tetrascience")).toBeInTheDocument();
    });

    await step("Project region renders", async () => {
      expect(canvas.getByText("PROJECT")).toBeInTheDocument();
      expect(canvas.getByText("Not Selected")).toBeInTheDocument();
    });
  },
};
