import { useState } from "react";

import Dropdown from "./Dropdown";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Dropdown> = {
  title: "Atoms/Dropdown",
  component: Dropdown,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    disabled: {
      control: { type: "boolean" },
    },
    error: {
      control: { type: "boolean" },
    },
    size: {
      control: { type: "select" },
      options: ["small", "xsmall"],
    },
  },
};

export default meta;
type Story = StoryObj<typeof Dropdown>;

const sampleOptions = [
  { value: "v0.0.1", label: "v0.0.1" },
  { value: "v0.0.2", label: "v0.0.2" },
  { value: "v0.0.3", label: "v0.0.3" },
  { value: "v0.0.4", label: "v0.0.4", disabled: true },
  { value: "v0.0.5", label: "v0.0.5" },
];

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T776" },
  },
  args: {
    options: sampleOptions,
    placeholder: "Placeholder",
    size: "small",
  },
};

export const XSmall: Story = {
  name: "X Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T777" },
  },
  args: {
    options: sampleOptions,
    placeholder: "Placeholder",
    size: "xsmall",
  },
};

export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T778" },
  },
  args: {
    options: sampleOptions,
    placeholder: "Placeholder",
    size: "small",
  },
};

export const WithValue: Story = {
  name: "With Value",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T779" },
  },
  args: {
    options: sampleOptions,
    value: "v0.0.1",
    placeholder: "Placeholder",
  },
};

export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T780" },
  },
  args: {
    options: sampleOptions,
    value: "v0.0.1",
    disabled: true,
    placeholder: "Placeholder",
  },
};

export const WithError: Story = {
  name: "With Error",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T781" },
  },
  args: {
    options: sampleOptions,
    error: true,
    placeholder: "Placeholder",
  },
};

export const WithDisabledOption: Story = {
  name: "With Disabled Option",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T782" },
  },
  args: {
    options: sampleOptions,
    placeholder: "Placeholder",
  },
};

export const NoData: Story = {
  name: "No Data",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T783" },
  },
  args: {
    options: [],
    placeholder: "No options available",
  },
};

// Interactive example with controlled state
const InteractiveExample = () => {
  const [selectedValue, setSelectedValue] = useState("v0.0.1");

  return (
    <div style={{ width: "200px" }}>
      <p>Selected value: {selectedValue}</p>
      <Dropdown
        options={sampleOptions}
        value={selectedValue}
        onChange={(value) => setSelectedValue(value)}
        placeholder="Select version"
      />
    </div>
  );
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T784" },
  },
  render: () => <InteractiveExample />,
};

// Showcase all variants
export const AllVariants: Story = {
  name: "All Variants",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T785" },
  },
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px", width: "200px" }}>
      <div>
        <h4>Small (36px)</h4>
        <Dropdown options={sampleOptions} placeholder="Placeholder" size="small" />
      </div>

      <div>
        <h4>Extra Small (32px)</h4>
        <Dropdown options={sampleOptions} placeholder="Placeholder" size="xsmall" />
      </div>

      <div>
        <h4>With Value</h4>
        <Dropdown options={sampleOptions} value="v0.0.1" placeholder="Placeholder" />
      </div>

      <div>
        <h4>With Error</h4>
        <Dropdown options={sampleOptions} placeholder="Placeholder" error={true} />
      </div>

      <div>
        <h4>Disabled</h4>
        <Dropdown options={sampleOptions} placeholder="Placeholder" disabled={true} />
      </div>

      <div>
        <h4>With Disabled Option Selected</h4>
        <Dropdown
          options={sampleOptions}
          value="v0.0.4" // This is a disabled option
          placeholder="Placeholder"
        />
      </div>

      <div>
        <h4>No Data</h4>
        <Dropdown options={[]} placeholder="No options available" />
      </div>
    </div>
  ),
};
