import React from "react";
import { Meta, StoryObj } from "@storybook/react-vite";
import TabGroup from "./TabGroup";

const meta: Meta<typeof TabGroup> = {
  title: "Molecules/TabGroup",
  component: TabGroup,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    disabled: {
      control: { type: "boolean" },
    },
    size: {
      control: { type: "select" },
      options: ["small", "medium"],
    },
  },
};

export default meta;
type Story = StoryObj<typeof TabGroup>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T944" },
  },
  args: {
    tabs: [
      { id: "tab1", label: "Pipeline Builder" },
      { id: "tab2", label: "Configuration" },
      { id: "tab3", label: "Launch" },
    ],
    activeTab: "tab1",
  },
};

export const Medium: Story = {
  name: "Medium",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T945" },
  },
  args: {
    tabs: [
      { id: "tab1", label: "Pipeline Builder" },
      { id: "tab2", label: "Configuration" },
      { id: "tab3", label: "Launch" },
    ],
    activeTab: "tab2",
    size: "medium",
  },
};

export const Small: Story = {
  name: "Small",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T946" },
  },
  args: {
    tabs: [
      { id: "tab1", label: "Pipeline Builder" },
      { id: "tab2", label: "Configuration" },
      { id: "tab3", label: "Launch" },
    ],
    activeTab: "tab3",
    size: "small",
  },
};

export const Disabled: Story = {
  name: "Disabled",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T947" },
  },
  args: {
    tabs: [
      { id: "tab1", label: "Pipeline Builder" },
      { id: "tab2", label: "Configuration" },
      { id: "tab3", label: "Launch" },
    ],
    activeTab: "tab2",
    disabled: true,
  },
};

export const WithDisabledTab: Story = {
  name: "With Disabled Tab",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T948" },
  },
  args: {
    tabs: [
      { id: "tab1", label: "Pipeline Builder" },
      { id: "tab2", label: "Configuration", disabled: true },
      { id: "tab3", label: "Launch" },
    ],
    activeTab: "tab3",
  },
};

// Interactive example component
const InteractiveExample = () => {
  const [activeTabId, setActiveTabId] = React.useState("tab1");

  return (
    <div style={{ width: "600px" }}>
      <h3>Click a tab to change active state</h3>
      <TabGroup
        tabs={[
          { id: "tab1", label: "Pipeline Builder" },
          { id: "tab2", label: "Configuration" },
          { id: "tab3", label: "Launch" },
        ]}
        activeTab={activeTabId}
        onChange={(tabId) => setActiveTabId(tabId)}
      />
    </div>
  );
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T949" },
  },
  render: () => <InteractiveExample />,
};
