import {
  Box,
  CheckCheck,
  Code,
  Database,
  Lamp,
  Monitor,
  PieChart,
  Search,
  SearchCode,
  Settings,
  Workflow,
} from "lucide-react"
import { useState } from "react"
import { expect, userEvent, within } from "storybook/test"

import AppSidebar from "./Sidebar"

import type { Meta, StoryObj } from "@storybook/react-vite"

const meta: Meta<typeof AppSidebar> = {
  title: "Patterns/Sidebar",
  component: AppSidebar,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <div style={{ height: "100vh" }}>
        <Story />
      </div>
    ),
  ],
}

export default meta
type Story = StoryObj<typeof AppSidebar>

const sidebarItems = [
  { icon: Search, label: "Search" },
  { icon: SearchCode, label: "SQL Search" },
  { icon: Lamp, label: "Projects" },
  { icon: Workflow, label: "Pipelines" },
  { icon: Monitor, label: "Data & AI Workspace" },
  { icon: Box, label: "Artifacts" },
  { icon: Database, label: "Data Sources" },
  { icon: PieChart, label: "Health Monitoring" },
  { icon: CheckCheck, label: "Bulk Actions" },
  { icon: Code, label: "Attribute Management" },
  { icon: Settings, label: "Administration" },
]

// Default sidebar with static items
const InteractiveComponent = () => {
  const [activeItem, setActiveItem] = useState("Pipelines")

  const handleItemClick = (label: string) => {
    setActiveItem(label)
  }

  return (
    <div style={{ display: "flex", height: "100%" }}>
      <AppSidebar items={sidebarItems} activeItem={activeItem} onItemClick={handleItemClick} />
      <div
        style={{
          padding: "20px",
          backgroundColor: "#f5f7f9",
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            fontSize: "18px",
            color: "#333",
            textAlign: "center",
          }}
        >
          <p>
            Selected navigation: <strong>{activeItem}</strong>
          </p>
          <p>Click on sidebar items to navigate</p>
        </div>
      </div>
    </div>
  )
}

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T942" },
  },
  args: {
    items: sidebarItems,
    activeItem: "Pipelines",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Primary navigation labels render", async () => {
      expect(canvas.getByText("Search")).toBeInTheDocument()
      expect(canvas.getByText("Pipelines")).toBeInTheDocument()
      expect(canvas.getByText("Administration")).toBeInTheDocument()
    })

    await step("Additional menu items render", async () => {
      expect(canvas.getByText("SQL Search")).toBeInTheDocument()
      expect(canvas.getByText("Data Sources")).toBeInTheDocument()
    })
  },
}

// Interactive sidebar with state
export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T943" },
  },
  render: () => <InteractiveComponent />,
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Primary navigation labels render", async () => {
      expect(canvas.getByText("Search")).toBeInTheDocument()
      expect(canvas.getAllByText("Pipelines").length).toBeGreaterThanOrEqual(1)
      expect(canvas.getByText("Administration")).toBeInTheDocument()
    })

    await step("Main panel shows selected navigation", async () => {
      expect(canvas.getByText("Selected navigation:")).toBeInTheDocument()
      expect(canvas.getByText("Click on sidebar items to navigate")).toBeInTheDocument()
    })
  },
}

// --- New stories for expanded test coverage ---

export const AllItemsRendered: Story = {
  name: "All Items Rendered",
  parameters: {
    zephyr: { testCaseId: "SW-T944" },
  },
  args: {
    items: sidebarItems,
    activeItem: "Pipelines",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("All 11 sidebar items render", async () => {
      for (const item of sidebarItems) {
        expect(canvas.getByText(item.label)).toBeInTheDocument()
      }
    })

    await step("Each item has an icon", async () => {
      // Each sidebar item wrapper should contain an svg icon
      const items = canvasElement.querySelectorAll("svg")
      expect(items.length).toBeGreaterThanOrEqual(sidebarItems.length)
    })
  },
}

export const ActiveItemHighlight: Story = {
  name: "Active Item Highlight",
  parameters: {
    zephyr: { testCaseId: "SW-T945" },
  },
  args: {
    items: sidebarItems,
    activeItem: "Data Sources",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Active item exists in the sidebar", async () => {
      expect(canvas.getByText("Data Sources")).toBeInTheDocument()
    })

    await step("Active item has bg-primary class", async () => {
      const activeItemWrapper = canvas.getByText("Data Sources").closest("[class*='cursor-pointer']")
      expect(activeItemWrapper?.className).toContain("bg-primary")
      expect(activeItemWrapper?.className).not.toContain("bg-transparent")
    })

    await step("Non-active items have bg-transparent", async () => {
      const inactiveWrapper = canvas.getByText("Search").closest("[class*='cursor-pointer']")
      expect(inactiveWrapper?.className).toContain("bg-transparent")
    })
  },
}

export const ClickNavigation: Story = {
  name: "Click Navigation",
  parameters: {
    zephyr: { testCaseId: "SW-T946" },
  },
  render: () => <InteractiveComponent />,
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Initial active item is Pipelines", async () => {
      const strong = canvas.getByText("Pipelines", { selector: "strong" })
      expect(strong).toBeInTheDocument()
    })

    await step("Click on Search changes active item", async () => {
      await userEvent.click(canvas.getByText("Search"))
      const strong = canvas.getByText("Search", { selector: "strong" })
      expect(strong).toBeInTheDocument()
    })

    await step("Click on Administration changes active item", async () => {
      await userEvent.click(canvas.getByText("Administration"))
      const strong = canvas.getByText("Administration", { selector: "strong" })
      expect(strong).toBeInTheDocument()
    })

    await step("Click on Data & AI Workspace changes active item", async () => {
      await userEvent.click(canvas.getByText("Data & AI Workspace"))
      const strong = canvas.getByText("Data & AI Workspace", { selector: "strong" })
      expect(strong).toBeInTheDocument()
    })
  },
}

export const KeyboardAccessibility: Story = {
  name: "Keyboard Accessibility",
  parameters: {
    zephyr: { testCaseId: "SW-T947" },
  },
  render: () => <InteractiveComponent />,
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Sidebar items have onKeyDown handlers", async () => {
      const searchText = canvas.getByText("Search")
      const itemContainer = searchText.closest("[class*='cursor-pointer']") as HTMLElement
      expect(itemContainer).toBeTruthy()
    })

    await step("Items respond to click interactions", async () => {
      await userEvent.click(canvas.getByText("Search"))
      const strong = canvas.getByText("Search", { selector: "strong" })
      expect(strong).toBeInTheDocument()
    })

    await step("Cursor pointer class applied to all items", async () => {
      const items = canvasElement.querySelectorAll("[class*='cursor-pointer']")
      expect(items.length).toBe(sidebarItems.length)
    })
  },
}

export const MinimalItems: Story = {
  name: "Minimal Items",
  parameters: {
    zephyr: { testCaseId: "SW-T948" },
  },
  args: {
    items: [
      { icon: Search, label: "Search" },
      { icon: Settings, label: "Settings" },
    ],
    activeItem: "Search",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Renders with only two items", async () => {
      expect(canvas.getByText("Search")).toBeInTheDocument()
      expect(canvas.getByText("Settings")).toBeInTheDocument()
    })

    await step("No other items present", async () => {
      expect(canvas.queryByText("Pipelines")).not.toBeInTheDocument()
      expect(canvas.queryByText("Administration")).not.toBeInTheDocument()
    })
  },
}

export const NoActiveItem: Story = {
  name: "No Active Item",
  parameters: {
    zephyr: { testCaseId: "SW-T949" },
  },
  args: {
    items: sidebarItems,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("All items render", async () => {
      expect(canvas.getByText("Search")).toBeInTheDocument()
      expect(canvas.getByText("Administration")).toBeInTheDocument()
    })

    await step("All items have bg-transparent (no active)", async () => {
      const items = canvasElement.querySelectorAll("[class*='cursor-pointer']")
      for (const item of items) {
        expect(item.className).toContain("bg-transparent")
      }
    })
  },
}
