import {
  Box,
  CheckCheck,
  Code,
  Database,
  Lamp,
  Monitor,
  PieChart,
  Search,
  SearchCode,
  Settings,
  Workflow,
} from "lucide-react";
import { useState } from "react";

import AppSidebar from "./Sidebar";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof AppSidebar> = {
  title: "Patterns/Sidebar",
  component: AppSidebar,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <div style={{ height: "100vh" }}>
        <Story />
      </div>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof AppSidebar>;

const sidebarItems = [
  { icon: Search, label: "Search" },
  { icon: SearchCode, label: "SQL Search" },
  { icon: Lamp, label: "Projects" },
  { icon: Workflow, label: "Pipelines" },
  { icon: Monitor, label: "Data & AI Workspace" },
  { icon: Box, label: "Artifacts" },
  { icon: Database, label: "Data Sources" },
  { icon: PieChart, label: "Health Monitoring" },
  { icon: CheckCheck, label: "Bulk Actions" },
  { icon: Code, label: "Attribute Management" },
  { icon: Settings, label: "Administration" },
];

// Default sidebar with static items
const InteractiveComponent = () => {
  const [activeItem, setActiveItem] = useState("Pipelines");

  const handleItemClick = (label: string) => {
    setActiveItem(label);
    console.log(`Clicked on: ${label}`);
  };

  return (
    <div style={{ display: "flex", height: "100%" }}>
      <AppSidebar items={sidebarItems} activeItem={activeItem} onItemClick={handleItemClick} />
      <div
        style={{
          padding: "20px",
          backgroundColor: "#f5f7f9",
          flex: 1,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            fontSize: "18px",
            color: "#333",
            textAlign: "center",
          }}
        >
          <p>
            Selected navigation: <strong>{activeItem}</strong>
          </p>
          <p>Click on sidebar items to navigate</p>
        </div>
      </div>
    </div>
  );
};

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T942" },
  },
  args: {
    items: sidebarItems,
    activeItem: "Pipelines",
  },
};

// Interactive sidebar with state
export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T943" },
  },
  render: () => <InteractiveComponent />,
};
