import { expect, within } from "storybook/test";

import Main from "./Main";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Main> = {
  title: "Patterns/Main",
  component: Main,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Main>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1011" },
  },
  args: {
    hostname: "localhost:3000",
    userProfile: {
      name: "Chris Calo",
      avatar: undefined,
    },
    organization: {
      name: "TetraScience",
      subtext: "tetrascience",
    },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Header shows hostname and user", async () => {
      expect(canvas.getByText("localhost:3000")).toBeInTheDocument();
      expect(canvas.getByText("Chris Calo")).toBeInTheDocument();
    });

    await step("Navbar shows organization", async () => {
      expect(canvas.getByText("TetraScience")).toBeInTheDocument();
      expect(canvas.getByText("tetrascience")).toBeInTheDocument();
    });

    await step("Sidebar and main panels render", async () => {
      expect(canvas.getByText("Pipelines")).toBeInTheDocument();
      expect(canvas.getByRole("heading", { name: "Templates", level: 2 })).toBeInTheDocument();
    });
  },
};
