import { expect, within } from "storybook/test";

import { COLORS } from "../../../utils/colors";

import { Histogram } from "./Histogram";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof Histogram> = {
  title: "Charts/Histogram",
  component: Histogram,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Histogram>;

const generateNormalData = (mean: number, stdDev: number, count: number): number[] => {
  const data: number[] = [];

  for (let i = 0; i < count; i++) {
    const u1 = Math.random();
    const u2 = Math.random();
    const z0 = Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math.PI * u2);
    const value = mean + z0 * stdDev;
    data.push(value);
  }

  return data;
};

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T990" },
  },
  args: {
    dataSeries: {
      x: generateNormalData(20, 8, 200),
      name: "Label",
    },
    title: "Histogram",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Histogram")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One histogram trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const WithCustomColor: Story = {
  name: "With Custom Color",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T991" },
  },
  args: {
    dataSeries: {
      x: generateNormalData(20, 8, 200),
      name: "Custom Color",
      color: COLORS.RED,
    },
    title: "Histogram with Custom Color",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Histogram with Custom Color")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One histogram trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const WithCustomBins: Story = {
  name: "With Custom Bins",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T992" },
  },
  args: {
    dataSeries: {
      x: generateNormalData(20, 8, 200),
      name: "Custom Bins",
      autobinx: false,
      xbins: {
        start: 0,
        end: 40,
        size: 4,
      },
    },
    title: "Histogram with Custom Bins",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Histogram with Custom Bins")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("One histogram trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(1);
    });

    await step("Custom bins render visible bars", async () => {
      const barPoints = canvasElement.querySelectorAll(".barlayer .bars .point");
      expect(barPoints.length).toBeGreaterThan(0);
    });
  },
};

export const StackedHistogram: Story = {
  name: "Stacked Histogram",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T993" },
  },
  args: {
    dataSeries: [
      {
        x: generateNormalData(20, 8, 200),
        name: "Series A",
        color: COLORS.ORANGE,
      },
      {
        x: generateNormalData(20, 6, 150),
        name: "Series B",
        color: COLORS.RED,
      },
    ],
    title: "Group of Histogram",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Group of Histogram")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Two histogram traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(2);
    });

    await step("Legend shows series names", async () => {
      expect(canvas.getByText("Series A")).toBeInTheDocument();
      expect(canvas.getByText("Series B")).toBeInTheDocument();
    });
  },
};

export const MultipleSeries: Story = {
  name: "Multiple Series",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T994" },
  },
  args: {
    dataSeries: [
      {
        x: generateNormalData(10, 5, 100),
        name: "Series A",
        color: COLORS.BLUE,
      },
      {
        x: generateNormalData(20, 5, 100),
        name: "Series B",
        color: COLORS.RED,
      },
      {
        x: generateNormalData(30, 5, 100),
        name: "Series C",
        color: COLORS.GREEN,
      },
      {
        x: generateNormalData(40, 5, 100),
        name: "Series D",
        color: COLORS.ORANGE,
      },
    ],
    title: "Multiple Series Histogram",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 600,
    height: 480,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Multiple Series Histogram")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Four histogram traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".barlayer .trace");
      expect(traces.length).toBe(4);
    });

    await step("Legend shows series names", async () => {
      expect(canvas.getByText("Series A")).toBeInTheDocument();
      expect(canvas.getByText("Series B")).toBeInTheDocument();
      expect(canvas.getByText("Series C")).toBeInTheDocument();
      expect(canvas.getByText("Series D")).toBeInTheDocument();
    });
  },
};

export const WithDistributionLine: Story = {
  name: "With Distribution Line",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T995" },
  },
  args: {
    dataSeries: {
      x: generateNormalData(20, 8, 200),
      name: "Label",
      color: COLORS.ORANGE,
    },
    title: "Histogram with Fitted Distribution Line",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
    showDistributionLine: true,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Histogram with Fitted Distribution Line")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Histogram and distribution line traces render", async () => {
      expect(canvasElement.querySelectorAll(".barlayer .trace").length).toBe(1);
      expect(canvasElement.querySelectorAll(".scatterlayer .trace").length).toBe(1);
    });
  },
};

export const WithCustomBinsAndDistributionLine: Story = {
  name: "With Custom Bins And Distribution Line",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T996" },
  },
  args: {
    dataSeries: {
      x: generateNormalData(20, 8, 200),
      name: "Label",
      color: COLORS.ORANGE,
      autobinx: false,
      xbins: {
        start: 0,
        end: 40,
        size: 4,
      },
    },
    title: "Histogram with Fitted Distribution Line",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 480,
    height: 480,
    showDistributionLine: true,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Histogram with Fitted Distribution Line")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Histogram and distribution line traces render", async () => {
      expect(canvasElement.querySelectorAll(".barlayer .trace").length).toBe(1);
      expect(canvasElement.querySelectorAll(".scatterlayer .trace").length).toBe(1);
    });

    await step("Custom bins render visible bars", async () => {
      const barPoints = canvasElement.querySelectorAll(".barlayer .bars .point");
      expect(barPoints.length).toBeGreaterThan(0);
    });
  },
};

export const MultipleSeriesWithDistributionLines: Story = {
  name: "Multiple Series With Distribution Lines",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T997" },
  },
  args: {
    dataSeries: [
      {
        x: generateNormalData(20, 8, 200),
        name: "Series A",
        color: COLORS.ORANGE,
      },
      {
        x: generateNormalData(15, 5, 150),
        name: "Series B",
        color: COLORS.RED,
      },
    ],
    title: "Group of Histogram with Fitted Distribution Line",
    xTitle: "Torque",
    yTitle: "Frequency",
    width: 600,
    height: 500,
    showDistributionLine: true,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Group of Histogram with Fitted Distribution Line")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Two histogram and two distribution line traces render", async () => {
      expect(canvasElement.querySelectorAll(".barlayer .trace").length).toBe(2);
      expect(canvasElement.querySelectorAll(".scatterlayer .trace").length).toBe(2);
    });

    await step("Legend shows series names", async () => {
      expect(canvas.getByText("Series A")).toBeInTheDocument();
      expect(canvas.getByText("Series B")).toBeInTheDocument();
    });
  },
};
