import { useState } from "react";
import { expect, within } from "storybook/test";

import ProtocolYamlCard from "./ProtocolYamlCard";

export default {
  title: "Patterns/ProtocolYamlCard",
  component: ProtocolYamlCard,
};

const versionOptions:  { value: string; label: string }[] = [
  { value: "v0.0.1", label: "v0.0.1" },
  { value: "v0.0.0", label: "v0.0.0" },
];

const initialYaml = `protocolSchema: v3\nname: v3\ndescription: No description\nconfig: {}\nsteps: []\n`;

export const Default = () => {
  const [newVersionMode, setNewVersionMode] = useState(false);
  const [selectedVersion, setSelectedVersion] = useState(versionOptions[0].value);
  const [yaml, setYaml] = useState(initialYaml);

  return (
    <ProtocolYamlCard
      title="Protocol Yaml"
      newVersionMode={newVersionMode}
      onToggleNewVersionMode={setNewVersionMode}
      versionOptions={versionOptions}
      selectedVersion={selectedVersion}
      onVersionChange={setSelectedVersion}
      onDeploy={() => alert("Deploy clicked!")}
      yaml={yaml}
      onYamlChange={setYaml}
    />
  );
};
Default.storyName = "Default";
Default.parameters = {
  // Auto-generated by sync-storybook-zephyr - do not add manually
  zephyr: { testCaseId: "SW-T931" },
};
Default.play = async ({ canvasElement, step }) => {
  const canvas = within(canvasElement);

  await step("Card title and controls render", async () => {
    expect(canvas.getByText("Protocol Yaml")).toBeInTheDocument();
    expect(canvas.getByText("New Version Mode")).toBeInTheDocument();
    expect(canvas.getByRole("button", { name: "Deploy" })).toBeInTheDocument();
  });

  await step("Version selector shows current version", async () => {
    expect(canvas.getByText("v0.0.1")).toBeInTheDocument();
  });
};
