import { expect, waitFor, within } from "storybook/test";


import { ScatterPlot, type MarkerSymbol, type ScatterPlotDataSeries } from "./ScatterPlot";

import type { Meta, StoryObj } from "@storybook/react-vite";

const generateScatterDemoData = (): ScatterPlotDataSeries[] => {
  return [
    {
      name: "Data A",
      x: [400, 430, 450, 470, 490, 510, 530, 550, 570, 590, 610, 630, 650],
      y: [85, 72, 75, 92, 87, 125, 143, 145, 150, 165, 170, 160, 145],
    },
    {
      name: "Data B",
      x: [390, 410, 430, 450, 470, 490, 510, 530, 550, 570, 590, 610],
      y: [50, 75, 80, 85, 100, 105, 115, 135, 140, 150, 155, 145],
    },
    {
      name: "Data C",
      x: [410, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620, 640],
      y: [60, 85, 90, 100, 110, 120, 125, 150, 160, 165, 175, 170],
    },
  ];
};

// Generate grid data for dense marker layouts
const generateGridData = (rows: number, cols: number, density: number = 0.15): { x: number[]; y: number[] } => {
  const x: number[] = [];
  const y: number[] = [];

  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      if (Math.random() < density) {
        x.push(col);
        y.push(row);
      }
    }
  }

  return { x, y };
};

// Generate stacked data for multiple series
const generateStackedData = (
  rows: number,
  cols: number,
  seriesCount: number,
): Array<{ x: number[]; y: number[]; name: string }> => {
  const series: Array<{ x: number[]; y: number[]; name: string }> = [];

  for (let i = 0; i < seriesCount; i++) {
    const { x, y } = generateGridData(rows, cols, 0.05);
    series.push({
      x,
      y: y.map((val) => val + i * 0.2), // Slight offset for stacking effect
      name: "Label",
    });
  }

  return series;
};

const meta: Meta<typeof ScatterPlot> = {
  title: "Data Viz/Scatter Plot",
  component: ScatterPlot,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof ScatterPlot>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1017" },
  },
  args: {
    dataSeries: generateScatterDemoData(),
    width: 900,
    height: 600,
    title: "Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const CustomRanges: Story = {
  name: "Custom Ranges",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1018" },
  },
  args: {
    ...Default.args,
    xRange: [300, 700],
    yRange: [0, 200],
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Three traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(3);
    });

    await step("Legend shows all series names", async () => {
      expect(canvas.getByText("Data A")).toBeInTheDocument();
      expect(canvas.getByText("Data B")).toBeInTheDocument();
      expect(canvas.getByText("Data C")).toBeInTheDocument();
    });
  },
};

export const SingleSeries: Story = {
  name: "Single Series",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T978" },
  },
  args: {
    dataSeries: {
      x: generateGridData(25, 41, 0.12).x,
      y: generateGridData(25, 41, 0.12).y,
      name: "Label",
    },
    title: "Single Series Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "default",
    markerSize: 8,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Single Series Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Single trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const Stacked: Story = {
  name: "Stacked",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T979" },
  },
  args: {
    dataSeries: generateStackedData(25, 41, 4).map((series, index) => ({
      ...series,
      symbol: (["circle", "square", "diamond", "triangle-up"] as MarkerSymbol[])[index],
    })),
    title: "Stacked Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "stacked",
    markerSize: 8,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Stacked Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Multiple traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(4);
    });

    await step("Legend shows series labels", async () => {
      expect(canvas.getAllByText("Label").length).toBe(4);
    });
  },
};

export const WithCustomColors: Story = {
  name: "With Custom Colors",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T980" },
  },
  args: {
    dataSeries: [
      {
        x: generateGridData(15, 25, 0.15).x,
        y: generateGridData(15, 25, 0.15).y,
        name: "Series A",
        color: "#2D9CDB",
        symbol: "circle" as MarkerSymbol,
      },
      {
        x: generateGridData(15, 25, 0.1).x,
        y: generateGridData(15, 25, 0.1).y,
        name: "Series B",
        color: "#FF5C64",
        symbol: "square" as MarkerSymbol,
      },
    ],
    title: "Custom Colors Scatter Plot",
    xTitle: "X Axis",
    yTitle: "Y Axis",
    width: 1000,
    height: 600,
    variant: "stacked",
    markerSize: 10,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Custom Colors Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Multiple traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(2);
    });

    await step("Legend shows series names", async () => {
      expect(canvas.getByText("Series A")).toBeInTheDocument();
      expect(canvas.getByText("Series B")).toBeInTheDocument();
    });
  },
};

export const LargeMarkers: Story = {
  name: "Large Markers",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T981" },
  },
  args: {
    dataSeries: {
      x: generateGridData(12, 20, 0.18).x,
      y: generateGridData(12, 20, 0.18).y,
      name: "Large Dots",
    },
    title: "Large Marker Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "default",
    markerSize: 15,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Large Marker Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Single trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const MultipleSeriesColors: Story = {
  name: "Multiple Series Colors",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T982" },
  },
  args: {
    dataSeries: [
      {
        x: generateGridData(10, 15, 0.12).x,
        y: generateGridData(10, 15, 0.12).y,
        name: "Series A",
        symbol: "circle" as MarkerSymbol,
      },
      {
        x: generateGridData(10, 15, 0.1).x,
        y: generateGridData(10, 15, 0.1).y,
        name: "Series B",
        symbol: "square" as MarkerSymbol,
      },
      {
        x: generateGridData(10, 15, 0.1).x,
        y: generateGridData(10, 15, 0.1).y,
        name: "Series C",
        symbol: "diamond" as MarkerSymbol,
      },
      {
        x: generateGridData(10, 15, 0.09).x,
        y: generateGridData(10, 15, 0.09).y,
        name: "Series D",
        symbol: "triangle-up" as MarkerSymbol,
      },
    ],
    title: "Multiple Series Colors",
    xTitle: "Position X",
    yTitle: "Position Y",
    width: 1000,
    height: 600,
    variant: "stacked",
    markerSize: 12,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Multiple Series Colors")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Multiple traces are rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(4);
    });

    await step("Legend shows series names", async () => {
      expect(canvas.getByText("Series A")).toBeInTheDocument();
      expect(canvas.getByText("Series B")).toBeInTheDocument();
      expect(canvas.getByText("Series C")).toBeInTheDocument();
      expect(canvas.getByText("Series D")).toBeInTheDocument();
    });
  },
};

export const SmallScale: Story = {
  name: "Small Scale",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T983" },
  },
  args: {
    dataSeries: {
      x: generateGridData(8, 12, 0.4).x,
      y: generateGridData(8, 12, 0.4).y,
      name: "Small Grid",
    },
    title: "Small Scale Scatter Plot",
    xTitle: "X",
    yTitle: "Y",
    width: 500,
    height: 600,
    variant: "default",
    markerSize: 6,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("Small Scale Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Single trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const HighDensity: Story = {
  name: "High Density",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T984" },
  },
  args: {
    dataSeries: {
      x: generateGridData(20, 30, 0.25).x,
      y: generateGridData(20, 30, 0.25).y,
      name: "High Density",
    },
    title: "High Density Scatter Plot",
    xTitle: "Columns",
    yTitle: "Rows",
    width: 1000,
    height: 600,
    variant: "default",
    markerSize: 6,
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step("Chart title is displayed", async () => {
      expect(canvas.getByText("High Density Scatter Plot")).toBeInTheDocument();
    });

    await step("Chart container renders", async () => {
      expect(canvasElement.querySelector(".js-plotly-plot")).toBeInTheDocument();
    });

    await step("Single trace is rendered", async () => {
      const traces = canvasElement.querySelectorAll(".scatterlayer .trace");
      expect(traces.length).toBe(1);
    });
  },
};

export const ContainerFilled: Story = {
  name: "Container Filled (responsive)",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T5478" },
    layout: "fullscreen",
    docs: {
      description: {
        story:
          "Omit `width`/`height` and the chart fills its container, tracking size via a `ResizeObserver`. Wrapped here in an `h-80 w-full` box.",
      },
    },
  },
  args: {
    dataSeries: generateScatterDemoData(),
    title: "Fills its container",
  },
  decorators: [
    (Story) => (
      <div data-testid="fill-wrapper" className="h-80 w-full">
        <Story />
      </div>
    ),
  ],
  play: async ({ canvasElement, step }) => {
    await step("Chart canvas fills the container width", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot).toBeInTheDocument();
        expect(plot.clientWidth).toBeGreaterThanOrEqual(wrapper.clientWidth - 2);
      });
    });

    await step("Chart resizes in place when the container resizes", async () => {
      const wrapper = canvasElement.querySelector(
        '[data-testid="fill-wrapper"]',
      ) as HTMLElement;
      // Shrink the container; the ResizeObserver should drive a Plotly relayout
      // (not a full re-plot) so the canvas tracks the new width.
      wrapper.style.width = "440px";
      await waitFor(() => {
        const plot = canvasElement.querySelector(".js-plotly-plot") as HTMLElement;
        expect(plot.clientWidth).toBeGreaterThanOrEqual(420);
        expect(plot.clientWidth).toBeLessThanOrEqual(460);
      });
    });
  },
};
