import React, { useState } from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "@atoms/Button";
import { Modal } from "@atoms/Modal";
import { ThemeProvider } from "../../../theme";

const meta: Meta<typeof Modal> = {
  title: "Atoms/Modal",
  component: Modal,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof Modal>;

// Base story
export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T820" },
  },
  args: {
    isOpen: true,
    onClose: () => console.log("Modal closed"),
    onConfirm: () => console.log("Modal confirmed"),
    title: "Title",
    children: (
      <p>
        Are you sure you want to reset this view? you will need to input all the settings and load all the graph from
        the start
      </p>
    ),
  },
};

// Modal with hidden actions
export const HiddenActions: Story = {
  name: "Hidden Actions",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T821" },
  },
  args: {
    ...Default.args,
    hideActions: true,
  },
};
const InteractiveComponent = () => {
  const [isOpen, setIsOpen] = useState(false);

  const handleOpen = () => {
    setIsOpen(true);
  };

  const handleClose = () => {
    setIsOpen(false);
  };

  const handleConfirm = () => {
    console.log("Reset confirmed");
    setIsOpen(false);
  };

  return (
    <div>
      <Button onClick={handleOpen} variant="primary">
        Open Modal
      </Button>
      <Modal isOpen={isOpen} onClose={handleClose} onConfirm={handleConfirm} title="Title">
        <p>
          Are you sure you want to reset this view? you will need to input all the settings and load all the graph from
          the start
        </p>
      </Modal>
    </div>
  );
};

// Modal with custom width
export const CustomWidth: Story = {
  name: "Custom Width",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T822" },
  },
  args: {
    ...Default.args,
    width: "800px",
  },
};

// Modal with long scrollable content
export const LongContent: Story = {
  name: "Long Content",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T823" },
  },
  args: {
    ...Default.args,
    children: (
      <>
        {Array(10)
          .fill(0)
          .map((_, i) => (
            <p key={i}>
              This is paragraph {i + 1}. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu justo eu
              nisi ultrices facilisis. Donec vestibulum metus at sem faucibus, a commodo nunc ultricies.
            </p>
          ))}
      </>
    ),
  },
};

// Interactive example
const InteractiveWithThemeComponent = () => {
  const [isOpen, setIsOpen] = useState(false);

  const handleOpen = () => {
    setIsOpen(true);
  };

  const handleClose = () => {
    setIsOpen(false);
  };

  const handleConfirm = () => {
    console.log("Reset confirmed");
    setIsOpen(false);
  };

  return (
    <ThemeProvider
      theme={{
        colors: {
          primary: "#DC2626",
          primaryHover: "#B91C1C",
          primaryActive: "#991B1B",
          background: "#FEE2E2",
        },
        radius: {
          large: "8px",
          medium: "8px",
        },
      }}
    >
      <div>
        <Button onClick={handleOpen} variant="primary">
          Open Themed Modal
        </Button>
        <Modal isOpen={isOpen} onClose={handleClose} onConfirm={handleConfirm} title="Themed Modal">
          <p>This modal and button are both themed with custom red colors and sharp corners!</p>
        </Modal>
      </div>
    </ThemeProvider>
  );
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T824" },
  },
  render: () => <InteractiveComponent />,
};

// Modal with custom content
export const CustomContent: Story = {
  name: "Custom Content",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T825" },
  },
  args: {
    ...Default.args,
    title: "Custom Form",
    children: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <input
          type="text"
          placeholder="Enter your name"
          style={{
            padding: "8px",
            borderRadius: "4px",
            border: "1px solid var(--grey-200)",
          }}
        />
        <textarea
          placeholder="Enter your message"
          rows={4}
          style={{
            padding: "8px",
            borderRadius: "4px",
            border: "1px solid var(--grey-200)",
          }}
        />
      </div>
    ),
  },
};

// Theme examples
export const WithSharpCorners: Story = {
  name: "With Sharp Corners",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T826" },
  },
  args: {
    ...Default.args,
    title: "Sharp Corners Modal",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          radius: {
            large: "4px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithCustomBackground: Story = {
  name: "With Custom Background",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T827" },
  },
  args: {
    ...Default.args,
    title: "Custom Background Modal",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            background: "#FEF3C7",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const WithFullTheme: Story = {
  name: "With Full Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T828" },
  },
  args: {
    ...Default.args,
    title: "Fully Themed Modal",
  },
  decorators: [
    (Story) => (
      <ThemeProvider
        theme={{
          colors: {
            background: "#F3E8FF",
            primary: "#9333EA",
            primaryHover: "#7E22CE",
            primaryActive: "#6B21A8",
          },
          radius: {
            large: "24px",
            medium: "12px",
          },
        }}
      >
        <Story />
      </ThemeProvider>
    ),
  ],
};

export const InteractiveWithTheme: Story = {
  name: "Interactive With Theme",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T829" },
  },
  render: () => <InteractiveWithThemeComponent />,
};
