import { SupportiveText } from "./SupportiveText";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof SupportiveText> = {
  title: "Atoms/SupportiveText",
  component: SupportiveText,
  tags: ["autodocs"],
  argTypes: {
    children: { control: "text" },
    showCheck: { control: "boolean" },
  },
};

export default meta;
type Story = StoryObj<typeof SupportiveText>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T835" },
  },
  args: {
    children: "This is a supportive text",
  },
};

export const WithCheckIcon: Story = {
  name: "With Check Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T836" },
  },
  args: {
    children: "This is a supportive text with check icon",
    showCheck: true,
  },
};
