/**
 * Deployed MCP endpoint for the TetraScience UI kit Storybook.
 *
 * `@storybook/addon-mcp` only serves `/mcp` from a running `storybook dev`
 * process, so it cannot run on the static Storybook we deploy to Vercel. This
 * Vercel serverless function provides the deployed equivalent: a stateless
 * Streamable-HTTP MCP server exposing the "docs" toolset (component discovery,
 * props/variants, and authored usage examples) over the catalog produced at
 * build time by `scripts/mcp/build-metadata.ts`.
 *
 * Vercel auto-routes this file to `/api/mcp`. AI agents connect with:
 *   npx mcp-add --type http --url "https://<deployment-host>/api/mcp"
 */
import fs from "node:fs";
import path from "node:path";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";

import type { VercelRequest, VercelResponse } from "@vercel/node";

interface ArgType {
  control?: string;
  options?: unknown[];
  description?: string;
}

interface StoryMeta {
  name: string;
  args?: Record<string, unknown>;
  hasPlayTest?: boolean;
}

interface ComponentMeta {
  title: string;
  name: string;
  importPath: string;
  tags: string[];
  hasDocsPage: boolean;
  argTypes: Record<string, ArgType>;
  defaultArgs: Record<string, unknown>;
  stories: StoryMeta[];
}

interface Catalog {
  generatedAt: string;
  packageName: string;
  packageVersion: string;
  componentCount: number;
  components: ComponentMeta[];
}

// The catalog is generated by `scripts/mcp/build-metadata.ts` into the static
// Storybook output and bundled into this function via `functions.includeFiles`
// in vercel.json. It is read from disk (not fetched over HTTP) so the function
// makes no outbound request — there is no user-controlled URL and thus no SSRF
// surface. Path is resolved from the project root (process.cwd() on Vercel).
const CATALOG_FILE = path.join(
  process.cwd(),
  "storybook-static",
  "mcp",
  "components.json",
);

// Static per deployment, so read and cache it once per warm instance.
let cachedCatalog: Catalog | undefined;

function getCatalog(): Catalog {
  if (cachedCatalog) return cachedCatalog;
  let raw: string;
  try {
    raw = fs.readFileSync(CATALOG_FILE, "utf8");
  } catch {
    throw new Error(
      `Component catalog not found at ${CATALOG_FILE}. Ensure \`yarn build-storybook\` ` +
        `ran the metadata step and that vercel.json bundles it via functions.includeFiles.`,
    );
  }
  cachedCatalog = JSON.parse(raw) as Catalog;
  return cachedCatalog;
}

function findComponent(catalog: Catalog, query: string): ComponentMeta | undefined {
  const needle = query.trim().toLowerCase();
  return (
    catalog.components.find((c) => c.title.toLowerCase() === needle) ??
    catalog.components.find((c) => c.name.toLowerCase() === needle) ??
    catalog.components.find((c) => c.title.toLowerCase().endsWith(`/${needle}`)) ??
    catalog.components.find((c) => c.name.toLowerCase().includes(needle))
  );
}

function jsonContent(value: unknown): { content: { type: "text"; text: string }[] } {
  return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }] };
}

function buildServer(catalog: Catalog): McpServer {
  const server = new McpServer({
    name: `${catalog.packageName}-storybook`,
    version: catalog.packageVersion,
  });

  server.registerTool(
    "list_components",
    {
      title: "List UI kit components",
      description:
        `List every component published in the ${catalog.packageName} Storybook, ` +
        `with its story count, tags, and whether it has a docs page. ` +
        `Use this first to discover what the UI kit offers before scaffolding.`,
    },
    () =>
      jsonContent({
        packageName: catalog.packageName,
        packageVersion: catalog.packageVersion,
        componentCount: catalog.componentCount,
        components: catalog.components.map((c) => ({
          title: c.title,
          name: c.name,
          tags: c.tags,
          storyCount: c.stories.length,
          hasDocsPage: c.hasDocsPage,
        })),
      }),
  );

  server.registerTool(
    "get_component",
    {
      title: "Get component details",
      description:
        `Get the full metadata for one component: its prop controls (argTypes, ` +
        `including the exact allowed variant/size options), default args, and every ` +
        `story with its concrete args (copy-pasteable usage examples). Always prefer ` +
        `these authoritative values over guessing a component's API.`,
      inputSchema: {
        name: z
          .string()
          .describe(
            'Component name or Storybook title, e.g. "Button" or "Components/Button".',
          ),
      },
    },
    ({ name }) => {
      const component = findComponent(catalog, name);
      if (!component) {
        return {
          isError: true,
          content: [
            {
              type: "text",
              text: `No component matching "${name}". Call list_components to see available names.`,
            },
          ],
        };
      }
      return jsonContent({
        ...component,
        importHint: `import { ${component.name} } from "${catalog.packageName}";`,
      });
    },
  );

  server.registerTool(
    "search_components",
    {
      title: "Search components",
      description:
        "Search components by name, Storybook title, tags, or prop names. Returns " +
        "matching components ranked by relevance. Use when you know what you need " +
        '(e.g. "chart", "table", "form input") but not the exact component name.',
      inputSchema: {
        query: z.string().describe("Free-text search term."),
      },
    },
    ({ query }) => {
      const needle = query.trim().toLowerCase();
      const matches = catalog.components
        .map((c) => {
          const haystack = [
            c.title,
            c.name,
            ...c.tags,
            ...Object.keys(c.argTypes),
          ]
            .join(" ")
            .toLowerCase();
          return { component: c, hit: haystack.includes(needle) };
        })
        .filter((m) => m.hit)
        .map((m) => ({
          title: m.component.title,
          name: m.component.name,
          tags: m.component.tags,
          storyCount: m.component.stories.length,
        }));
      return jsonContent({ query, matchCount: matches.length, matches });
    },
  );

  return server;
}

function setCorsHeaders(res: VercelResponse): void {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Content-Type, Authorization, mcp-session-id, mcp-protocol-version",
  );
  res.setHeader("Access-Control-Expose-Headers", "mcp-session-id");
}

export default async function handler(
  req: VercelRequest,
  res: VercelResponse,
): Promise<void> {
  setCorsHeaders(res);

  if (req.method === "OPTIONS") {
    res.status(204).end();
    return;
  }

  try {
    const catalog = getCatalog();
    const server = buildServer(catalog);

    // Stateless mode: a fresh server + transport per request (no sessions),
    // which matches the serverless execution model. JSON responses avoid SSE.
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: undefined,
      enableJsonResponse: true,
    });

    res.on("close", () => {
      void transport.close();
      void server.close();
    });

    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    if (!res.headersSent) {
      res.status(500).json({
        jsonrpc: "2.0",
        error: { code: -32603, message: `MCP server error: ${message}` },
        id: null,
      });
    }
  }
}
