name: CI

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.0-noble
    timeout-minutes: 30 

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Type Check
        run: yarn typecheck

      - name: Run Tests with Coverage
        run: yarn run test:all:coverage

      - name: Coverage
        uses: tetrascience/ts-ci-cd-lib/coverage-check@main