import { expect, within } from "storybook/test"

import { Badge } from "./badge"

import type { Meta, StoryObj } from "@storybook/react-vite"


const meta: Meta<typeof Badge> = {
  title: "Components/Badge",
  component: Badge,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["default", "secondary", "info", "destructive", "positive", "warning", "outline", "ghost", "link"],
    },
  },
  args: {
    children: "Badge",
    variant: "default",
  },
}

export default meta

type Story = StoryObj<typeof Badge>

export const Default: Story = {
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1192" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Badge text renders", async () => {
      expect(canvas.getByText("Badge")).toBeInTheDocument()
    })
  },
}

export const Secondary: Story = {
  args: {
    children: "Secondary Badge",
    variant: "secondary",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1193" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Secondary badge text renders", async () => {
      expect(canvas.getByText("Secondary Badge")).toBeInTheDocument()
    })
  },
}

export const Info: Story = {
  args: {
    children: "Info Badge",
    variant: "info",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Info badge text renders", async () => {
      expect(canvas.getByText("Info Badge")).toBeInTheDocument()
    })
  },
}

export const Destructive: Story = {
  args: {
    children: "Destructive Badge",
    variant: "destructive",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1194" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Destructive badge text renders", async () => {
      expect(canvas.getByText("Destructive Badge")).toBeInTheDocument()
    })
  },
}

export const Positive: Story = {
  args: {
    children: "Positive Badge",
    variant: "positive",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Positive badge text renders", async () => {
      expect(canvas.getByText("Positive Badge")).toBeInTheDocument()
    })
  },
}

export const Warning: Story = {
  args: {
    children: "Warning Badge",
    variant: "warning",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Warning badge text renders", async () => {
      expect(canvas.getByText("Warning Badge")).toBeInTheDocument()
    })
  },
}

export const Outline: Story = {
  args: {
    children: "Outline Badge",
    variant: "outline",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1195" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Outline badge text renders", async () => {
      expect(canvas.getByText("Outline Badge")).toBeInTheDocument()
    })
  },
}

export const Ghost: Story = {
  args: {
    children: "Ghost Badge",
    variant: "ghost",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1196" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Ghost badge text renders", async () => {
      expect(canvas.getByText("Ghost Badge")).toBeInTheDocument()
    })
  },
}

export const Link: Story = {
  args: {
    children: "Link Badge",
    variant: "link",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1197" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Link badge text renders", async () => {
      expect(canvas.getByText("Link Badge")).toBeInTheDocument()
    })
  },
}