import { expect, within } from "storybook/test"

import { Badge } from "./badge"

import type { Meta, StoryObj } from "@storybook/react-vite"


const meta: Meta<typeof Badge> = {
  title: "Components/Badge",
  component: Badge,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["default", "secondary", "info", "destructive", "positive", "warning", "outline", "ghost", "link"],
    },
  },
  args: {
    children: "Badge",
    variant: "default",
  },
}

export default meta

type Story = StoryObj<typeof Badge>

export const Default: Story = {
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T1192" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Badge")

    await step("Badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has correct data attributes", async () => {
      expect(badge).toHaveAttribute("data-slot", "badge")
      expect(badge).toHaveAttribute("data-variant", "default")
    })

    await step("Badge renders as a span element", async () => {
      expect(badge.tagName).toBe("SPAN")
    })
  },
}

export const Secondary: Story = {
  args: {
    children: "Secondary Badge",
    variant: "secondary",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1193" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Secondary Badge")

    await step("Secondary badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has secondary variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "secondary")
    })
  },
}

export const Info: Story = {
  args: {
    children: "Info Badge",
    variant: "info",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Info Badge")

    await step("Info badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has info variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "info")
    })
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1397" },
  },
}

export const Destructive: Story = {
  args: {
    children: "Destructive Badge",
    variant: "destructive",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1194" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Destructive Badge")

    await step("Destructive badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has destructive variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "destructive")
    })
  },
}

export const Positive: Story = {
  args: {
    children: "Positive Badge",
    variant: "positive",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Positive Badge")

    await step("Positive badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has positive variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "positive")
    })
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1398" },
  },
}

export const Warning: Story = {
  args: {
    children: "Warning Badge",
    variant: "warning",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Warning Badge")

    await step("Warning badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has warning variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "warning")
    })
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1399" },
  },
}

export const Outline: Story = {
  args: {
    children: "Outline Badge",
    variant: "outline",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1195" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Outline Badge")

    await step("Outline badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has outline variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "outline")
    })
  },
}

export const Ghost: Story = {
  args: {
    children: "Ghost Badge",
    variant: "ghost",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1196" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Ghost Badge")

    await step("Ghost badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has ghost variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "ghost")
    })
  },
}

export const Link: Story = {
  args: {
    children: "Link Badge",
    variant: "link",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1197" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Link Badge")

    await step("Link badge text renders", async () => {
      expect(badge).toBeInTheDocument()
    })

    await step("Badge has link variant attribute", async () => {
      expect(badge).toHaveAttribute("data-variant", "link")
    })
  },
}

export const AsChild: Story = {
  args: {
    asChild: true,
  },
  render: (args) => (
    <Badge {...args}>
      <a href="#test">Link as Badge</a>
    </Badge>
  ),
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const link = canvas.getByText("Link as Badge")

    await step("Renders as child element (anchor) instead of span", async () => {
      expect(link.tagName).toBe("A")
      expect(link).toHaveAttribute("href", "#test")
    })

    await step("Data attributes are forwarded to the child element", async () => {
      expect(link).toHaveAttribute("data-slot", "badge")
      expect(link).toHaveAttribute("data-variant", "default")
    })
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1475" },
  },
}

export const CustomClassName: Story = {
  args: {
    children: "Custom Badge",
    className: "my-custom-class",
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)
    const badge = canvas.getByText("Custom Badge")

    await step("Badge renders with custom className merged", async () => {
      expect(badge).toHaveClass("my-custom-class")
    })

    await step("Badge retains data-slot attribute", async () => {
      expect(badge).toHaveAttribute("data-slot", "badge")
    })
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1476" },
  },
}