import { Badge } from "./badge"

import type { Meta, StoryObj } from "@storybook/react-vite"


const meta: Meta<typeof Badge> = {
  title: "Components/Badge",
  component: Badge,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["default", "secondary", "destructive", "outline", "ghost", "link"],
    },
  },
  args: {
    children: "Badge",
    variant: "default",
  },
}

export default meta

type Story = StoryObj<typeof Badge>

export const Default: Story = {
    parameters: {
            // Auto-generated by sync-storybook-zephyr - do not add manually
            zephyr: { testCaseId: "SW-T1192" },
          }
}

export const Secondary: Story = {
  args: {
    children: "Secondary Badge",
    variant: "secondary",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1193" },
  },
}

export const Destructive: Story = {
  args: {
    children: "Destructive Badge",
    variant: "destructive",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1194" },
  },
}

export const Outline: Story = {
  args: {
    children: "Outline Badge",
    variant: "outline",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1195" },
  },
}

export const Ghost: Story = {
  args: {
    children: "Ghost Badge",
    variant: "ghost",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1196" },
  },
}

export const Link: Story = {
  args: {
    children: "Link Badge",
    variant: "link",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1197" },
  },
}