import { Button } from "./button"

import type { Meta, StoryObj } from "@storybook/react-vite"


const meta: Meta<typeof Button> = {
  title: "Components/Button",
  component: Button,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["default", "outline", "secondary", "ghost", "destructive", "link"],
    },
    size: {
      control: { type: "select" },
      options: ["default", "xs", "sm", "lg", "icon", "icon-xs", "icon-sm", "icon-lg"],
    },
  },
  args: {
    children: "Button",
    variant: "default",
    size: "default",
  },
}

export default meta

type Story = StoryObj<typeof Button>

export const Default: Story = {
    parameters: {
            // Auto-generated by sync-storybook-zephyr - do not add manually
            zephyr: { testCaseId: "SW-T1202" },
          }
}

export const Outline: Story = {
  args: {
    children: "Outline Button",
    variant: "outline",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1203" },
  },
}

export const Secondary: Story = {
  args: {
    children: "Secondary Button",
    variant: "secondary",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1204" },
  },
}

export const Ghost: Story = {
  args: {
    children: "Ghost Button",
    variant: "ghost",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1205" },
  },
}

export const Destructive: Story = {
  args: {
    children: "Destructive Button",
    variant: "destructive",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1206" },
  },
}

export const Link: Story = {
  args: {
    children: "Link Button",
    variant: "link",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1207" },
  },
}