import CodeEditor from "./code-editor";

import type { Meta, StoryObj } from "@storybook/react-vite";

const meta: Meta<typeof CodeEditor> = {
  title: "Components/CodeEditor",
  component: CodeEditor,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    language: {
      control: { type: "select" },
      options: ["python", "javascript", "json", "markdown"],
    },
    theme: {
      control: { type: "select" },
      options: ["dark", "light"],
    },
    height: {
      control: { type: "number" },
    },
    width: {
      control: { type: "text" },
    },
    label: {
      control: { type: "text" },
    },
    onChange: { action: "changed" },
    onCopy: { action: "copied" },
    onLaunch: { action: "launched" },
  },
};

export default meta;

type Story = StoryObj<typeof CodeEditor>;

const defaultHandlers = {
  onCopy: (code: string) => {
    navigator.clipboard.writeText(code);
    console.log("Code copied to clipboard");
  },
  onLaunch: (code: string) => {
    console.log("Launching code:", code);
  },
};

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T772" },
  },
  args: {
    value: "print('Hello, world!')",
    language: "python",
    theme: "dark",
    height: 400,
    width: "400px",
    label: "Description",
    ...defaultHandlers,
  },
};

export const LightMode: Story = {
  name: "Light Mode",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T773" },
  },
  args: {
    value: "console.log('Hello, world!')",
    language: "javascript",
    height: 400,
    width: "400px",
    label: "Description",
    theme: "light",
    ...defaultHandlers,
  },
};

export const ReactJavascriptExample: Story = {
  name: "React Javascript Example",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T774" },
  },
  args: {
    value: `import React, { useState, useEffect } from 'react';

function Counter() {
  const [count, setCount] = useState(0);
  
  useEffect(() => {
    document.title = \`Count: \${count}\`;
  }, [count]);
  
  return (
    <div>
      <h1>Count: {count}</h1>
      <button onClick={() => setCount(count + 1)}>
        Increment
      </button>
    </div>
  );
}

export default Counter;`,
    language: "javascript",
    height: 400,
    width: "600px",
    label: "React Counter Component",
    theme: "dark",
    ...defaultHandlers,
  },
};

export const Interactive: Story = {
  name: "Interactive",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T775" },
  },
  args: {
    value: "print('Helommlkmllo, world!')",
    language: "javascript",
    height: 400,
    width: "400px",
    label: "Description",
  },
};
