import { CopyIcon, FolderIcon, PencilIcon, Trash2Icon } from "lucide-react"
import React from "react"
import { expect, userEvent, waitFor, within } from "storybook/test"

import {
  ContextMenu,
  ContextMenuCheckboxItem,
  ContextMenuContent,
  ContextMenuGroup,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuRadioGroup,
  ContextMenuRadioItem,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuTrigger,
} from "./context-menu"

import type { Meta, StoryObj } from "@storybook/react-vite"

const meta: Meta<typeof ContextMenuItem> = {
  title: "Components/Context Menu",
  component: ContextMenuItem,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    variant: {
      control: { type: "select" },
      options: ["default", "destructive"],
    },
  },
  args: {
    variant: "default",
  },
}

export default meta

type Story = StoryObj<typeof ContextMenuItem>

function renderMenu(args: Story["args"]) {
  const destructive = args?.variant === "destructive"

  return (
    <ContextMenu>
      <ContextMenuTrigger className="flex h-40 w-[320px] items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">
        Right click this area
      </ContextMenuTrigger>
      <ContextMenuContent className="w-52">
        <ContextMenuItem>
          <PencilIcon />
          Rename
          <ContextMenuShortcut>⌘R</ContextMenuShortcut>
        </ContextMenuItem>
        <ContextMenuItem>
          <CopyIcon />
          Duplicate
          <ContextMenuShortcut>⌘D</ContextMenuShortcut>
        </ContextMenuItem>
        <ContextMenuSeparator />
        <ContextMenuItem {...args}>
          {destructive ? <Trash2Icon /> : <FolderIcon />}
          {destructive ? "Delete" : "Move to folder"}
        </ContextMenuItem>
      </ContextMenuContent>
    </ContextMenu>
  )
}

export const Default: Story = {
  render: renderMenu,
  parameters: {
    zephyr: { testCaseId: "SW-T1228" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Context menu trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify items in portal", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: 8,
          clientY: 8,
        }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("Rename")).toBeInTheDocument()
      expect(body.getByText("Duplicate")).toBeInTheDocument()
      expect(body.getByText("Move to folder")).toBeInTheDocument()
    })
  },
}

export const Destructive: Story = {
  args: {
    variant: "destructive",
  },
  render: renderMenu,
  parameters: {
    zephyr: { testCaseId: "SW-T1229" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Context menu trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify destructive item in portal", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", {
          bubbles: true,
          cancelable: true,
          clientX: 8,
          clientY: 8,
        }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("Delete")).toBeInTheDocument()
    })
  },
}

export const WithGroup: Story = {
  render: () => (
    <ContextMenu>
      <ContextMenuTrigger className="flex h-40 w-[320px] items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">
        Right click this area
      </ContextMenuTrigger>
      <ContextMenuContent className="w-52">
        <ContextMenuGroup>
          <ContextMenuLabel>File</ContextMenuLabel>
          <ContextMenuItem>
            <PencilIcon />
            Rename
            <ContextMenuShortcut>⌘R</ContextMenuShortcut>
          </ContextMenuItem>
          <ContextMenuItem>
            <CopyIcon />
            Duplicate
            <ContextMenuShortcut>⌘D</ContextMenuShortcut>
          </ContextMenuItem>
        </ContextMenuGroup>
        <ContextMenuSeparator />
        <ContextMenuGroup>
          <ContextMenuLabel>Actions</ContextMenuLabel>
          <ContextMenuItem>
            <FolderIcon />
            Move to folder
          </ContextMenuItem>
        </ContextMenuGroup>
      </ContextMenuContent>
    </ContextMenu>
  ),
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify grouped items", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", { bubbles: true, cancelable: true, clientX: 8, clientY: 8 }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("File")).toBeInTheDocument()
      expect(body.getByText("Actions")).toBeInTheDocument()
      expect(body.getByText("Rename")).toBeInTheDocument()
      expect(body.getByText("Move to folder")).toBeInTheDocument()
    })
  },
}

export const WithSubMenu: Story = {
  render: () => (
    <ContextMenu>
      <ContextMenuTrigger className="flex h-40 w-[320px] items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">
        Right click this area
      </ContextMenuTrigger>
      <ContextMenuContent className="w-52">
        <ContextMenuItem>
          <PencilIcon />
          Rename
        </ContextMenuItem>
        <ContextMenuSub>
          <ContextMenuSubTrigger>
            <FolderIcon />
            Move to
          </ContextMenuSubTrigger>
          <ContextMenuSubContent>
            <ContextMenuItem>Projects</ContextMenuItem>
            <ContextMenuItem>Archive</ContextMenuItem>
            <ContextMenuItem>Trash</ContextMenuItem>
          </ContextMenuSubContent>
        </ContextMenuSub>
        <ContextMenuSeparator />
        <ContextMenuItem variant="destructive">
          <Trash2Icon />
          Delete
        </ContextMenuItem>
      </ContextMenuContent>
    </ContextMenu>
  ),
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify sub-trigger", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", { bubbles: true, cancelable: true, clientX: 8, clientY: 8 }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("Move to")).toBeInTheDocument()
      expect(
        body.getByText("Move to").closest("[data-slot='context-menu-sub-trigger']"),
      ).toBeInTheDocument()
    })

    await step("Hover sub-trigger opens sub-content", async () => {
      const body = within(canvasElement.ownerDocument.body)
      const subTrigger = body.getByText("Move to")
      await userEvent.hover(subTrigger)
      await waitFor(() => {
        expect(body.getByText("Projects")).toBeInTheDocument()
      })
      expect(body.getByText("Archive")).toBeInTheDocument()
    })
  },
}

export const WithCheckboxItems: Story = {
  render: () => {
    const [showGrid, setShowGrid] = React.useState(true)
    const [showRulers, setShowRulers] = React.useState(false)

    return (
      <ContextMenu>
        <ContextMenuTrigger className="flex h-40 w-[320px] items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">
          Right click this area
        </ContextMenuTrigger>
        <ContextMenuContent className="w-52">
          <ContextMenuLabel>View options</ContextMenuLabel>
          <ContextMenuSeparator />
          <ContextMenuCheckboxItem checked={showGrid} onCheckedChange={setShowGrid}>
            Show grid
          </ContextMenuCheckboxItem>
          <ContextMenuCheckboxItem checked={showRulers} onCheckedChange={setShowRulers}>
            Show rulers
          </ContextMenuCheckboxItem>
        </ContextMenuContent>
      </ContextMenu>
    )
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify checkbox items", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", { bubbles: true, cancelable: true, clientX: 8, clientY: 8 }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("Show grid")).toBeInTheDocument()
      expect(body.getByText("Show rulers")).toBeInTheDocument()
    })

    await step("Checked item has data-state checked", async () => {
      const body = within(canvasElement.ownerDocument.body)
      const gridItem = body.getByText("Show grid").closest("[data-slot='context-menu-checkbox-item']")!
      expect(gridItem).toHaveAttribute("data-state", "checked")
      const rulersItem = body.getByText("Show rulers").closest("[data-slot='context-menu-checkbox-item']")!
      expect(rulersItem).toHaveAttribute("data-state", "unchecked")
    })
  },
}

export const WithRadioItems: Story = {
  render: () => {
    const [zoom, setZoom] = React.useState("100")

    return (
      <ContextMenu>
        <ContextMenuTrigger className="flex h-40 w-[320px] items-center justify-center rounded-xl border border-dashed text-sm text-muted-foreground">
          Right click this area
        </ContextMenuTrigger>
        <ContextMenuContent className="w-52">
          <ContextMenuLabel>Zoom level</ContextMenuLabel>
          <ContextMenuSeparator />
          <ContextMenuRadioGroup value={zoom} onValueChange={setZoom}>
            <ContextMenuRadioItem value="50">50%</ContextMenuRadioItem>
            <ContextMenuRadioItem value="100">100%</ContextMenuRadioItem>
            <ContextMenuRadioItem value="150">150%</ContextMenuRadioItem>
          </ContextMenuRadioGroup>
        </ContextMenuContent>
      </ContextMenu>
    )
  },
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "" },
  },
  play: async ({ canvasElement, step }) => {
    const canvas = within(canvasElement)

    await step("Trigger renders", async () => {
      expect(canvas.getByText("Right click this area")).toBeInTheDocument()
    })

    await step("Open menu and verify radio items", async () => {
      const trigger = canvas.getByText("Right click this area")
      trigger.dispatchEvent(
        new MouseEvent("contextmenu", { bubbles: true, cancelable: true, clientX: 8, clientY: 8 }),
      )
      const body = within(canvasElement.ownerDocument.body)
      expect(await body.findByText("100%")).toBeInTheDocument()
      expect(body.getByText("50%")).toBeInTheDocument()
      expect(body.getByText("150%")).toBeInTheDocument()
    })

    await step("Selected radio item has data-state checked", async () => {
      const body = within(canvasElement.ownerDocument.body)
      const hundredItem = body.getByText("100%").closest("[data-slot='context-menu-radio-item']")!
      expect(hundredItem).toHaveAttribute("data-state", "checked")
      const fiftyItem = body.getByText("50%").closest("[data-slot='context-menu-radio-item']")!
      expect(fiftyItem).toHaveAttribute("data-state", "unchecked")
    })
  },
}