import { Switch } from "./switch"

import type { Meta, StoryObj } from "@storybook/react-vite"


const meta: Meta<typeof Switch> = {
  title: "Components/Switch",
  component: Switch,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    size: {
      control: { type: "select" },
      options: ["default", "sm"],
    },
  },
  args: {
    size: "default",
  },
}

export default meta

type Story = StoryObj<typeof Switch>

export const Default: Story = {
    parameters: {
            // Auto-generated by sync-storybook-zephyr - do not add manually
            zephyr: { testCaseId: "SW-T1304" },
          }
}

export const Small: Story = {
  args: {
    size: "sm",
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1305" },
  },
}

export const Checked: Story = {
  args: {
    defaultChecked: true,
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1306" },
  },
}

export const Disabled: Story = {
  args: {
    disabled: true,
  },
  parameters: {
    zephyr: { testCaseId: "SW-T1307" },
  },
}