import { action } from "storybook/actions";
import { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "@atoms/Button";
import { Icon, IconName } from "@atoms/Icon";
import PopConfirm from "./PopConfirm";

const meta: Meta<typeof PopConfirm> = {
  title: "Atoms/PopConfirm",
  component: PopConfirm,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;
type Story = StoryObj<typeof PopConfirm>;

export const Default: Story = {
  name: "Default",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T830" },
  },
  args: {
    title: "Are you sure?",
    description: "This action cannot be undone.",
    okText: "Yes",
    cancelText: "No",
    onConfirm: action("confirmed"),
    onCancel: action("canceled"),
    children: <Button>Delete</Button>,
    placement: "top",
  },
};

export const WithIcon: Story = {
  name: "With Icon",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T831" },
  },
  args: {
    title: "Delete this item?",
    description: "This will permanently remove the item from your list.",
    okText: "Delete",
    cancelText: "Cancel",
    onConfirm: action("confirmed"),
    onCancel: action("canceled"),
    children: (
      <Button variant="tertiary" size="small" leftIcon={<Icon name={IconName.TRASH} width="16px" height="16px" />}>
        Delete
      </Button>
    ),
    placement: "left",
  },
};

export const ConfirmDelete: Story = {
  name: "Confirm Delete",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T832" },
  },
  args: {
    title: "Are you sure to delete this input?",
    description: "Doing so will remove the connected edges as well.",
    okText: "Delete",
    cancelText: "Keep",
    onConfirm: action("confirmed"),
    onCancel: action("canceled"),
    placement: "left",
    children: (
      <Button variant="tertiary" size="small" leftIcon={<Icon name={IconName.TRASH} />} aria-label="Remove item">
        {""}
      </Button>
    ),
  },
};

export const CustomButtons: Story = {
  name: "Custom Buttons",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T833" },
  },
  args: {
    title: "Are you sure?",
    description: "This will permanently delete this record.",
    okText: "Yes, delete it",
    cancelText: "No, keep it",
    onConfirm: action("confirmed"),
    onCancel: action("canceled"),
    children: <Button>Delete Record</Button>,
    placement: "bottom",
    okButtonProps: {
      style: { backgroundColor: "#ff4d4f", borderColor: "#ff4d4f" },
    },
    cancelButtonProps: {
      style: { fontWeight: 400 },
    },
  },
};

export const BottomRight: Story = {
  name: "Bottom Right",
  parameters: {
    // Auto-generated by sync-storybook-zephyr - do not add manually
    zephyr: { testCaseId: "SW-T834" },
  },
  args: {
    title: "Are you sure?",
    description: "This action cannot be undone.",
    okText: "Yes",
    cancelText: "No",
    onConfirm: action("confirmed"),
    onCancel: action("canceled"),
    children: <Button>Delete</Button>,
    placement: "bottomRight",
  },
};
